import type { ExplainerCategorySeed, ExplainerSeed } from './explainer-types';

/**
 * The American football taxonomy: the categories, and every concept the
 * library intends to cover.
 *
 * Everything in this file is a draft placeholder. Nothing here reaches the
 * site. The written explainers live in `american-football-explainers.ts`, and
 * they override these by slug, which is why the slugs here have to be right
 * first time: a typo produces a second concept rather than a written version
 * of the first.
 *
 * ## On categories
 *
 * The content brief names thirty groupings, and all thirty are kept as real
 * categories with real URLs rather than consolidated the way golf's
 * thirty-four were. American football's groupings are already closer to what
 * a reader would look for (Downs & Yards, Pass Coverages, NFL Draft, Contracts
 * & Salary Cap are each a distinct destination a fan actually searches for),
 * so collapsing them would blur searches the brief's own structure gets right.
 * They are ordered exactly as the brief lists them.
 *
 * ## On what is written vs what is taxonomy-only
 *
 * The brief lists 400+ possible explainer titles across those thirty
 * categories. Writing all of them is out of scope for this pass. What ships
 * fully written (in `american-football-explainers.ts`) is:
 *
 * - All of Category 1, Start Here (the beginner spine).
 * - All of Category 2, Downs & Yards (the brief's own "most important beginner
 *   category", including the interactive down-sequence scenarios it asks for).
 * - The six most essential Category 3, Scoring concepts.
 * - One representative explainer each from Positions (Quarterback), Pass
 *   Coverages (Cover 2), Penalties (Defensive Pass Interference), NFL Draft
 *   (The NFL Draft Explained), Clock & Game Management (Two-Minute Warning)
 *   and Advanced NFL Analytics (EPA), to prove the pattern extends into
 *   intermediate and advanced tiers without writing every category in full.
 *
 * Every other category exists below purely as taxonomy: a real slug, a real
 * name, a real description and a real difficulty tier, with zero or a
 * handful of written concepts under it. That is not an oversight, it is the
 * same shape golf shipped for the categories below its own fold: a category a
 * reader can browse to and find a short but genuine list, ready to grow in a
 * future pass without ever renaming a slug a link already points at.
 *
 * ## On duplication with the overview
 *
 * The brief's content rule applies here exactly as it does for golf: the
 * Overview says what exists ("the offense gets four downs to gain 10 yards"),
 * the Explainer says how it works (what 1st & 10, 2nd & 6 and 4th & 1 actually
 * mean, worked through with a down sequence). So there is no
 * `what-is-american-football` here, because the Overview already carries that
 * introduction, and `how-american-football-works` is written as the mechanics
 * of a game rather than as a second one.
 *
 * A handful of slugs are chosen to line up with the `explainerSlug` values the
 * Overview file already names optimistically on its `ConceptSeed` rows
 * (`downs-and-distance`, `how-scoring-works`, `offensive-positions`,
 * `defensive-tactics`, `penalties`). Those five are deliberately not
 * reused as this file's own slugs, because none of them is a single clean
 * concept: "downs-and-distance" the Overview names is served here by an
 * entire category's worth of explainers, not one page, and picking a single
 * winner among them to rename would make the other four look like an
 * afterthought. The Overview file is left untouched; a future pass can decide
 * whether to point those five references at `downs-explained`,
 * `how-scoring-works` (kept as an exact match below), `quarterback`,
 * `blitz-explained` and `defensive-pass-interference` respectively, or to
 * split them further.
 */

export const AMERICAN_FOOTBALL_EXPLAINER_CATEGORIES: ExplainerCategorySeed[] = [
  {
    slug: 'start-here',
    name: 'Start Here',
    shortName: 'Basics',
    description:
      'American football from zero: the objective, the structure, and how a game is won.',
    order: 10,
  },
  {
    slug: 'downs-and-yards',
    name: 'Downs & Yards',
    shortName: 'Downs',
    description:
      'What 1st & 10, 2nd & 6 and 4th & 1 actually mean, and why the offense only gets four tries.',
    order: 20,
  },
  {
    slug: 'scoring',
    name: 'Scoring',
    description: 'Touchdowns, field goals, extra points, two-point conversions and safeties.',
    order: 30,
  },
  {
    slug: 'positions',
    name: 'Positions',
    description: 'Every job on the field, offense, defense and special teams.',
    order: 40,
  },
  {
    slug: 'offense-basics',
    name: 'Offense Basics',
    shortName: 'Offense',
    description: 'How a play from scrimmage works: dropbacks, handoffs, the pocket and tempo.',
    order: 50,
  },
  {
    slug: 'passing',
    name: 'Passing',
    description:
      'The forward pass, what counts as a catch, and how a quarterback works through it.',
    order: 60,
  },
  {
    slug: 'receiver-routes',
    name: 'Receiver Routes',
    shortName: 'Routes',
    description: 'The route tree: every path a receiver runs, drawn on the field.',
    order: 70,
  },
  {
    slug: 'running-game',
    name: 'Running Game',
    shortName: 'Run Game',
    description: 'Zone runs, gap schemes, and how a ball carrier finds a lane.',
    order: 80,
  },
  {
    slug: 'offensive-formations',
    name: 'Offensive Formations',
    shortName: 'Formations',
    description: 'Shotgun, pistol, personnel groupings, and what 11 personnel actually means.',
    order: 90,
  },
  {
    slug: 'defense-basics',
    name: 'Defense Basics',
    shortName: 'Defense',
    description: 'Tackling, pressure, the blitz, and how a defense is built to stop a play.',
    order: 100,
  },
  {
    slug: 'defensive-formations',
    name: 'Defensive Formations',
    shortName: 'D-Formations',
    description: '4-3, 3-4, nickel and dime: how many defenders line up where, and why.',
    order: 110,
  },
  {
    slug: 'pass-coverages',
    name: 'Pass Coverages',
    shortName: 'Coverages',
    description:
      'Man, zone, and the numbered coverage shells: Cover 2, Cover 3, Cover 4 and the rest.',
    order: 120,
  },
  {
    slug: 'special-teams',
    name: 'Special Teams',
    description: 'Kickoffs, punts, field goals and the return game.',
    order: 130,
  },
  {
    slug: 'clock-and-game-management',
    name: 'Clock & Game Management',
    shortName: 'Clock',
    description:
      'The game clock, the play clock, timeouts, and how the end of a half is actually played.',
    order: 140,
  },
  {
    slug: 'penalties',
    name: 'Penalties',
    description: 'What each flag costs, and how declined and offsetting penalties work.',
    order: 150,
  },
  {
    slug: 'turnovers',
    name: 'Turnovers',
    description:
      'Interceptions, fumbles, and why they swing a game more than almost anything else.',
    order: 160,
  },
  {
    slug: 'nfl-season',
    name: 'NFL Season',
    description:
      'The regular season: schedule, divisions, standings and how the playoff field is set.',
    order: 170,
  },
  {
    slug: 'nfl-playoffs',
    name: 'NFL Playoffs',
    shortName: 'Playoffs',
    description: 'Wild Card, Divisional, Conference Championship and the Super Bowl.',
    order: 180,
  },
  {
    slug: 'nfl-draft',
    name: 'NFL Draft',
    shortName: 'Draft',
    description: 'Draft order, rounds, trades, and how a prospect becomes a pick.',
    order: 190,
  },
  {
    slug: 'contracts-and-salary-cap',
    name: 'Contracts & Salary Cap',
    shortName: 'Salary Cap',
    description:
      'Cap hits, signing bonuses, dead money and how teams build a roster within a hard cap.',
    order: 200,
  },
  {
    slug: 'rosters',
    name: 'Rosters',
    description: 'The 53-man roster, the practice squad, injured reserve and the depth chart.',
    order: 210,
  },
  {
    slug: 'nfl-statistics',
    name: 'NFL Statistics',
    shortName: 'Stats',
    description: 'The official numbers on the back of a box score, for players and for teams.',
    order: 220,
  },
  {
    slug: 'advanced-nfl-analytics',
    name: 'Advanced NFL Analytics',
    shortName: 'Analytics',
    description:
      'EPA, success rate, CPOE and the modern statistics built on top of the official ones.',
    order: 230,
  },
  {
    slug: 'quarterback-analysis',
    name: 'Quarterback Analysis',
    shortName: 'QB Analysis',
    description:
      'How to evaluate a quarterback beyond the stat line: processing, pocket presence and reads.',
    order: 240,
  },
  {
    slug: 'coaching-and-play-calling',
    name: 'Coaching & Play Calling',
    shortName: 'Coaching',
    description: 'The staff behind the roster, and how a play is actually called.',
    order: 250,
  },
  {
    slug: 'offensive-systems',
    name: 'Offensive Systems',
    description: 'West Coast, Air Raid, wide zone: the named systems modern offenses borrow from.',
    order: 260,
  },
  {
    slug: 'defensive-concepts',
    name: 'Defensive Concepts',
    description:
      'Gaps, run fits, disguised coverage and the advanced language of stopping an offense.',
    order: 270,
  },
  {
    slug: 'replay-and-officiating',
    name: 'Replay & Officiating',
    shortName: 'Officiating',
    description: 'The officials, what a catch actually requires, and how replay review works.',
    order: 280,
  },
  {
    slug: 'college-football',
    name: 'College Football',
    description:
      'NCAA football: conferences, the College Football Playoff, and how it feeds the NFL Draft.',
    order: 290,
  },
  {
    slug: 'terminology',
    name: 'Terminology',
    description: 'A searchable glossary of the words used throughout the sport.',
    order: 300,
  },
];

/**
 * Every concept, as a draft.
 *
 * `type` and `difficulty` are set here rather than left to default, because
 * they drive the page template and the beginner filter, and a taxonomy that
 * calls everything a beginner `standard` explainer is not carrying
 * information. Difficulty follows the brief's three-tier breakdown exactly:
 * Categories 1-3 are beginner, formations/routes/coverages/draft/contracts/
 * playoffs/clock management are intermediate, and analytics/coverage
 * disguises/pass-rush concepts/run fits/cap mechanics/advanced quarterback
 * analysis are advanced.
 */
export const AMERICAN_FOOTBALL_EXPLAINER_TOPICS: ExplainerSeed[] = [
  // ── Start Here ─────────────────────────────────────────────────────────────
  {
    slug: 'american-football-in-5-minutes',
    title: 'American Football in 5 Minutes',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-american-football-works',
    title: 'How American Football Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'objective-of-american-football',
    title: 'What Is the Objective of American Football?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-you-win-an-american-football-game',
    title: 'How Do You Win an American Football Game?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-an-nfl-game-is-structured',
    title: 'How an NFL Game Is Structured',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'offense-defense-and-special-teams',
    title: 'Understanding Offense, Defense & Special Teams',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'american-football-field-explained',
    title: 'American Football Field Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'american-football-positions-explained',
    title: 'American Football Positions Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['positions'],
  },
  {
    slug: 'how-scoring-works',
    title: 'How Scoring Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['scoring'],
  },
  {
    slug: 'what-are-downs',
    title: 'What Are Downs?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['downs-and-yards'],
  },
  {
    slug: 'what-is-a-first-down',
    title: 'What Is a First Down?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['downs-and-yards'],
  },
  {
    slug: 'what-is-the-line-of-scrimmage',
    title: 'What Is the Line of Scrimmage?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'what-is-a-drive',
    title: 'What Is a Drive?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-possession-works',
    title: 'How Possession Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'nfl-vs-college-football',
    title: 'NFL vs College Football',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['college-football'],
  },

  // ── Downs & Yards ──────────────────────────────────────────────────────────
  {
    slug: 'downs-explained',
    title: 'Downs Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'why-does-the-offense-get-four-downs',
    title: 'Why Does the Offense Get Four Downs?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'what-is-1st-and-10',
    title: 'What Is 1st & 10?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'what-does-2nd-and-7-mean',
    title: 'What Does 2nd & 7 Mean?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'first-down-explained',
    title: 'What Is a First Down? (Downs & Yards)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'what-happens-on-fourth-down',
    title: 'What Happens on Fourth Down?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'fourth-down-conversion',
    title: 'What Is Fourth-Down Conversion?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'turnover-on-downs',
    title: 'What Is Turnover on Downs?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
    alsoIn: ['turnovers'],
  },
  {
    slug: 'yards-to-go-explained',
    title: 'What Does "Yards to Go" Mean?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'line-to-gain-explained',
    title: 'What Is the Line to Gain?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'field-position-explained',
    title: 'What Is Field Position?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'short-yardage-explained',
    title: 'What Is Short Yardage?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'goal-to-go-explained',
    title: 'What Is Goal-to-Go?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },
  {
    slug: 'what-does-1st-and-goal-mean',
    title: 'What Does 1st & Goal Mean?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'downs-and-yards',
  },

  // ── Scoring ────────────────────────────────────────────────────────────────
  {
    slug: 'touchdown-explained',
    title: 'Touchdown Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'why-is-a-touchdown-worth-6-points',
    title: 'Why Is a Touchdown Worth 6 Points?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'field-goal-explained',
    title: 'Field Goal Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'extra-point-explained',
    title: 'Extra Point Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'two-point-conversion-explained',
    title: 'Two-Point Conversion Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'safety-explained',
    title: 'Safety Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'defensive-touchdowns',
    title: 'Defensive Touchdowns',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'pick-six-explained',
    title: 'Pick Six Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['turnovers'],
  },
  {
    slug: 'fumble-return-touchdown',
    title: 'Fumble Return Touchdown',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['turnovers'],
  },
  {
    slug: 'special-teams-touchdowns',
    title: 'Special Teams Touchdowns',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['special-teams'],
  },
  {
    slug: 'defensive-two-point-conversion',
    title: 'Defensive Two-Point Conversion',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'scoring',
  },
  {
    slug: 'what-happens-after-a-touchdown',
    title: 'What Happens After a Touchdown?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'why-teams-go-for-two',
    title: 'Why Teams Go for Two',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'when-should-teams-kick-a-field-goal',
    title: 'When Should Teams Kick a Field Goal?',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'scoring',
  },

  // ── Positions ──────────────────────────────────────────────────────────────
  {
    slug: 'positions-master-guide',
    title: 'American Football Positions: The Master Guide',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'quarterback',
    title: 'Quarterback Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'running-back-explained',
    title: 'Running Back Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'fullback-explained',
    title: 'Fullback Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'wide-receiver-explained',
    title: 'Wide Receiver Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'slot-receiver-explained',
    title: 'Slot Receiver Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
  },
  {
    slug: 'tight-end-explained',
    title: 'Tight End Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'center-explained',
    title: 'Center Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'offensive-guard-explained',
    title: 'Offensive Guard Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'offensive-tackle-explained',
    title: 'Offensive Tackle Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'offensive-line-explained',
    title: 'Offensive Line Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'defensive-tackle-explained',
    title: 'Defensive Tackle Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'nose-tackle-explained',
    title: 'Nose Tackle Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
  },
  {
    slug: 'defensive-end-explained',
    title: 'Defensive End Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'edge-rusher-explained',
    title: 'Edge Rusher Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
  },
  {
    slug: 'linebacker-explained',
    title: 'Linebacker Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'inside-linebacker-explained',
    title: 'Inside Linebacker Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
  },
  {
    slug: 'outside-linebacker-explained',
    title: 'Outside Linebacker Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
  },
  {
    slug: 'cornerback-explained',
    title: 'Cornerback Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'safety-position-explained',
    title: 'Safety (Position) Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
  },
  {
    slug: 'free-safety-vs-strong-safety',
    title: 'Free Safety vs Strong Safety',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
  },
  {
    slug: 'nickel-corner-explained',
    title: 'Nickel Corner Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
  },
  {
    slug: 'kicker-explained',
    title: 'Kicker Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
    alsoIn: ['special-teams'],
  },
  {
    slug: 'punter-explained',
    title: 'Punter Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
    alsoIn: ['special-teams'],
  },
  {
    slug: 'long-snapper-explained',
    title: 'Long Snapper Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
    alsoIn: ['special-teams'],
  },
  {
    slug: 'kick-returner-explained',
    title: 'Kick Returner Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
    alsoIn: ['special-teams'],
  },
  {
    slug: 'punt-returner-explained',
    title: 'Punt Returner Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'positions',
    alsoIn: ['special-teams'],
  },
  {
    slug: 'gunner-explained',
    title: 'Gunner Explained',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'positions',
    alsoIn: ['special-teams'],
  },

  // ── Offense Basics ─────────────────────────────────────────────────────────
  {
    slug: 'how-an-nfl-offense-works',
    title: 'How an NFL Offense Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'offense-basics',
  },
  {
    slug: 'running-play-explained',
    title: 'Running Play Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'offense-basics',
  },
  {
    slug: 'passing-play-explained',
    title: 'Passing Play Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'offense-basics',
  },
  {
    slug: 'handoff-explained',
    title: 'Handoff Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'offense-basics',
  },
  {
    slug: 'qb-dropback-explained',
    title: 'QB Dropback Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },
  {
    slug: 'pocket-explained',
    title: 'Pocket Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'offense-basics',
  },
  {
    slug: 'scramble-explained',
    title: 'Scramble Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'offense-basics',
  },
  {
    slug: 'qb-sneak-explained',
    title: 'QB Sneak Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },
  {
    slug: 'play-action-explained',
    title: 'Play-Action Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },
  {
    slug: 'screen-pass-explained',
    title: 'Screen Pass Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },
  {
    slug: 'checkdown-explained',
    title: 'Checkdown Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
    alsoIn: ['passing'],
  },
  {
    slug: 'deep-pass-explained',
    title: 'Deep Pass Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },
  {
    slug: 'shotgun-formation-explained',
    title: 'Shotgun Formation Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offense-basics',
    alsoIn: ['offensive-formations'],
  },
  {
    slug: 'under-center-explained',
    title: 'Under Center Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offense-basics',
    alsoIn: ['offensive-formations'],
  },
  {
    slug: 'no-huddle-offense-explained',
    title: 'No-Huddle Offense Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },
  {
    slug: 'hurry-up-offense-explained',
    title: 'Hurry-Up Offense Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },
  {
    slug: 'two-minute-offense-explained',
    title: 'Two-Minute Offense Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
    alsoIn: ['clock-and-game-management'],
  },
  {
    slug: 'red-zone-offense-explained',
    title: 'Red Zone Offense Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'offense-basics',
  },

  // ── Passing ────────────────────────────────────────────────────────────────
  {
    slug: 'forward-pass-rules',
    title: 'Forward Pass Rules',
    type: 'rule',
    difficulty: 'beginner',
    category: 'passing',
  },
  {
    slug: 'complete-vs-incomplete',
    title: 'Complete vs Incomplete',
    type: 'standard',
    difficulty: 'beginner',
    category: 'passing',
  },
  {
    slug: 'passing-yards-explained',
    title: 'Passing Yards Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'passing',
    alsoIn: ['nfl-statistics'],
  },
  {
    slug: 'passing-td-explained',
    title: 'Passing TD Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'passing',
    alsoIn: ['nfl-statistics'],
  },
  {
    slug: 'interception-explained',
    title: 'Interception Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'passing',
    alsoIn: ['turnovers'],
  },
  {
    slug: 'qb-sack-explained',
    title: 'QB Sack Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'passing',
    alsoIn: ['defense-basics'],
  },
  {
    slug: 'pass-protection-explained',
    title: 'Pass Protection Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'passing',
  },
  {
    slug: 'pocket-presence-explained',
    title: 'Pocket Presence Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'passing',
    alsoIn: ['quarterback-analysis'],
  },
  {
    slug: 'throwing-on-the-run-explained',
    title: 'Throwing on the Run Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'passing',
  },
  {
    slug: 'checkdowns-explained',
    title: 'Checkdowns Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'passing',
  },
  {
    slug: 'throwaway-explained',
    title: 'Throwaway Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'passing',
  },
  {
    slug: 'intentional-grounding-explained',
    title: 'Intentional Grounding Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'passing',
    alsoIn: ['penalties'],
  },
  {
    slug: 'air-yards-explained',
    title: 'Air Yards Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'passing',
    alsoIn: ['advanced-nfl-analytics'],
  },
  {
    slug: 'yac-explained',
    title: 'YAC Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'passing',
    alsoIn: ['advanced-nfl-analytics'],
  },
  {
    slug: 'deep-ball-explained',
    title: 'Deep Ball Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'passing',
  },
  {
    slug: 'contested-catch-explained',
    title: 'Contested Catch Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'passing',
  },
  {
    slug: 'catch-rules-explained',
    title: 'Catch Rules Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'passing',
    alsoIn: ['replay-and-officiating'],
  },
  {
    slug: 'what-counts-as-a-reception',
    title: 'What Counts as a Reception?',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'passing',
    alsoIn: ['replay-and-officiating'],
  },
  {
    slug: 'sideline-catch-rules',
    title: 'Sideline Catch Rules',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'passing',
    alsoIn: ['replay-and-officiating'],
  },
  {
    slug: 'qb-progressions-explained',
    title: 'QB Progressions Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'passing',
    alsoIn: ['quarterback-analysis'],
  },

  // ── Receiver Routes ────────────────────────────────────────────────────────
  {
    slug: 'route-tree-explained',
    title: 'Route Tree Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'go-route-explained',
    title: 'Go Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'slant-route-explained',
    title: 'Slant Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'post-route-explained',
    title: 'Post Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'corner-route-explained',
    title: 'Corner Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'out-route-explained',
    title: 'Out Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'in-dig-route-explained',
    title: 'In/Dig Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'curl-route-explained',
    title: 'Curl Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'comeback-route-explained',
    title: 'Comeback Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'flat-route-explained',
    title: 'Flat Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'wheel-route-explained',
    title: 'Wheel Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'crossing-route-explained',
    title: 'Crossing Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'seam-route-explained',
    title: 'Seam Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'screen-route-explained',
    title: 'Screen Route Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'double-move-explained',
    title: 'Double Move Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'receiver-routes',
  },
  {
    slug: 'option-route-explained',
    title: 'Option Route Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'receiver-routes',
  },

  // ── Running Game ───────────────────────────────────────────────────────────
  {
    slug: 'running-game-explained',
    title: 'Running Game Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'running-game',
  },
  {
    slug: 'inside-vs-outside-run',
    title: 'Inside vs Outside Run',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'running-game',
  },
  {
    slug: 'zone-running-explained',
    title: 'Zone Running Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'running-game',
  },
  {
    slug: 'inside-zone-explained',
    title: 'Inside Zone Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'running-game',
  },
  {
    slug: 'outside-zone-explained',
    title: 'Outside Zone Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'running-game',
  },
  {
    slug: 'power-run-explained',
    title: 'Power Run Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'running-game',
  },
  {
    slug: 'counter-explained',
    title: 'Counter Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'running-game',
  },
  {
    slug: 'toss-explained',
    title: 'Toss Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'running-game',
  },
  {
    slug: 'sweep-explained',
    title: 'Sweep Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'running-game',
  },
  {
    slug: 'draw-play-explained',
    title: 'Draw Play Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'running-game',
  },
  {
    slug: 'qb-run-explained',
    title: 'QB Run Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'running-game',
  },
  {
    slug: 'read-option-explained',
    title: 'Read Option Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'running-game',
    alsoIn: ['offensive-systems'],
  },
  {
    slug: 'running-lanes-explained',
    title: 'Running Lanes Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'running-game',
  },
  {
    slug: 'cutback-lane-explained',
    title: 'Cutback Lane Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'running-game',
  },
  {
    slug: 'broken-tackle-explained',
    title: 'Broken Tackle Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'running-game',
  },
  {
    slug: 'yards-after-contact-explained',
    title: 'Yards After Contact Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'running-game',
    alsoIn: ['advanced-nfl-analytics'],
  },

  // ── Offensive Formations ───────────────────────────────────────────────────
  {
    slug: 'formation-explained',
    title: 'Formation Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'shotgun-explained',
    title: 'Shotgun Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'pistol-formation-explained',
    title: 'Pistol Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'i-formation-explained',
    title: 'I-Formation Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'singleback-explained',
    title: 'Singleback Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'empty-backfield-explained',
    title: 'Empty Backfield Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'trips-explained',
    title: 'Trips Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'bunch-explained',
    title: 'Bunch Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'spread-offense-explained',
    title: 'Spread Offense Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
    alsoIn: ['offensive-systems'],
  },
  {
    slug: 'two-tight-end-sets-explained',
    title: 'Two Tight-End Sets Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'goal-line-formation-explained',
    title: 'Goal-Line Formation Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },
  {
    slug: 'personnel-groupings-explained',
    title: '11/12/21 Personnel Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'offensive-formations',
  },

  // ── Defense Basics ─────────────────────────────────────────────────────────
  {
    slug: 'how-nfl-defense-works',
    title: 'How NFL Defense Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'defense-basics',
  },
  {
    slug: 'tackling-explained',
    title: 'Tackling Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'defense-basics',
  },
  {
    slug: 'sack-explained',
    title: 'Sack Explained (Defense)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'defense-basics',
  },
  {
    slug: 'tackle-for-loss-explained',
    title: 'Tackle for Loss Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'defense-basics',
  },
  {
    slug: 'defensive-interception-explained',
    title: 'Interception Explained (Defense)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'defense-basics',
  },
  {
    slug: 'forced-fumble-explained',
    title: 'Forced Fumble Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'defense-basics',
    alsoIn: ['turnovers'],
  },
  {
    slug: 'fumble-recovery-explained',
    title: 'Fumble Recovery Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'defense-basics',
    alsoIn: ['turnovers'],
  },
  {
    slug: 'pass-breakup-explained',
    title: 'Pass Breakup Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'defense-basics',
  },
  {
    slug: 'pressure-explained',
    title: 'Pressure Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'defense-basics',
  },
  {
    slug: 'qb-hit-explained',
    title: 'QB Hit Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'defense-basics',
  },
  {
    slug: 'blitz-explained',
    title: 'Blitz Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'defense-basics',
  },
  {
    slug: 'pass-rush-explained',
    title: 'Pass Rush Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'defense-basics',
  },
  {
    slug: 'run-defense-explained',
    title: 'Run Defense Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'defense-basics',
  },
  {
    slug: 'red-zone-defense-explained',
    title: 'Red Zone Defense Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'defense-basics',
  },

  // ── Defensive Formations ───────────────────────────────────────────────────
  {
    slug: 'defensive-front-explained',
    title: 'Defensive Front Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'defensive-formations',
  },
  {
    slug: 'four-three-defense-explained',
    title: '4-3 Defense Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'defensive-formations',
  },
  {
    slug: 'three-four-defense-explained',
    title: '3-4 Defense Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'defensive-formations',
  },
  {
    slug: 'nickel-defense-explained',
    title: 'Nickel Defense Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'defensive-formations',
  },
  {
    slug: 'dime-defense-explained',
    title: 'Dime Defense Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'defensive-formations',
  },
  {
    slug: 'goal-line-defense-explained',
    title: 'Goal-Line Defense Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'defensive-formations',
  },
  {
    slug: 'dl-techniques-explained',
    title: 'DL Techniques Explained',
    type: 'formation',
    difficulty: 'advanced',
    category: 'defensive-formations',
    alsoIn: ['defensive-concepts'],
  },
  {
    slug: 'gap-responsibilities-explained',
    title: 'Gap Responsibilities Explained',
    type: 'formation',
    difficulty: 'advanced',
    category: 'defensive-formations',
    alsoIn: ['defensive-concepts'],
  },
  {
    slug: 'box-count-explained',
    title: 'Box Count Explained',
    type: 'formation',
    difficulty: 'intermediate',
    category: 'defensive-formations',
  },
  {
    slug: 'seven-man-front-explained',
    title: 'Seven-Man Front Explained',
    type: 'formation',
    difficulty: 'advanced',
    category: 'defensive-formations',
  },

  // ── Pass Coverages ─────────────────────────────────────────────────────────
  {
    slug: 'man-coverage-explained',
    title: 'Man Coverage Explained',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'zone-coverage-explained',
    title: 'Zone Coverage Explained',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'man-vs-zone-explained',
    title: 'Man vs Zone Explained',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'cover-0-explained',
    title: 'Cover 0 Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
  },
  {
    slug: 'cover-1-explained',
    title: 'Cover 1 Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
  },
  {
    slug: 'cover-2-explained',
    title: 'What Is Cover 2 Defense?',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'cover-3-explained',
    title: 'Cover 3 Explained',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'cover-4-explained',
    title: 'Cover 4 Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
  },
  {
    slug: 'cover-6-explained',
    title: 'Cover 6 Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
  },
  {
    slug: 'tampa-2-explained',
    title: 'Tampa 2 Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
  },
  {
    slug: 'press-coverage-explained',
    title: 'Press Coverage Explained',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'off-coverage-explained',
    title: 'Off Coverage Explained',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'double-team-coverage-explained',
    title: 'Double Team (Coverage) Explained',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'pass-coverages',
  },
  {
    slug: 'match-coverage-explained',
    title: 'Match Coverage Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
  },
  {
    slug: 'bracket-coverage-explained',
    title: 'Bracket Coverage Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
  },
  {
    slug: 'how-qbs-read-coverage',
    title: 'How QBs Read Coverage',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'pass-coverages',
    alsoIn: ['quarterback-analysis'],
  },

  // ── Special Teams ──────────────────────────────────────────────────────────
  {
    slug: 'special-teams-explained',
    title: 'Special Teams Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'kickoff-explained',
    title: 'Kickoff Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'punt-explained',
    title: 'Punt Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'fg-attempt-explained',
    title: 'FG Attempt Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'extra-point-attempt-explained',
    title: 'Extra Point (Attempt) Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'kick-return-explained',
    title: 'Kick Return Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'punt-return-explained',
    title: 'Punt Return Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'touchback-explained',
    title: 'Touchback Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'fair-catch-explained',
    title: 'Fair Catch Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'special-teams',
  },
  {
    slug: 'onside-kick-explained',
    title: 'Onside Kick Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'special-teams',
  },
  {
    slug: 'coffin-corner-punt-explained',
    title: 'Coffin Corner Punt Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'special-teams',
  },
  {
    slug: 'punting-for-field-position',
    title: 'Punting for Field Position',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'special-teams',
  },
  {
    slug: 'blocked-punt-explained',
    title: 'Blocked Punt Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'special-teams',
  },
  {
    slug: 'blocked-fg-explained',
    title: 'Blocked FG Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'special-teams',
  },
  {
    slug: 'long-snapper-role-explained',
    title: 'Long Snapper Role Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'special-teams',
  },

  // ── Clock & Game Management ────────────────────────────────────────────────
  {
    slug: 'game-clock-explained',
    title: 'Game Clock Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'clock-and-game-management',
  },
  {
    slug: 'play-clock-explained',
    title: 'Play Clock Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'clock-and-game-management',
  },
  {
    slug: 'when-does-the-clock-stop',
    title: 'When Does the Clock Stop?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'clock-and-game-management',
  },
  {
    slug: 'timeout-rules-explained',
    title: 'Timeout Rules Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'clock-and-game-management',
  },
  {
    slug: 'two-minute-warning-explained',
    title: 'Two-Minute Warning Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },
  {
    slug: 'clock-management-explained',
    title: 'Clock Management Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },
  {
    slug: 'running-out-the-clock',
    title: 'Running Out the Clock',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },
  {
    slug: 'taking-a-knee-explained',
    title: 'Taking a Knee Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'clock-and-game-management',
  },
  {
    slug: 'spike-explained',
    title: 'Spike Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'clock-and-game-management',
  },
  {
    slug: 'why-qbs-spike-the-ball',
    title: 'Why QBs Spike the Ball',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },
  {
    slug: 'delay-of-game-explained',
    title: 'Delay of Game Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'clock-and-game-management',
    alsoIn: ['penalties'],
  },
  {
    slug: 'two-minute-drill-explained',
    title: 'Two-Minute Drill Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },
  {
    slug: 'four-minute-offense-explained',
    title: 'Four-Minute Offense Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },
  {
    slug: 'end-of-game-strategy-explained',
    title: 'End-of-Game Strategy Explained',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },
  {
    slug: 'overtime-explained',
    title: 'Overtime Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'clock-and-game-management',
  },

  // ── Penalties ──────────────────────────────────────────────────────────────
  {
    slug: 'how-penalties-work',
    title: 'How Penalties Work',
    type: 'rule',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'false-start-explained',
    title: 'False Start Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'offside-explained',
    title: 'Offside Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'encroachment-explained',
    title: 'Encroachment Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'neutral-zone-infraction-explained',
    title: 'Neutral Zone Infraction Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'holding-explained',
    title: 'Holding Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'defensive-holding-explained',
    title: 'Defensive Holding Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'pass-interference-explained',
    title: 'Pass Interference Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'defensive-pass-interference-explained',
    title: 'What Is Defensive Pass Interference?',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'illegal-contact-explained',
    title: 'Illegal Contact Explained',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'roughing-the-passer-explained',
    title: 'Roughing the Passer Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'facemask-explained',
    title: 'Facemask Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'unnecessary-roughness-explained',
    title: 'Unnecessary Roughness Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'personal-foul-explained',
    title: 'Personal Foul Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'targeting-vs-nfl-helmet-rules',
    title: 'Targeting vs NFL Helmet Rules',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties',
    alsoIn: ['college-football'],
  },
  {
    slug: 'illegal-formation-explained',
    title: 'Illegal Formation Explained',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'illegal-motion-explained',
    title: 'Illegal Motion Explained',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'illegal-shift-explained',
    title: 'Illegal Shift Explained',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'too-many-men-explained',
    title: 'Too Many Men Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'unsportsmanlike-conduct-explained',
    title: 'Unsportsmanlike Conduct Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties',
  },
  {
    slug: 'dpi-vs-holding',
    title: 'DPI vs Holding',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'declining-a-penalty-explained',
    title: 'Declining a Penalty Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'offset-penalties-explained',
    title: 'Offset Penalties Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'automatic-first-down-explained',
    title: 'Automatic First Down Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties',
  },
  {
    slug: 'loss-of-down-explained',
    title: 'Loss of Down Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties',
  },

  // ── Turnovers ──────────────────────────────────────────────────────────────
  {
    slug: 'turnover-explained',
    title: 'Turnover Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'turnovers',
  },
  {
    slug: 'turnover-interception-explained',
    title: 'Interception Explained (Turnovers)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'turnovers',
  },
  {
    slug: 'fumble-explained',
    title: 'Fumble Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'turnovers',
  },
  {
    slug: 'turnover-forced-fumble-explained',
    title: 'Forced Fumble Explained (Turnovers)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'turnovers',
  },
  {
    slug: 'turnover-fumble-recovery-explained',
    title: 'Fumble Recovery Explained (Turnovers)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'turnovers',
  },
  {
    slug: 'turnover-on-downs-category',
    title: 'Turnover on Downs (Turnovers)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'turnovers',
  },
  {
    slug: 'turnover-pick-six-explained',
    title: 'Pick Six Explained (Turnovers)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'turnovers',
  },
  {
    slug: 'scoop-and-score-explained',
    title: 'Scoop and Score Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'turnovers',
  },
  {
    slug: 'strip-sack-explained',
    title: 'Strip Sack Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'turnovers',
  },
  {
    slug: 'why-turnovers-matter-so-much',
    title: 'Why Turnovers Matter So Much',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'turnovers',
    alsoIn: ['nfl-statistics'],
  },

  // ── NFL Season ─────────────────────────────────────────────────────────────
  {
    slug: 'how-nfl-season-works',
    title: 'How NFL Season Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'preseason-explained',
    title: 'Preseason Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'regular-season-explained',
    title: 'Regular Season Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'nfl-schedule-explained',
    title: 'Schedule Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'division-games-explained',
    title: 'Division Games Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'conference-games-explained',
    title: 'Conference Games Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'bye-week-explained',
    title: 'Bye Week Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'standings-explained',
    title: 'Standings Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'winning-percentage-explained',
    title: 'Winning Percentage Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-season',
  },
  {
    slug: 'strength-of-schedule-explained',
    title: 'Strength of Schedule Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'nfl-season',
  },
  {
    slug: 'how-teams-qualify-for-playoffs',
    title: 'How Teams Qualify for Playoffs',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'nfl-season',
    alsoIn: ['nfl-playoffs'],
  },

  // ── NFL Playoffs ───────────────────────────────────────────────────────────
  {
    slug: 'nfl-playoffs-explained',
    title: 'Playoffs Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'nfl-playoffs',
  },
  {
    slug: 'wild-card-explained',
    title: 'Wild Card Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'nfl-playoffs',
  },
  {
    slug: 'playoff-seeding-explained',
    title: 'Playoff Seeding Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nfl-playoffs',
  },
  {
    slug: 'first-round-bye-explained',
    title: 'First-Round Bye Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nfl-playoffs',
  },
  {
    slug: 'wild-card-round-explained',
    title: 'Wild Card Round Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'nfl-playoffs',
  },
  {
    slug: 'divisional-round-explained',
    title: 'Divisional Round Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'nfl-playoffs',
  },
  {
    slug: 'conference-championship-explained',
    title: 'Conference Championship Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'nfl-playoffs',
  },
  {
    slug: 'super-bowl-explained',
    title: 'Super Bowl Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'nfl-playoffs',
  },
  {
    slug: 'home-field-advantage-explained',
    title: 'Home-Field Advantage Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'nfl-playoffs',
  },
  {
    slug: 'playoff-tiebreakers-explained',
    title: 'Playoff Tiebreakers Explained',
    type: 'format',
    difficulty: 'advanced',
    category: 'nfl-playoffs',
  },
  {
    slug: 'how-the-playoff-bracket-works',
    title: 'How the Bracket Works',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nfl-playoffs',
  },
  {
    slug: 'why-no-two-legged-ties',
    title: 'Why No Two-Legged Ties',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nfl-playoffs',
  },

  // ── NFL Draft ──────────────────────────────────────────────────────────────
  {
    slug: 'nfl-draft-explained',
    title: 'The NFL Draft Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'draft-order-explained',
    title: 'Draft Order Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'why-worst-teams-pick-first',
    title: 'Why Worst Teams Pick First',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'draft-rounds-explained',
    title: 'Draft Rounds Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'draft-picks-explained',
    title: 'Draft Picks Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'trading-picks-explained',
    title: 'Trading Picks Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'future-picks-explained',
    title: 'Future Picks Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'first-overall-pick-explained',
    title: 'First Overall Pick Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'compensatory-picks-explained',
    title: 'Compensatory Picks Explained',
    type: 'procedure',
    difficulty: 'advanced',
    category: 'nfl-draft',
  },
  {
    slug: 'nfl-combine-explained',
    title: 'Combine Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'pro-day-explained',
    title: 'Pro Day Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'draft-board-explained',
    title: 'Draft Board Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'mock-draft-explained',
    title: 'Mock Draft Explained',
    type: 'procedure',
    difficulty: 'beginner',
    category: 'nfl-draft',
  },
  {
    slug: 'prospect-grades-explained',
    title: 'Prospect Grades Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'draft-day-trades-explained',
    title: 'Draft Day Trades Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'draft-bust-explained',
    title: 'Draft Bust Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-draft',
  },
  {
    slug: 'draft-steal-explained',
    title: 'Draft Steal Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-draft',
  },
  {
    slug: 'udfas-explained',
    title: 'UDFAs Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'nfl-draft',
  },
  {
    slug: 'mr-irrelevant-explained',
    title: 'Mr. Irrelevant Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'nfl-draft',
  },

  // ── Contracts & Salary Cap ─────────────────────────────────────────────────
  {
    slug: 'nfl-contracts-explained',
    title: 'Contracts Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'salary-cap-explained',
    title: 'Salary Cap Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'guaranteed-money-explained',
    title: 'Guaranteed Money Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'signing-bonus-explained',
    title: 'Signing Bonus Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'base-salary-explained',
    title: 'Base Salary Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'cap-hit-explained',
    title: 'Cap Hit Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'dead-cap-explained',
    title: 'Dead Cap Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'restructured-contract-explained',
    title: 'Restructured Contract Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'contract-extension-explained',
    title: 'Contract Extension Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'rookie-contracts-explained',
    title: 'Rookie Contracts Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'fifth-year-option-explained',
    title: 'Fifth-Year Option Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'franchise-tag-explained',
    title: 'Franchise Tag Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'transition-tag-explained',
    title: 'Transition Tag Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'free-agency-explained',
    title: 'Free Agency Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'rfa-explained',
    title: 'RFA Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'ufa-explained',
    title: 'UFA Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'waivers-explained',
    title: 'Waivers Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'practice-squad-explained',
    title: 'Practice Squad Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'contracts-and-salary-cap',
    alsoIn: ['rosters'],
  },
  {
    slug: 'cap-space-explained',
    title: 'Cap Space Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'contracts-and-salary-cap',
  },
  {
    slug: 'void-years-explained',
    title: 'Void Years Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'contracts-and-salary-cap',
  },

  // ── Rosters ────────────────────────────────────────────────────────────────
  {
    slug: 'roster-explained',
    title: 'Roster Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rosters',
  },
  {
    slug: '53-man-roster-explained',
    title: '53-Man Roster Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rosters',
  },
  {
    slug: 'active-game-day-roster-explained',
    title: 'Active Game-Day Roster Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rosters',
  },
  {
    slug: 'rosters-practice-squad-explained',
    title: 'Practice Squad Explained (Rosters)',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rosters',
  },
  {
    slug: 'injured-reserve-explained',
    title: 'Injured Reserve Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'rosters',
  },
  {
    slug: 'pup-list-explained',
    title: 'PUP List Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'rosters',
  },
  {
    slug: 'depth-chart-explained',
    title: 'Depth Chart Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rosters',
  },
  {
    slug: 'starter-vs-backup-explained',
    title: 'Starter vs Backup Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rosters',
  },
  {
    slug: 'healthy-scratch-explained',
    title: 'Healthy Scratch Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'rosters',
  },
  {
    slug: 'roster-cuts-explained',
    title: 'Roster Cuts Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'rosters',
  },

  // ── NFL Statistics ─────────────────────────────────────────────────────────
  {
    slug: 'passing-yards-statistic',
    title: 'Passing Yards (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'passing-tds-statistic',
    title: 'Passing TDs (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'ints-statistic',
    title: 'INTs (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'completion-percentage-explained',
    title: 'Completion % Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'rushing-yards-statistic',
    title: 'Rushing Yards (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'receiving-yards-statistic',
    title: 'Receiving Yards (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'receptions-statistic',
    title: 'Receptions (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'tds-statistic',
    title: 'TDs (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'sacks-statistic',
    title: 'Sacks (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'tackles-statistic',
    title: 'Tackles (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'defensive-ints-statistic',
    title: 'Defensive INTs (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'total-yards-statistic',
    title: 'Total Yards (Team Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'points-per-game-statistic',
    title: 'Points Per Game (Statistic)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'nfl-statistics',
  },
  {
    slug: 'third-down-conversion-statistic',
    title: 'Third-Down Conversion (Statistic)',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'nfl-statistics',
  },
  {
    slug: 'red-zone-percentage-statistic',
    title: 'Red Zone % (Statistic)',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'nfl-statistics',
  },
  {
    slug: 'turnover-differential-statistic',
    title: 'Turnover Differential (Statistic)',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'nfl-statistics',
  },
  {
    slug: 'time-of-possession-statistic',
    title: 'Time of Possession (Statistic)',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'nfl-statistics',
  },

  // ── Advanced NFL Analytics ─────────────────────────────────────────────────
  {
    slug: 'epa-explained',
    title: 'EPA Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'epa-per-play-explained',
    title: 'EPA per Play Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'success-rate-explained',
    title: 'Success Rate Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'cpoe-explained',
    title: 'CPOE Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'expected-completion-percentage-explained',
    title: 'Expected Completion % Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'adot-explained',
    title: 'ADOT Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'pressure-rate-explained',
    title: 'Pressure Rate Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'sack-rate-explained',
    title: 'Sack Rate Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'pass-rush-win-rate-explained',
    title: 'Pass Rush Win Rate Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'pass-block-win-rate-explained',
    title: 'Pass Block Win Rate Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'qb-rating-explained',
    title: 'QB Rating Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'passer-rating-explained',
    title: 'Passer Rating Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'qbr-explained',
    title: 'QBR Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'expected-points-explained',
    title: 'Expected Points Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'win-probability-explained',
    title: 'Win Probability Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'wpa-explained',
    title: 'WPA Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },
  {
    slug: 'fourth-down-decision-models-explained',
    title: 'Fourth-Down Decision Models Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-nfl-analytics',
  },

  // ── Quarterback Analysis ───────────────────────────────────────────────────
  {
    slug: 'how-to-evaluate-a-qb',
    title: 'How to Evaluate a QB',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'accuracy-explained',
    title: 'Accuracy Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'arm-strength-explained',
    title: 'Arm Strength Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'quarterback-analysis',
  },
  {
    slug: 'processing-explained',
    title: 'Processing Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'pre-snap-reads-explained',
    title: 'Pre-Snap Reads Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'post-snap-reads-explained',
    title: 'Post-Snap Reads Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'blitz-recognition-explained',
    title: 'Blitz Recognition Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'throwing-under-pressure-explained',
    title: 'Throwing Under Pressure Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'deep-ball-accuracy-explained',
    title: 'Deep-Ball Accuracy Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'mobility-explained',
    title: 'Mobility Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'quarterback-analysis',
  },
  {
    slug: 'scrambling-analysis-explained',
    title: 'Scrambling Explained (QB Analysis)',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'quarterback-analysis',
  },
  {
    slug: 'play-action-passing-explained',
    title: 'Play-Action Passing Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'qb-rating-metrics-explained',
    title: 'QB Rating Metrics Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'quarterback-analysis',
  },
  {
    slug: 'game-manager-explained',
    title: 'Game Manager Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'quarterback-analysis',
  },
  {
    slug: 'dual-threat-qb-explained',
    title: 'Dual-Threat QB Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'quarterback-analysis',
  },

  // ── Coaching & Play Calling ────────────────────────────────────────────────
  {
    slug: 'head-coach-explained',
    title: 'Head Coach Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'offensive-coordinator-explained',
    title: 'Offensive Coordinator Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'defensive-coordinator-explained',
    title: 'Defensive Coordinator Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'special-teams-coordinator-explained',
    title: 'Special Teams Coordinator Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'position-coaches-explained',
    title: 'Position Coaches Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'play-caller-explained',
    title: 'Play Caller Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'offensive-defensive-play-calling-explained',
    title: 'Offensive/Defensive Play Calling Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'halftime-adjustments-explained',
    title: 'Halftime Adjustments Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'game-plan-explained',
    title: 'Game Plan Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'scripted-plays-explained',
    title: 'Scripted Plays Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'challenge-flag-explained',
    title: 'Challenge Flag Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'coaching-and-play-calling',
    alsoIn: ['replay-and-officiating'],
  },
  {
    slug: 'timeout-strategy-explained',
    title: 'Timeout Strategy Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'coaching-and-play-calling',
  },
  {
    slug: 'fourth-down-decision-making-explained',
    title: 'Fourth-Down Decision Making Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'coaching-and-play-calling',
  },

  // ── Offensive Systems ──────────────────────────────────────────────────────
  {
    slug: 'west-coast-offense-explained',
    title: 'West Coast Offense Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'air-coryell-explained',
    title: 'Air Coryell Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'spread-offense-system-explained',
    title: 'Spread Offense (System) Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'air-raid-explained',
    title: 'Air Raid Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'shanahan-wide-zone-explained',
    title: 'Shanahan-Style Wide Zone Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'erhardt-perkins-explained',
    title: 'Erhardt-Perkins Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'rpo-explained',
    title: 'RPO Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'systems-read-option-explained',
    title: 'Read Option Explained (Systems)',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'play-action-offense-explained',
    title: 'Play-Action Offense Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'motion-based-offense-explained',
    title: 'Motion-Based Offense Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },
  {
    slug: 'west-coast-vs-air-raid',
    title: 'West Coast vs Air Raid',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offensive-systems',
  },

  // ── Defensive Concepts ─────────────────────────────────────────────────────
  {
    slug: 'defensive-gaps-explained',
    title: 'Defensive Gaps Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'a-b-c-gap-explained',
    title: 'A/B/C-Gap Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'edge-setting-explained',
    title: 'Edge Setting Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'contain-explained',
    title: 'Contain Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'spy-explained',
    title: 'Spy Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'stunt-explained',
    title: 'Stunt Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'twist-explained',
    title: 'Twist Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'zone-blitz-explained',
    title: 'Zone Blitz Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'simulated-pressure-explained',
    title: 'Simulated Pressure Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'disguised-coverage-explained',
    title: 'Disguised Coverage Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'safety-rotation-explained',
    title: 'Safety Rotation Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'single-high-safety-explained',
    title: 'Single-High Safety Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'two-high-safety-explained',
    title: 'Two-High Safety Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'box-safety-explained',
    title: 'Box Safety Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },
  {
    slug: 'run-fits-explained',
    title: 'Run Fits Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defensive-concepts',
  },

  // ── Replay & Officiating ───────────────────────────────────────────────────
  {
    slug: 'officials-explained',
    title: 'Officials Explained',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'replay-and-officiating',
  },
  {
    slug: 'referee-roles-explained',
    title: 'Referee Roles Explained',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'replay-and-officiating',
  },
  {
    slug: 'replay-review-explained',
    title: 'Replay Review Explained',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },
  {
    slug: 'coachs-challenge-explained',
    title: "Coach's Challenge Explained",
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },
  {
    slug: 'automatic-reviews-explained',
    title: 'Automatic Reviews Explained',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },
  {
    slug: 'what-is-a-catch',
    title: 'What Is a Catch?',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },
  {
    slug: 'down-by-contact-explained',
    title: 'Down by Contact Explained',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'replay-and-officiating',
  },
  {
    slug: 'forward-progress-explained',
    title: 'Forward Progress Explained',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },
  {
    slug: 'spot-of-the-ball-explained',
    title: 'Spot of the Ball Explained',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },
  {
    slug: 'chains-first-down-measurement-explained',
    title: 'Chains/First-Down Measurement Explained',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },
  {
    slug: 'replay-assistant-explained',
    title: 'Replay Assistant Explained',
    type: 'officiating',
    difficulty: 'advanced',
    category: 'replay-and-officiating',
  },
  {
    slug: 'why-some-calls-cant-be-challenged',
    title: "Why Some Calls Can't Be Challenged",
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'replay-and-officiating',
  },

  // ── College Football ───────────────────────────────────────────────────────
  {
    slug: 'college-football-explained',
    title: 'College Football Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'college-football',
  },
  {
    slug: 'ncaa-vs-nfl-rules',
    title: 'NCAA vs NFL Rules',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'conferences-explained',
    title: 'Conferences Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'college-football',
  },
  {
    slug: 'college-football-playoff-explained',
    title: 'College Football Playoff Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'bowl-games-explained',
    title: 'Bowl Games Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'college-football',
  },
  {
    slug: 'national-championship-explained',
    title: 'National Championship Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'college-football',
  },
  {
    slug: 'college-rankings-explained',
    title: 'College Rankings Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'ap-poll-explained',
    title: 'AP Poll Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'conference-championship-games-explained',
    title: 'Conference Championship Games Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'college-football',
  },
  {
    slug: 'redshirt-explained',
    title: 'Redshirt Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'transfer-portal-explained',
    title: 'Transfer Portal Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'nil-explained',
    title: 'NIL Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'college-recruiting-explained',
    title: 'College Recruiting Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'five-star-recruit-explained',
    title: 'Five-Star Recruit Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'college-football',
  },
  {
    slug: 'college-to-nfl-draft-explained',
    title: 'College to NFL Draft Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'college-football',
    alsoIn: ['nfl-draft'],
  },

  // ── Terminology ────────────────────────────────────────────────────────────
  {
    slug: 'audible-glossary',
    title: 'Audible',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'blitz-glossary',
    title: 'Blitz (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'checkdown-glossary',
    title: 'Checkdown (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'completion-glossary',
    title: 'Completion',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'down-glossary',
    title: 'Down (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'drive-glossary',
    title: 'Drive (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'end-zone-glossary',
    title: 'End Zone (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'false-start-glossary',
    title: 'False Start (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'field-goal-glossary',
    title: 'Field Goal (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'first-down-glossary',
    title: 'First Down (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'formation-glossary',
    title: 'Formation (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'fumble-glossary',
    title: 'Fumble (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'handoff-glossary',
    title: 'Handoff (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'hash-marks-glossary',
    title: 'Hash Marks',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'huddle-glossary',
    title: 'Huddle',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'interception-glossary',
    title: 'Interception (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'line-of-scrimmage-glossary',
    title: 'Line of Scrimmage (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'motion-glossary',
    title: 'Motion',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'offside-glossary',
    title: 'Offside (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'pass-rush-glossary',
    title: 'Pass Rush (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'pocket-glossary',
    title: 'Pocket (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'possession-glossary',
    title: 'Possession (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'punt-glossary',
    title: 'Punt (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'red-zone-glossary',
    title: 'Red Zone (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'route-glossary',
    title: 'Route',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'sack-glossary',
    title: 'Sack (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'safety-glossary',
    title: 'Safety (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'scramble-glossary',
    title: 'Scramble (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'snap-glossary',
    title: 'Snap',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'touchdown-glossary',
    title: 'Touchdown (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'turnover-glossary',
    title: 'Turnover (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'two-minute-drill-glossary',
    title: 'Two-Minute Drill (Glossary)',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
  {
    slug: 'yards-after-catch-glossary',
    title: 'Yards After Catch',
    type: 'definition',
    difficulty: 'beginner',
    category: 'terminology',
  },
];

/**
 * The "Learn American Football From Scratch" guided path.
 *
 * Twelve steps, per the brief, each naming the slug of the explainer that
 * best represents that step. All twelve resolve to real, written explainers
 * in this pass.
 */
export const AMERICAN_FOOTBALL_LEARN_PATH: { step: number; title: string; slug: string }[] = [
  { step: 1, title: 'What Is American Football?', slug: 'american-football-in-5-minutes' },
  { step: 2, title: 'The Field', slug: 'american-football-field-explained' },
  { step: 3, title: 'Downs Explained', slug: 'downs-and-distance' },
  { step: 4, title: 'Scoring', slug: 'how-scoring-works' },
  { step: 5, title: 'Positions', slug: 'american-football-positions-explained' },
  { step: 6, title: 'Offense vs Defense', slug: 'offense-defense-special-teams' },
  { step: 7, title: 'Running vs Passing', slug: 'zone-running-explained' },
  { step: 8, title: 'Penalties', slug: 'penalties' },
  { step: 9, title: 'NFL Season', slug: 'how-an-nfl-game-is-structured' },
  { step: 10, title: 'NFL Playoffs', slug: 'nfl-playoffs-explained' },
  { step: 11, title: 'Formations', slug: 'personnel-groupings-explained' },
  { step: 12, title: 'Strategy & Analytics', slug: 'epa-explained' },
];
