import type { ExplainerCategorySeed, ExplainerSeed } from './explainer-types';

/**
 * The basketball taxonomy: the categories, and every concept the library
 * intends to cover.
 *
 * Everything in this file is a draft placeholder. Nothing here reaches the
 * site. The written explainers live in `basketball-explainers.ts` and override
 * these by slug, which is why the slugs here have to be right first time: a
 * typo produces a second concept rather than a written version of the first.
 *
 * Seeding the whole taxonomy ahead of the writing is deliberate. It gives the
 * duplicate check something to work against before the articles exist, fixes
 * the URL of every concept on the day it is named, and means the categories on
 * the landing page are the real structure rather than whatever happens to be
 * finished.
 *
 * ## On categories
 *
 * Eight categories are shown on the landing page. That number is a product
 * decision rather than a limit of the schema: a reader who is shown twenty
 * headings is being asked to do the organising themselves.
 *
 * Basketball needs many-to-many membership as much as cricket does. A pick and
 * roll is an offensive action, the thing drop coverage exists to defend, and a
 * concept a beginner meets in their first game. The corner three is a shot, a
 * spot on the floor, and the payoff of drive-and-kick. Each is one row with
 * `alsoIn`, never three rows, and the unique index on (sport_id, slug) makes
 * that a guarantee rather than a convention.
 *
 * ## On the NBA
 *
 * The NBA has its own category because a reader meets NBA-specific machinery
 * constantly and needs somewhere to look it up. It is one category of eight,
 * and the rules categories describe the sport rather than the NBA: where a
 * competition differs, that belongs in a `rule_differences` section of the
 * concept, not in a separate NBA article. See `basketball-explainers.ts`.
 */

export const BASKETBALL_EXPLAINER_CATEGORIES: ExplainerCategorySeed[] = [
  {
    slug: 'rules-and-basics',
    name: 'Rules & Basics',
    shortName: 'Basics',
    description: 'Basketball from zero: how a game is played, won, timed and scored.',
    order: 10,
  },
  {
    slug: 'court-and-positions',
    name: 'Court & Positions',
    shortName: 'Court',
    description: 'Where everything happens on the floor, and who does what.',
    order: 20,
  },
  {
    slug: 'fouls-and-violations',
    name: 'Fouls & Violations',
    shortName: 'Fouls',
    description: 'What stops play, what it costs, and how the calls are judged.',
    order: 30,
  },
  {
    slug: 'offense',
    name: 'Offense',
    description: 'How teams create good shots: actions, spacing and movement.',
    order: 40,
  },
  {
    slug: 'defense',
    name: 'Defense',
    description: 'How teams take good shots away: schemes, coverages and rotations.',
    order: 50,
  },
  {
    slug: 'statistics',
    name: 'Basketball Statistics',
    shortName: 'Stats',
    description: 'Reading a box score, and what the advanced numbers actually measure.',
    order: 60,
  },
  {
    slug: 'nba-explained',
    name: 'NBA Explained',
    shortName: 'NBA',
    description: 'The season, the playoffs, the draft, trades and the salary cap.',
    order: 70,
  },
  {
    slug: 'international-basketball',
    name: 'International Basketball',
    shortName: 'International',
    description: 'FIBA, the Olympics, Europe, college and the women’s game.',
    order: 80,
  },
  /*
   * Below the fold.
   *
   * Real categories with real URLs, reachable from a concept's breadcrumb and
   * from search, but not among the eight the landing page leads with. This is
   * how the taxonomy grows past what a landing page can show without either
   * hiding concepts or turning the page into a directory.
   */
  {
    slug: 'shooting',
    name: 'Shooting',
    description: 'Every way the ball goes in, from a layup to a step-back three.',
    order: 90,
  },
  {
    slug: 'rebounding',
    name: 'Rebounding',
    description: 'What happens after a miss, and why it decides possessions.',
    order: 100,
  },
  {
    slug: 'glossary',
    name: 'Glossary',
    description: 'The slang: what a dime, a brick, a poster and a heat check are.',
    order: 110,
  },
];

/**
 * Every concept, as a draft.
 *
 * `type` and `difficulty` are set here rather than left to default, because
 * they drive the page template and the beginner filter, and a taxonomy that
 * calls everything a beginner `standard` explainer is not carrying information.
 */
export const BASKETBALL_EXPLAINER_TOPICS: ExplainerSeed[] = [
  // ── Rules & basics ─────────────────────────────────────────────────────────
  {
    slug: 'how-basketball-works',
    title: 'How Basketball Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'how-a-basketball-game-starts',
    title: 'How a Basketball Game Starts',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'how-you-win-a-basketball-game',
    title: 'How You Win a Basketball Game',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'how-scoring-works',
    title: 'How Scoring Works',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'possession',
    title: 'How Possession Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'how-long-a-basketball-game-is',
    title: 'How Long a Basketball Game Is',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'game-clock',
    title: 'Game Clock Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'shot-clock',
    title: 'Shot Clock Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'overtime',
    title: 'Overtime Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'timeouts',
    title: 'Timeouts Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'substitutions',
    title: 'Substitutions Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'jump-ball',
    title: 'Jump Ball Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },
  {
    slug: 'out-of-bounds',
    title: 'Out of Bounds Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules-and-basics',
  },

  // ── Court ──────────────────────────────────────────────────────────────────
  {
    slug: 'basketball-court',
    title: 'Basketball Court Explained',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'three-point-line',
    title: 'The Three-Point Line',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'the-paint',
    title: 'The Paint (The Key)',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'restricted-area',
    title: 'The Restricted Area',
    type: 'court_area',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'free-throw-line',
    title: 'The Free-Throw Line',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'baseline',
    title: 'The Baseline',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'sideline',
    title: 'The Sideline',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'half-court',
    title: 'Half Court',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'frontcourt',
    title: 'Frontcourt',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'backcourt',
    title: 'Backcourt',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'the-corner',
    title: 'The Corner',
    type: 'court_area',
    difficulty: 'intermediate',
    category: 'court-and-positions',
    alsoIn: ['shooting'],
  },
  {
    slug: 'the-wing',
    title: 'The Wing',
    type: 'court_area',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'the-elbow',
    title: 'The Elbow',
    type: 'court_area',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'low-post',
    title: 'The Low Post',
    type: 'court_area',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'high-post',
    title: 'The High Post',
    type: 'court_area',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },

  // ── Positions ──────────────────────────────────────────────────────────────
  {
    slug: 'basketball-positions',
    title: 'Basketball Positions Explained',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'point-guard',
    title: 'Point Guard',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'shooting-guard',
    title: 'Shooting Guard',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'small-forward',
    title: 'Small Forward',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'power-forward',
    title: 'Power Forward',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'center',
    title: 'Center',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'combo-guard',
    title: 'Combo Guard',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'wing-player',
    title: 'Wing (Player)',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'big-man',
    title: 'Big Man',
    type: 'position_role',
    difficulty: 'beginner',
    category: 'court-and-positions',
  },
  {
    slug: 'point-forward',
    title: 'Point Forward',
    type: 'position_role',
    difficulty: 'advanced',
    category: 'court-and-positions',
  },
  {
    slug: 'stretch-four',
    title: 'Stretch Four',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'stretch-five',
    title: 'Stretch Five',
    type: 'position_role',
    difficulty: 'advanced',
    category: 'court-and-positions',
  },
  {
    slug: 'three-and-d',
    title: '3-and-D Player',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },
  {
    slug: 'rim-protector',
    title: 'Rim Protector',
    type: 'position_role',
    difficulty: 'intermediate',
    category: 'court-and-positions',
    alsoIn: ['defense'],
  },
  {
    slug: 'positionless-basketball',
    title: 'Positionless Basketball',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'court-and-positions',
  },

  // ── Violations ─────────────────────────────────────────────────────────────
  {
    slug: 'traveling',
    title: 'Traveling',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'double-dribble',
    title: 'Double Dribble',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'carrying',
    title: 'Carrying',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'backcourt-violation',
    title: 'Backcourt Violation',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'shot-clock-violation',
    title: 'Shot Clock Violation',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'three-second-violation',
    title: 'Three-Second Violation',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'eight-second-violation',
    title: 'Eight-Second Violation',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'five-second-violation',
    title: 'Five-Second Violation',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'goaltending',
    title: 'Goaltending',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'basket-interference',
    title: 'Basket Interference',
    type: 'officiating',
    difficulty: 'advanced',
    category: 'fouls-and-violations',
  },
  {
    slug: 'kick-ball',
    title: 'Kicked Ball',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },

  // ── Fouls ──────────────────────────────────────────────────────────────────
  {
    slug: 'fouls',
    title: 'Fouls Explained',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'personal-foul',
    title: 'Personal Foul',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'shooting-foul',
    title: 'Shooting Foul',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'offensive-foul',
    title: 'Offensive Foul',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'charging',
    title: 'Charging',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'blocking-foul',
    title: 'Blocking Foul',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'charge-vs-block',
    title: 'Charge vs Block',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'technical-foul',
    title: 'Technical Foul',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },
  {
    slug: 'flagrant-foul',
    title: 'Flagrant Foul',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'team-fouls',
    title: 'Team Fouls',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'bonus',
    title: 'The Bonus',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'foul-trouble',
    title: 'Foul Trouble',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'fouls-and-violations',
  },
  {
    slug: 'fouling-out',
    title: 'Fouling Out',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'fouls-and-violations',
  },

  // ── Offense ────────────────────────────────────────────────────────────────
  { slug: 'screen', title: 'Screen', type: 'play', difficulty: 'beginner', category: 'offense' },
  {
    slug: 'pick-and-roll',
    title: 'Pick and Roll',
    type: 'play',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'spacing',
    title: 'Spacing',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'fast-break',
    title: 'Fast Break',
    type: 'play',
    difficulty: 'beginner',
    category: 'offense',
  },
  {
    slug: 'transition-offense',
    title: 'Transition Offense',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'isolation',
    title: 'Isolation',
    type: 'play',
    difficulty: 'beginner',
    category: 'offense',
  },
  { slug: 'post-up', title: 'Post-Up', type: 'play', difficulty: 'beginner', category: 'offense' },
  {
    slug: 'cutting',
    title: 'Cutting',
    type: 'play',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'ball-movement',
    title: 'Ball Movement',
    type: 'tactical_concept',
    difficulty: 'beginner',
    category: 'offense',
  },
  {
    slug: 'pick-and-pop',
    title: 'Pick and Pop',
    type: 'play',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'drive-and-kick',
    title: 'Drive and Kick',
    type: 'play',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'give-and-go',
    title: 'Give and Go',
    type: 'play',
    difficulty: 'beginner',
    category: 'offense',
  },
  {
    slug: 'dribble-hand-off',
    title: 'Dribble Hand-Off',
    type: 'play',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'backdoor-cut',
    title: 'Backdoor Cut',
    type: 'play',
    difficulty: 'intermediate',
    category: 'offense',
  },
  {
    slug: 'motion-offense',
    title: 'Motion Offense',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'five-out-offense',
    title: 'Five-Out Offense',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'four-out-one-in',
    title: 'Four-Out One-In',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'spain-pick-and-roll',
    title: 'Spain Pick and Roll',
    type: 'play',
    difficulty: 'advanced',
    category: 'offense',
  },
  { slug: 'horns', title: 'Horns', type: 'play', difficulty: 'advanced', category: 'offense' },
  {
    slug: 'double-drag',
    title: 'Double Drag',
    type: 'play',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'ghost-screen',
    title: 'Ghost Screen',
    type: 'play',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'slip-screen',
    title: 'Slip Screen',
    type: 'play',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'flare-screen',
    title: 'Flare Screen',
    type: 'play',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'pin-down',
    title: 'Pin-Down',
    type: 'play',
    difficulty: 'advanced',
    category: 'offense',
  },
  {
    slug: 'elevator-screen',
    title: 'Elevator Screen',
    type: 'play',
    difficulty: 'advanced',
    category: 'offense',
  },

  // ── Defense ────────────────────────────────────────────────────────────────
  {
    slug: 'man-to-man-defense',
    title: 'Man-to-Man Defense',
    type: 'tactical_concept',
    difficulty: 'beginner',
    category: 'defense',
  },
  {
    slug: 'zone-defense',
    title: 'Zone Defense',
    type: 'tactical_concept',
    difficulty: 'beginner',
    category: 'defense',
  },
  {
    slug: 'man-vs-zone',
    title: 'Man vs Zone',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'defense',
  },
  {
    slug: 'help-defense',
    title: 'Help Defense',
    type: 'tactical_concept',
    difficulty: 'beginner',
    category: 'defense',
  },
  {
    slug: 'switching',
    title: 'Switching',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'defense',
  },
  {
    slug: 'double-team',
    title: 'Double Team',
    type: 'tactical_concept',
    difficulty: 'beginner',
    category: 'defense',
  },
  {
    slug: 'rim-protection',
    title: 'Rim Protection',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'defense',
  },
  {
    slug: 'two-three-zone',
    title: '2-3 Zone',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'defense',
  },
  {
    slug: 'three-two-zone',
    title: '3-2 Zone',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'one-three-one-zone',
    title: '1-3-1 Zone',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'drop-coverage',
    title: 'Drop Coverage',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'hedge',
    title: 'Hedge',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'blitz',
    title: 'Blitz',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'drop-vs-switch',
    title: 'Drop Coverage vs Switching',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'closeout',
    title: 'Closeout',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'defense',
  },
  {
    slug: 'defensive-rotation',
    title: 'Defensive Rotation',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'weak-side-help',
    title: 'Weak-Side Help',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },
  {
    slug: 'full-court-press',
    title: 'Full-Court Press',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'defense',
  },
  {
    slug: 'transition-defense',
    title: 'Transition Defense',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'defense',
  },
  {
    slug: 'ice-coverage',
    title: 'ICE Coverage',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'defense',
  },

  // ── Rebounding ─────────────────────────────────────────────────────────────
  {
    slug: 'rebounding',
    title: 'Rebounding Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'rebounding',
  },
  {
    slug: 'offensive-rebound',
    title: 'Offensive Rebound',
    type: 'definition',
    difficulty: 'beginner',
    category: 'rebounding',
  },
  {
    slug: 'defensive-rebound',
    title: 'Defensive Rebound',
    type: 'definition',
    difficulty: 'beginner',
    category: 'rebounding',
  },
  {
    slug: 'boxing-out',
    title: 'Boxing Out',
    type: 'tactical_concept',
    difficulty: 'beginner',
    category: 'rebounding',
  },
  {
    slug: 'second-chance-points',
    title: 'Second-Chance Points',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'rebounding',
  },
  {
    slug: 'putback',
    title: 'Putback',
    type: 'definition',
    difficulty: 'beginner',
    category: 'rebounding',
  },
  {
    slug: 'team-rebounding',
    title: 'Team Rebounding',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'rebounding',
  },

  // ── Shooting ───────────────────────────────────────────────────────────────
  {
    slug: 'field-goal',
    title: 'Field Goal',
    type: 'definition',
    difficulty: 'beginner',
    category: 'shooting',
  },
  {
    slug: 'free-throw',
    title: 'Free Throw',
    type: 'rule',
    difficulty: 'beginner',
    category: 'shooting',
  },
  {
    slug: 'three-pointer',
    title: 'Three-Pointer',
    type: 'definition',
    difficulty: 'beginner',
    category: 'shooting',
  },
  {
    slug: 'layup',
    title: 'Layup',
    type: 'definition',
    difficulty: 'beginner',
    category: 'shooting',
  },
  { slug: 'dunk', title: 'Dunk', type: 'definition', difficulty: 'beginner', category: 'shooting' },
  {
    slug: 'mid-range-shot',
    title: 'Mid-Range Shot',
    type: 'definition',
    difficulty: 'beginner',
    category: 'shooting',
  },
  {
    slug: 'floater',
    title: 'Floater',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'shooting',
  },
  {
    slug: 'hook-shot',
    title: 'Hook Shot',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'shooting',
  },
  {
    slug: 'bank-shot',
    title: 'Bank Shot',
    type: 'definition',
    difficulty: 'beginner',
    category: 'shooting',
  },
  {
    slug: 'corner-three',
    title: 'Corner Three',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'shooting',
  },
  {
    slug: 'catch-and-shoot',
    title: 'Catch-and-Shoot',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'shooting',
  },
  {
    slug: 'pull-up-shot',
    title: 'Pull-Up Shot',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'shooting',
  },
  {
    slug: 'step-back',
    title: 'Step-Back',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'shooting',
  },
  {
    slug: 'buzzer-beater',
    title: 'Buzzer Beater',
    type: 'definition',
    difficulty: 'beginner',
    category: 'shooting',
  },

  // ── Statistics: basic ──────────────────────────────────────────────────────
  {
    slug: 'box-score',
    title: 'How to Read a Basketball Box Score',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'points',
    title: 'Points',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'rebounds',
    title: 'Rebounds',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'assists',
    title: 'Assists',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'steals',
    title: 'Steals',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'blocks',
    title: 'Blocks',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'turnovers',
    title: 'Turnovers',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'field-goal-percentage',
    title: 'Field Goal Percentage (FG%)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'three-point-percentage',
    title: 'Three-Point Percentage (3P%)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'free-throw-percentage',
    title: 'Free Throw Percentage (FT%)',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'plus-minus',
    title: 'Plus-Minus',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'double-double',
    title: 'Double-Double',
    type: 'definition',
    difficulty: 'beginner',
    category: 'statistics',
    alsoIn: ['glossary'],
  },
  {
    slug: 'triple-double',
    title: 'Triple-Double',
    type: 'definition',
    difficulty: 'beginner',
    category: 'statistics',
    alsoIn: ['glossary'],
  },

  // ── Statistics: advanced ───────────────────────────────────────────────────
  {
    slug: 'true-shooting-percentage',
    title: 'True Shooting Percentage',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'effective-field-goal-percentage',
    title: 'Effective Field Goal Percentage',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'usage-rate',
    title: 'Usage Rate',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'offensive-rating',
    title: 'Offensive Rating',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'defensive-rating',
    title: 'Defensive Rating',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'net-rating',
    title: 'Net Rating',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'pace',
    title: 'Pace',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'possessions',
    title: 'Possessions',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'points-per-possession',
    title: 'Points Per Possession',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'rebound-percentage',
    title: 'Rebound Percentage',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'assist-percentage',
    title: 'Assist Percentage',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'turnover-percentage',
    title: 'Turnover Percentage',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'player-efficiency-rating',
    title: 'Player Efficiency Rating (PER)',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'win-shares',
    title: 'Win Shares',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'box-plus-minus',
    title: 'Box Plus/Minus',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'vorp',
    title: 'VORP',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'on-off-rating',
    title: 'On/Off Rating',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'per-36-minutes',
    title: 'Per 36 Minutes',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },
  {
    slug: 'per-100-possessions',
    title: 'Per 100 Possessions',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'statistics',
  },

  // ── NBA ────────────────────────────────────────────────────────────────────
  {
    slug: 'how-the-nba-works',
    title: 'How the NBA Works',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'nba-regular-season',
    title: 'NBA Regular Season',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'nba-conferences',
    title: 'Eastern & Western Conferences',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'nba-standings',
    title: 'NBA Standings',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'nba-playoffs',
    title: 'NBA Playoffs',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'nba-play-in-tournament',
    title: 'NBA Play-In Tournament',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'nba-finals',
    title: 'NBA Finals',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'seeding',
    title: 'Seeding',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'home-court-advantage',
    title: 'Home-Court Advantage',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'nba-cup',
    title: 'NBA Cup',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'all-star-weekend',
    title: 'All-Star Weekend',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'nba-draft',
    title: 'NBA Draft Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'draft-lottery',
    title: 'Draft Lottery',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'draft-pick',
    title: 'Draft Pick',
    type: 'definition',
    difficulty: 'beginner',
    category: 'nba-explained',
  },
  {
    slug: 'lottery-pick',
    title: 'Lottery Pick',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'protected-pick',
    title: 'Protected Pick',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'pick-swap',
    title: 'Pick Swap',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'undrafted-player',
    title: 'Undrafted Player',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'nba-trades',
    title: 'Trades Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'trade-deadline',
    title: 'Trade Deadline',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'free-agency',
    title: 'Free Agency',
    type: 'format',
    difficulty: 'intermediate',
    category: 'nba-explained',
  },
  {
    slug: 'restricted-free-agent',
    title: 'Restricted Free Agent',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'unrestricted-free-agent',
    title: 'Unrestricted Free Agent',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'sign-and-trade',
    title: 'Sign-and-Trade',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'waivers',
    title: 'Waivers',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'buyout',
    title: 'Buyout',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'player-option',
    title: 'Player Option',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'team-option',
    title: 'Team Option',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'two-way-contract',
    title: 'Two-Way Contract',
    type: 'definition',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'salary-cap',
    title: 'Salary Cap',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'luxury-tax',
    title: 'Luxury Tax',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'salary-aprons',
    title: 'Salary Aprons',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'bird-rights',
    title: 'Bird Rights',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'max-contract',
    title: 'Max Contract',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'supermax',
    title: 'Supermax',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'mid-level-exception',
    title: 'Mid-Level Exception',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },
  {
    slug: 'trade-exception',
    title: 'Trade Exception',
    type: 'format',
    difficulty: 'advanced',
    category: 'nba-explained',
  },

  // ── International, Europe, college, women's, 3x3 ───────────────────────────
  {
    slug: 'fiba-basketball',
    title: 'FIBA Basketball Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'nba-vs-fiba-rules',
    title: 'NBA Rules vs FIBA Rules',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'fiba-world-cup',
    title: 'FIBA Basketball World Cup',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'olympic-basketball',
    title: 'Olympic Basketball',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'eurobasket',
    title: 'EuroBasket',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'fiba-windows',
    title: 'FIBA Windows',
    type: 'format',
    difficulty: 'advanced',
    category: 'international-basketball',
  },
  {
    slug: 'how-european-basketball-works',
    title: 'How European Basketball Works',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'euroleague',
    title: 'EuroLeague',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'eurocup',
    title: 'EuroCup',
    type: 'format',
    difficulty: 'advanced',
    category: 'international-basketball',
  },
  {
    slug: 'promotion-and-relegation-basketball',
    title: 'Promotion and Relegation in Basketball',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'euroleague-vs-nba',
    title: 'EuroLeague vs NBA',
    type: 'format',
    difficulty: 'advanced',
    category: 'international-basketball',
  },
  {
    slug: 'ncaa-basketball',
    title: 'NCAA Basketball',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'march-madness',
    title: 'March Madness',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'selection-sunday',
    title: 'Selection Sunday',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'final-four',
    title: 'The Final Four',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'cinderella-team',
    title: 'Cinderella Team',
    type: 'definition',
    difficulty: 'beginner',
    category: 'international-basketball',
    alsoIn: ['glossary'],
  },
  {
    slug: 'wnba',
    title: 'WNBA Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'wnba-season',
    title: 'WNBA Season',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'wnba-playoffs',
    title: 'WNBA Playoffs',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'wnba-draft',
    title: 'WNBA Draft',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'wnba-vs-nba',
    title: 'WNBA vs NBA',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'womens-ncaa-basketball',
    title: 'Women’s NCAA Basketball',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'three-by-three-basketball',
    title: '3x3 Basketball Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'international-basketball',
  },
  {
    slug: 'three-by-three-rules',
    title: '3x3 Rules',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },
  {
    slug: 'three-by-three-vs-five-on-five',
    title: '3x3 vs 5-on-5',
    type: 'format',
    difficulty: 'intermediate',
    category: 'international-basketball',
  },

  // ── Glossary ───────────────────────────────────────────────────────────────
  {
    slug: 'airball',
    title: 'Airball',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'alley-oop',
    title: 'Alley-Oop',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'and-one',
    title: 'And-One',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'ankle-breaker',
    title: 'Ankle Breaker',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'brick',
    title: 'Brick',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'clutch',
    title: 'Clutch',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  { slug: 'dime', title: 'Dime', type: 'definition', difficulty: 'beginner', category: 'glossary' },
  {
    slug: 'heat-check',
    title: 'Heat Check',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'mismatch',
    title: 'Mismatch',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'glossary',
  },
  {
    slug: 'poster',
    title: 'Poster',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'sixth-man',
    title: 'Sixth Man',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'splash',
    title: 'Splash',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
];
