import type { ExplainerCategorySeed, ExplainerSeed } from './explainer-types';

/**
 * The Formula 1 taxonomy: the categories, and every concept the library intends
 * to cover.
 *
 * Everything in this file is a draft placeholder. Nothing here reaches the site.
 * The written explainers live in the `formula1-*.ts` content files and override
 * these by slug, which is why the slugs here have to be right first time: a typo
 * produces a second concept rather than a written version of the first.
 *
 * ## On categories
 *
 * The brief names thirty-one groupings. Thirty-one headings on a landing page is
 * a directory rather than a structure, so the categories are ordered and the
 * landing page leads with the first ten; the rest are real categories with real
 * URLs, reachable from a breadcrumb and from search. Tennis and basketball
 * reached the same arrangement for the same reason.
 *
 * Several of the brief's groupings collapse here, because they name the same
 * concepts twice rather than naming two things:
 *
 * - **Race Weekend** and **Qualifying** overlap on the flying lap, the out lap
 *   and track evolution. Qualifying keeps them; the weekend category links to
 *   them through `alsoIn`.
 * - **Pit Stops** and **Race Strategy** both claim the pit window and the
 *   undercut. The mechanical concepts (pit lane, crew roles, double stacking)
 *   sit in Pit Stops; the decisions (undercut, overcut, offset) sit in Strategy.
 *   `pit-window` is one row in both.
 * - **Overtaking** and **Track Limits & Racing Rules** both claim leaving the
 *   track, racing room and moving under braking. Those are rules, so they live
 *   in Rules & Track Limits and appear in Overtaking through `alsoIn`.
 * - **F1 Car Basics** and **Aerodynamics** both claim the diffuser, the wings
 *   and the floor. The parts are components; the physics is aerodynamics. The
 *   diffuser is one row, typed `car_component`, in both.
 * - **Braking & Cornering** and **Driver Skills** both claim trail braking and
 *   the racing line. They are techniques, filed under Driving, with Braking &
 *   Cornering folded in rather than split from it.
 * - **Lap Times** and **Telemetry & Data** both claim sector times, delta time
 *   and fuel correction. One category, Telemetry & Lap Time.
 * - **Cost Cap & Business**, **Driver Market** and **Feeder Series** are three
 *   small categories about the sport's economics and its pathway. Two here:
 *   Business, and Getting to F1.
 * - **Advanced Performance Analysis** stays its own category. It is the one
 *   place in the library where the content is derived rather than reported, and
 *   keeping it together is what lets every entry in it carry the same warning.
 *
 * That is twenty-two categories covering all thirty-one of the brief's, with no
 * concept dropped and none duplicated.
 *
 * ## On versioning
 *
 * The brief asks three times for content to be versioned by season or
 * regulation era, and this is the sport where that matters most: there is one
 * Formula 1, but a 2013 car, a 2021 car and a 2026 car are three different
 * machines run under three different rulebooks. Every entry written against a
 * regulation carries `ruleSensitive: true` and a `sourceRevision`, and the
 * helper's `era` field puts the same statement on the page where the reader
 * can see it. The set to re-audit after a rule change is then a query rather
 * than a reading of four hundred articles.
 */

export const FORMULA1_EXPLAINER_CATEGORIES: ExplainerCategorySeed[] = [
  {
    slug: 'start-here',
    name: 'Start Here',
    description: 'What Formula 1 is, how a season fits together, and how to follow a race.',
    order: 10,
  },
  {
    slug: 'race-weekend',
    name: 'The Race Weekend',
    shortName: 'Weekend',
    description: 'Practice, qualifying and the Grand Prix, in the order they happen.',
    order: 20,
  },
  {
    slug: 'qualifying',
    name: 'Qualifying',
    description: 'Q1, Q2 and Q3, the flying lap, and how the grid is decided.',
    order: 30,
  },
  {
    slug: 'the-race',
    name: 'The Race',
    description: 'The start, the distance, the classification, and every way a race can end.',
    order: 40,
  },
  {
    slug: 'strategy',
    name: 'Race Strategy',
    shortName: 'Strategy',
    description: 'Undercuts, overcuts, pit windows and the arithmetic behind every stop.',
    order: 50,
  },
  {
    slug: 'tyres',
    name: 'Tyres',
    description: 'Compounds, degradation, temperature, graining, and why rubber decides races.',
    order: 60,
  },
  {
    slug: 'pit-stops',
    name: 'Pit Stops',
    shortName: 'Pit Stops',
    description: 'The pit lane, the crew, the two-second stop, and what it really costs.',
    order: 70,
  },
  {
    slug: 'overtaking',
    name: 'Overtaking',
    description: 'DRS, slipstream, dirty air, and why passing is harder than it looks.',
    order: 80,
  },
  {
    slug: 'flags-and-safety-car',
    name: 'Flags & Safety Car',
    shortName: 'Flags',
    description: 'Every flag, the safety car, the VSC, and what each does to a race.',
    order: 90,
  },
  {
    slug: 'championship',
    name: 'Championship & Points',
    shortName: 'Points',
    description: 'How points are scored, how titles are won, and how the maths works.',
    order: 100,
  },
  /*
   * Below the fold.
   *
   * Real categories with real URLs, reachable from a concept's breadcrumb and
   * from search, but not among the ten the landing page leads with. This is how
   * a twenty-two-category taxonomy stays navigable.
   */
  {
    slug: 'the-car',
    name: 'The Car',
    description: 'Every major part of a Formula 1 car, and what it is there to do.',
    order: 110,
  },
  {
    slug: 'aerodynamics',
    name: 'Aerodynamics',
    shortName: 'Aero',
    description: 'Downforce, drag, ground effect, and the invisible thing that makes it fast.',
    order: 120,
  },
  {
    slug: 'power-unit',
    name: 'Power Unit',
    description: 'The hybrid engine, energy recovery, deployment, and component penalties.',
    order: 130,
  },
  {
    slug: 'driving',
    name: 'Driving & Technique',
    shortName: 'Driving',
    description: 'Braking, cornering, car control, and what separates an elite driver.',
    order: 140,
  },
  {
    slug: 'car-setup',
    name: 'Car Setup',
    shortName: 'Setup',
    description: 'Wings, ride height, camber and bias: the compromises made before a lap.',
    order: 150,
  },
  {
    slug: 'telemetry',
    name: 'Telemetry & Lap Time',
    shortName: 'Telemetry',
    description: 'Traces, sectors, deltas, and how engineers read a lap.',
    order: 160,
  },
  {
    slug: 'circuits',
    name: 'Circuits',
    description: 'Street and permanent tracks, corner types, and why circuits suit cars.',
    order: 170,
  },
  {
    slug: 'weather',
    name: 'Weather & Conditions',
    shortName: 'Weather',
    description: 'Rain, temperature and wind, and how they rewrite a race.',
    order: 180,
  },
  {
    slug: 'rules-and-penalties',
    name: 'Rules & Penalties',
    shortName: 'Penalties',
    description: 'Track limits, the stewards, and every penalty they can hand out.',
    order: 190,
  },
  {
    slug: 'teams',
    name: 'Teams & People',
    shortName: 'Teams',
    description: 'Who does what on a pit wall, and how a team makes a decision at speed.',
    order: 200,
  },
  {
    slug: 'business',
    name: 'Regulations & Business',
    shortName: 'Business',
    description: 'The rulebook, the cost cap, prize money, and how teams are funded.',
    order: 210,
  },
  {
    slug: 'pathway',
    name: 'Getting to F1',
    shortName: 'Pathway',
    description: 'Karting, F2, super licences, academies and the driver market.',
    order: 220,
  },
  {
    slug: 'analysis',
    name: 'Performance Analysis',
    shortName: 'Analysis',
    description: 'Derived measures of car and driver performance, and what each assumes.',
    order: 230,
  },
  {
    slug: 'glossary',
    name: 'Glossary',
    description: 'Every term in the sport, defined in a sentence.',
    order: 240,
  },
];

/**
 * Builds a taxonomy placeholder.
 *
 * A row with no sections: the concept is named and categorised, but unwritten,
 * so it stays a draft and never reaches the site. This is what makes duplicate
 * control work before the writing happens, since a proposed explainer can be
 * checked against every concept the library intends to cover rather than only
 * against the ones already finished.
 */
function topic(
  slug: string,
  title: string,
  type: ExplainerSeed['type'],
  difficulty: ExplainerSeed['difficulty'],
  category: string,
  order: number,
  alsoIn?: string[],
): ExplainerSeed {
  return { slug, title, type, difficulty, category, order, alsoIn };
}

export const FORMULA1_EXPLAINER_TOPICS: ExplainerSeed[] = [
  /* ── Start here ─────────────────────────────────────────────────────────── */
  topic(
    'formula-1-in-five-minutes',
    'Formula 1 in 5 Minutes',
    'standard',
    'beginner',
    'start-here',
    10,
  ),
  topic('how-formula-1-works', 'How Formula 1 Works', 'standard', 'beginner', 'start-here', 20),
  topic(
    'what-is-a-grand-prix',
    'What Is a Grand Prix?',
    'definition',
    'beginner',
    'start-here',
    30,
  ),
  topic('how-an-f1-season-works', 'How an F1 Season Works', 'format', 'beginner', 'start-here', 40),
  topic(
    'how-an-f1-weekend-works',
    'How an F1 Weekend Works',
    'format',
    'beginner',
    'start-here',
    50,
    ['race-weekend'],
  ),
  topic(
    'drivers-vs-constructors',
    'Drivers vs Constructors',
    'standard',
    'beginner',
    'start-here',
    60,
    ['championship'],
  ),
  topic(
    'how-the-championship-works',
    'How the F1 Championship Works',
    'format',
    'beginner',
    'start-here',
    70,
    ['championship'],
  ),
  topic('how-f1-teams-work', 'How F1 Teams Work', 'standard', 'beginner', 'start-here', 80, [
    'teams',
  ]),
  topic(
    'what-makes-an-f1-car-different',
    'What Makes an F1 Car Different?',
    'standard',
    'beginner',
    'start-here',
    90,
    ['the-car'],
  ),
  topic(
    'f1-vs-other-motorsport',
    'Formula 1 vs Other Motorsport',
    'standard',
    'beginner',
    'start-here',
    100,
  ),

  /* ── Race weekend ───────────────────────────────────────────────────────── */
  topic(
    'race-weekend-explained',
    'The F1 Race Weekend Explained',
    'format',
    'beginner',
    'race-weekend',
    10,
  ),
  topic('free-practice', 'Free Practice Explained', 'format', 'beginner', 'race-weekend', 20),
  topic('fp1-fp2-fp3', 'FP1, FP2 and FP3', 'format', 'beginner', 'race-weekend', 30),
  topic(
    'why-practice-matters',
    'Why Practice Sessions Matter',
    'standard',
    'intermediate',
    'race-weekend',
    40,
  ),
  topic(
    'sprint-weekend',
    'Sprint Weekend Explained',
    'format',
    'intermediate',
    'race-weekend',
    50,
    ['championship'],
  ),
  topic('formation-lap', 'Formation Lap Explained', 'procedure', 'beginner', 'race-weekend', 60, [
    'the-race',
    'glossary',
  ]),
  topic('starting-grid', 'Starting Grid Explained', 'definition', 'beginner', 'race-weekend', 70, [
    'qualifying',
  ]),
  topic('grid-formation', 'Grid Formation Explained', 'procedure', 'beginner', 'race-weekend', 80),
  topic(
    'why-drivers-start-in-different-positions',
    'Why Drivers Start From Different Positions',
    'standard',
    'beginner',
    'race-weekend',
    90,
    ['qualifying'],
  ),
  topic('parc-ferme', 'Parc Fermé Explained', 'rule', 'intermediate', 'race-weekend', 100, [
    'car-setup',
    'rules-and-penalties',
  ]),
  topic(
    'what-happens-after-the-race',
    'What Happens After the Race?',
    'procedure',
    'beginner',
    'race-weekend',
    110,
  ),

  /* ── Qualifying ─────────────────────────────────────────────────────────── */
  topic('qualifying-explained', 'F1 Qualifying Explained', 'format', 'beginner', 'qualifying', 10),
  topic('q1', 'Q1 Explained', 'format', 'beginner', 'qualifying', 20),
  topic('q2', 'Q2 Explained', 'format', 'beginner', 'qualifying', 30),
  topic('q3', 'Q3 Explained', 'format', 'beginner', 'qualifying', 40),
  topic('pole-position', 'Pole Position Explained', 'definition', 'beginner', 'qualifying', 50),
  topic('flying-lap', 'What Is a Flying Lap?', 'definition', 'beginner', 'qualifying', 60, [
    'telemetry',
  ]),
  topic('out-lap', 'Out Lap Explained', 'definition', 'intermediate', 'qualifying', 70, ['tyres']),
  topic('in-lap', 'In Lap Explained', 'definition', 'intermediate', 'qualifying', 80),
  topic(
    'track-position-in-qualifying',
    'Why Drivers Need Track Position in Qualifying',
    'strategy_concept',
    'intermediate',
    'qualifying',
    90,
  ),
  topic(
    'qualifying-traffic',
    'Qualifying Traffic Explained',
    'standard',
    'intermediate',
    'qualifying',
    100,
  ),
  topic(
    'track-evolution',
    'Track Evolution Explained',
    'tactical_concept',
    'intermediate',
    'qualifying',
    110,
    ['circuits', 'telemetry'],
  ),
  topic(
    'why-lap-times-improve-in-qualifying',
    'Why Lap Times Improve During Qualifying',
    'standard',
    'intermediate',
    'qualifying',
    120,
  ),
  topic(
    'deleted-lap-times',
    'Deleted Lap Times Explained',
    'rule',
    'intermediate',
    'qualifying',
    130,
    ['rules-and-penalties'],
  ),
  topic(
    'grid-penalties',
    'Grid Penalties After Qualifying',
    'penalty',
    'intermediate',
    'qualifying',
    140,
    ['rules-and-penalties', 'power-unit'],
  ),
  topic(
    'pole-not-always-first',
    "Why Pole Position Doesn't Always Mean Starting First",
    'standard',
    'intermediate',
    'qualifying',
    150,
  ),

  /* ── The race ───────────────────────────────────────────────────────────── */
  topic('how-a-race-works', 'How an F1 Race Works', 'format', 'beginner', 'the-race', 10),
  topic('race-distance', 'Race Distance Explained', 'rule', 'beginner', 'the-race', 20),
  topic('the-race-start', 'The Race Start Explained', 'procedure', 'beginner', 'the-race', 30),
  topic('lights-out-procedure', 'Lights-Out Procedure', 'procedure', 'beginner', 'the-race', 40),
  topic('standing-start', 'What Is a Standing Start?', 'definition', 'beginner', 'the-race', 50),
  topic('rolling-start', 'What Is a Rolling Start?', 'definition', 'beginner', 'the-race', 60),
  topic(
    'race-classification',
    'Race Classification Explained',
    'rule',
    'intermediate',
    'the-race',
    70,
  ),
  topic('dnf', 'What Is a DNF?', 'definition', 'beginner', 'the-race', 80, ['glossary']),
  topic('dns', 'What Is a DNS?', 'definition', 'beginner', 'the-race', 90, ['glossary']),
  topic('dsq', 'What Is a DSQ?', 'definition', 'beginner', 'the-race', 100, [
    'rules-and-penalties',
    'glossary',
  ]),
  topic('lapped', 'What Does Lapped Mean?', 'definition', 'beginner', 'the-race', 110, [
    'glossary',
  ]),
  topic('unlapping', 'How Drivers Unlap Themselves', 'procedure', 'intermediate', 'the-race', 120, [
    'flags-and-safety-car',
  ]),
  topic('backmarkers', 'Backmarkers Explained', 'definition', 'beginner', 'the-race', 130, [
    'glossary',
  ]),
  topic('race-restart', 'What Is a Race Restart?', 'procedure', 'intermediate', 'the-race', 140, [
    'flags-and-safety-car',
  ]),
  topic(
    'suspended-race',
    'What Happens When a Race Is Suspended?',
    'procedure',
    'intermediate',
    'the-race',
    150,
    ['flags-and-safety-car'],
  ),

  /* ── Championship & points ──────────────────────────────────────────────── */
  topic('points-system', 'F1 Points System Explained', 'rule', 'beginner', 'championship', 10),
  topic(
    'how-drivers-score-points',
    'How Drivers Score Points',
    'rule',
    'beginner',
    'championship',
    20,
  ),
  topic(
    'constructors-points',
    "Constructors' Points Explained",
    'rule',
    'beginner',
    'championship',
    30,
  ),
  topic(
    'drivers-championship',
    "Drivers' Championship Explained",
    'format',
    'beginner',
    'championship',
    40,
  ),
  topic(
    'constructors-championship',
    "Constructors' Championship Explained",
    'format',
    'beginner',
    'championship',
    50,
  ),
  topic('how-ties-are-broken', 'How Ties Are Broken', 'rule', 'intermediate', 'championship', 60),
  topic(
    'why-every-point-matters',
    'Why Every Point Matters',
    'standard',
    'intermediate',
    'championship',
    70,
  ),
  topic('sprint-points', 'Sprint Points Explained', 'rule', 'intermediate', 'championship', 80),
  topic(
    'shortened-race-points',
    'What Happens if a Race Is Shortened?',
    'rule',
    'intermediate',
    'championship',
    90,
  ),
  topic(
    'championship-mathematics',
    'How Championship Mathematics Works',
    'standard',
    'advanced',
    'championship',
    100,
  ),
  topic(
    'clinching-the-championship',
    'What Does "Clinching the Championship" Mean?',
    'definition',
    'intermediate',
    'championship',
    110,
  ),

  /* ── Tyres ──────────────────────────────────────────────────────────────── */
  topic('tyres-explained', 'F1 Tyres Explained', 'standard', 'beginner', 'tyres', 10),
  topic('soft-tyres', 'Soft Tyres Explained', 'definition', 'beginner', 'tyres', 20),
  topic('medium-tyres', 'Medium Tyres Explained', 'definition', 'beginner', 'tyres', 30),
  topic('hard-tyres', 'Hard Tyres Explained', 'definition', 'beginner', 'tyres', 40),
  topic(
    'intermediate-tyres',
    'Intermediate Tyres Explained',
    'definition',
    'beginner',
    'tyres',
    50,
    ['weather'],
  ),
  topic('wet-tyres', 'Wet Tyres Explained', 'definition', 'beginner', 'tyres', 60, ['weather']),
  topic(
    'why-softer-tyres-are-faster',
    'Why Softer Tyres Are Faster',
    'tactical_concept',
    'intermediate',
    'tyres',
    70,
  ),
  topic('why-tyres-degrade', 'Why Tyres Degrade', 'tactical_concept', 'intermediate', 'tyres', 80),
  topic(
    'tyre-degradation',
    'Tyre Degradation Explained',
    'tactical_concept',
    'intermediate',
    'tyres',
    90,
    ['strategy'],
  ),
  topic(
    'wear-vs-degradation',
    'Tyre Wear vs Tyre Degradation',
    'tactical_concept',
    'advanced',
    'tyres',
    100,
  ),
  topic(
    'tyre-temperature',
    'Tyre Temperature Explained',
    'tactical_concept',
    'intermediate',
    'tyres',
    110,
  ),
  topic('tyre-warm-up', 'Tyre Warm-Up Explained', 'tactical_concept', 'intermediate', 'tyres', 120),
  topic('graining', 'Tyre Graining Explained', 'tactical_concept', 'advanced', 'tyres', 130),
  topic('blistering', 'Tyre Blistering Explained', 'tactical_concept', 'advanced', 'tyres', 140),
  topic('flat-spots', 'Flat Spots Explained', 'tactical_concept', 'intermediate', 'tyres', 150, [
    'driving',
  ]),
  topic(
    'tyre-management',
    'Tyre Management Explained',
    'tactical_concept',
    'intermediate',
    'tyres',
    160,
    ['driving'],
  ),
  topic('tyre-compounds', 'Tyre Compounds Explained', 'standard', 'beginner', 'tyres', 170),
  topic(
    'why-different-compounds',
    'Why Drivers Use Different Compounds',
    'strategy_concept',
    'intermediate',
    'tyres',
    180,
    ['strategy'],
  ),
  topic(
    'mandatory-tyre-rules',
    'Mandatory Tyre Rules Explained',
    'rule',
    'intermediate',
    'tyres',
    190,
    ['rules-and-penalties'],
  ),
  topic(
    'why-drivers-avoid-pitting',
    'Why Drivers Sometimes Avoid Pitting',
    'strategy_concept',
    'intermediate',
    'tyres',
    200,
    ['strategy'],
  ),

  /* ── Pit stops ──────────────────────────────────────────────────────────── */
  topic('pit-stops-explained', 'F1 Pit Stops Explained', 'procedure', 'beginner', 'pit-stops', 10),
  topic('why-cars-pit', 'Why F1 Cars Pit', 'standard', 'beginner', 'pit-stops', 20),
  topic(
    'how-a-tyre-change-works',
    'How a Tyre Change Works',
    'procedure',
    'beginner',
    'pit-stops',
    30,
  ),
  topic(
    'why-pit-stops-are-fast',
    'Why Pit Stops Are So Fast',
    'standard',
    'beginner',
    'pit-stops',
    40,
  ),
  topic(
    'pit-crew-roles',
    'Pit Crew Roles Explained',
    'position_role',
    'intermediate',
    'pit-stops',
    50,
    ['teams'],
  ),
  topic('pit-lane', 'Pit Lane Explained', 'definition', 'beginner', 'pit-stops', 60),
  topic('pit-entry', 'Pit Entry Explained', 'definition', 'intermediate', 'pit-stops', 70),
  topic('pit-exit', 'Pit Exit Explained', 'definition', 'intermediate', 'pit-stops', 80),
  topic('pit-lane-speed-limit', 'Pit Lane Speed Limit', 'rule', 'beginner', 'pit-stops', 90, [
    'rules-and-penalties',
  ]),
  topic('unsafe-release', 'Unsafe Release Explained', 'penalty', 'intermediate', 'pit-stops', 100, [
    'rules-and-penalties',
  ]),
  topic('pit-stop-errors', 'Pit Stop Errors', 'standard', 'intermediate', 'pit-stops', 110),
  topic(
    'double-stacking',
    'Double Stacking Explained',
    'strategy_concept',
    'advanced',
    'pit-stops',
    120,
    ['strategy'],
  ),
  topic(
    'why-teammates-pit-together',
    'Why Teammates Sometimes Pit Together',
    'strategy_concept',
    'advanced',
    'pit-stops',
    130,
  ),
  topic('pit-loss', 'Pit Stop Time vs Total Pit Loss', 'statistic', 'advanced', 'pit-stops', 140, [
    'strategy',
    'analysis',
  ]),
  topic(
    'pit-window',
    'Pit Window Explained',
    'strategy_concept',
    'intermediate',
    'pit-stops',
    150,
    ['strategy'],
  ),

  /* ── Strategy ───────────────────────────────────────────────────────────── */
  topic(
    'strategy-explained',
    'F1 Strategy Explained',
    'strategy_concept',
    'beginner',
    'strategy',
    10,
  ),
  topic(
    'one-stop-strategy',
    'What Is a One-Stop Strategy?',
    'strategy_concept',
    'beginner',
    'strategy',
    20,
  ),
  topic(
    'two-stop-strategy',
    'Two-Stop Strategy Explained',
    'strategy_concept',
    'intermediate',
    'strategy',
    30,
  ),
  topic('undercut', 'Undercut Explained', 'strategy_concept', 'intermediate', 'strategy', 40),
  topic('overcut', 'Overcut Explained', 'strategy_concept', 'intermediate', 'strategy', 50),
  topic(
    'track-position-vs-fresh-tyres',
    'Track Position vs Fresh Tyres',
    'strategy_concept',
    'intermediate',
    'strategy',
    60,
  ),
  topic(
    'extending-a-stint',
    'Why Drivers Extend a Stint',
    'strategy_concept',
    'intermediate',
    'strategy',
    70,
  ),
  topic(
    'offset-strategy',
    'Offset Strategy Explained',
    'strategy_concept',
    'advanced',
    'strategy',
    80,
  ),
  topic(
    'alternative-strategy',
    'Alternative Strategy Explained',
    'strategy_concept',
    'advanced',
    'strategy',
    90,
  ),
  topic(
    'covering-a-rival',
    'Covering a Rival Explained',
    'strategy_concept',
    'intermediate',
    'strategy',
    100,
  ),
  topic(
    'safety-car-strategy',
    'Safety Car Pit Strategy',
    'strategy_concept',
    'advanced',
    'strategy',
    110,
    ['flags-and-safety-car'],
  ),
  topic(
    'vsc-strategy',
    'Virtual Safety Car Strategy',
    'strategy_concept',
    'advanced',
    'strategy',
    120,
    ['flags-and-safety-car'],
  ),
  topic('weather-strategy', 'Weather Strategy', 'strategy_concept', 'advanced', 'strategy', 130, [
    'weather',
  ]),
  topic('tyre-gamble', 'Tyre Gamble Explained', 'strategy_concept', 'advanced', 'strategy', 140),
  topic(
    'how-teams-predict-strategy',
    'How Teams Predict Race Strategy',
    'standard',
    'advanced',
    'strategy',
    150,
    ['analysis'],
  ),
  topic(
    'why-strategy-changes-mid-race',
    'Why Teams Change Strategy Mid-Race',
    'strategy_concept',
    'intermediate',
    'strategy',
    160,
  ),

  /* ── Flags & safety car ─────────────────────────────────────────────────── */
  topic('flag-system', 'F1 Flag System Explained', 'flag', 'beginner', 'flags-and-safety-car', 10),
  topic('yellow-flag', 'Yellow Flag Explained', 'flag', 'beginner', 'flags-and-safety-car', 20),
  topic('double-yellow-flag', 'Double Yellow Flag', 'flag', 'beginner', 'flags-and-safety-car', 30),
  topic('red-flag', 'Red Flag Explained', 'flag', 'beginner', 'flags-and-safety-car', 40),
  topic('blue-flag', 'Blue Flag Explained', 'flag', 'beginner', 'flags-and-safety-car', 50),
  topic('black-flag', 'Black Flag Explained', 'flag', 'intermediate', 'flags-and-safety-car', 60),
  topic(
    'black-and-white-flag',
    'Black-and-White Flag Explained',
    'flag',
    'intermediate',
    'flags-and-safety-car',
    70,
  ),
  topic(
    'chequered-flag',
    'Chequered Flag Explained',
    'flag',
    'beginner',
    'flags-and-safety-car',
    80,
  ),
  topic('safety-car', 'Safety Car Explained', 'procedure', 'beginner', 'flags-and-safety-car', 90),
  topic(
    'virtual-safety-car',
    'Virtual Safety Car Explained',
    'procedure',
    'intermediate',
    'flags-and-safety-car',
    100,
  ),
  topic(
    'safety-car-vs-vsc',
    'Safety Car vs VSC',
    'standard',
    'intermediate',
    'flags-and-safety-car',
    110,
  ),
  topic(
    'why-safety-cars-close-the-field',
    'Why Safety Cars Close Up the Field',
    'standard',
    'beginner',
    'flags-and-safety-car',
    120,
  ),
  topic(
    'what-happens-to-race-gaps',
    'What Happens to Race Gaps?',
    'standard',
    'intermediate',
    'flags-and-safety-car',
    130,
  ),
  topic(
    'safety-car-restart',
    'Safety Car Restart Explained',
    'procedure',
    'intermediate',
    'flags-and-safety-car',
    140,
  ),
  topic(
    'lapped-cars-under-safety-car',
    'Lapped Cars Under Safety Car',
    'rule',
    'advanced',
    'flags-and-safety-car',
    150,
  ),
  topic(
    'red-flag-restart',
    'Red Flag Restart Explained',
    'procedure',
    'intermediate',
    'flags-and-safety-car',
    160,
  ),

  /* ── Overtaking ─────────────────────────────────────────────────────────── */
  topic(
    'how-overtaking-works',
    'How Overtaking Works in F1',
    'tactical_concept',
    'beginner',
    'overtaking',
    10,
  ),
  topic('drs', 'DRS Explained', 'tactical_concept', 'beginner', 'overtaking', 20, ['aerodynamics']),
  topic(
    'drs-detection-point',
    'DRS Detection Point Explained',
    'rule',
    'intermediate',
    'overtaking',
    30,
  ),
  topic('drs-activation-zone', 'DRS Activation Zone', 'rule', 'intermediate', 'overtaking', 40),
  topic('slipstream', 'Slipstream Explained', 'tactical_concept', 'beginner', 'overtaking', 50, [
    'aerodynamics',
  ]),
  topic('dirty-air', 'Dirty Air Explained', 'tactical_concept', 'intermediate', 'overtaking', 60, [
    'aerodynamics',
  ]),
  topic(
    'why-following-is-difficult',
    'Why Following Another Car Is Difficult',
    'tactical_concept',
    'intermediate',
    'overtaking',
    70,
    ['aerodynamics'],
  ),
  topic(
    'outbraking',
    'Outbraking Explained',
    'tactical_concept',
    'intermediate',
    'overtaking',
    80,
    ['driving'],
  ),
  topic(
    'late-braking',
    'Late Braking Explained',
    'tactical_concept',
    'intermediate',
    'overtaking',
    90,
    ['driving'],
  ),
  topic('switchback', 'Switchback Explained', 'tactical_concept', 'advanced', 'overtaking', 100),
  topic('divebomb', 'Divebomb Explained', 'tactical_concept', 'intermediate', 'overtaking', 110),
  topic('racing-line', 'Racing Line Explained', 'tactical_concept', 'beginner', 'overtaking', 120, [
    'driving',
    'circuits',
  ]),
  topic(
    'inside-vs-outside-line',
    'Inside vs Outside Line',
    'tactical_concept',
    'intermediate',
    'overtaking',
    130,
  ),
  topic(
    'defensive-driving',
    'Defensive Driving Explained',
    'tactical_concept',
    'intermediate',
    'overtaking',
    140,
    ['driving'],
  ),
  topic(
    'why-some-circuits-are-hard-to-overtake',
    'Why Some Circuits Are Hard to Overtake On',
    'standard',
    'intermediate',
    'overtaking',
    150,
    ['circuits'],
  ),

  /* ── The car ────────────────────────────────────────────────────────────── */
  topic('how-an-f1-car-works', 'How an F1 Car Works', 'standard', 'beginner', 'the-car', 10),
  topic('anatomy-of-an-f1-car', 'Anatomy of an F1 Car', 'car_component', 'beginner', 'the-car', 20),
  topic('chassis', 'Chassis Explained', 'car_component', 'intermediate', 'the-car', 30),
  topic('monocoque', 'Monocoque Explained', 'car_component', 'intermediate', 'the-car', 40),
  topic('front-wing', 'Front Wing Explained', 'car_component', 'beginner', 'the-car', 50, [
    'aerodynamics',
  ]),
  topic('rear-wing', 'Rear Wing Explained', 'car_component', 'beginner', 'the-car', 60, [
    'aerodynamics',
  ]),
  topic('floor', 'Floor Explained', 'car_component', 'intermediate', 'the-car', 70, [
    'aerodynamics',
  ]),
  topic('diffuser', 'Diffuser Explained', 'car_component', 'advanced', 'the-car', 80, [
    'aerodynamics',
  ]),
  topic('sidepods', 'Sidepods Explained', 'car_component', 'intermediate', 'the-car', 90, [
    'aerodynamics',
  ]),
  topic('suspension', 'Suspension Explained', 'car_component', 'intermediate', 'the-car', 100, [
    'car-setup',
  ]),
  topic('steering-wheel', 'Steering Wheel Explained', 'car_component', 'beginner', 'the-car', 110),
  topic('gearbox', 'Gearbox Explained', 'car_component', 'intermediate', 'the-car', 120),
  topic('brakes', 'Brakes Explained', 'car_component', 'intermediate', 'the-car', 130, ['driving']),
  topic('brake-by-wire', 'Brake-by-Wire Explained', 'car_component', 'advanced', 'the-car', 140, [
    'power-unit',
  ]),
  topic('fuel-system', 'Fuel System Explained', 'car_component', 'intermediate', 'the-car', 150),
  topic(
    'cooling-system',
    'Cooling System Explained',
    'car_component',
    'intermediate',
    'the-car',
    160,
  ),
  topic('halo', 'Halo Explained', 'car_component', 'beginner', 'the-car', 170),

  /* ── Aerodynamics ───────────────────────────────────────────────────────── */
  topic(
    'aerodynamics-explained',
    'F1 Aerodynamics Explained',
    'tactical_concept',
    'intermediate',
    'aerodynamics',
    10,
  ),
  topic('downforce', 'Downforce Explained', 'tactical_concept', 'beginner', 'aerodynamics', 20),
  topic('drag', 'Drag Explained', 'tactical_concept', 'beginner', 'aerodynamics', 30),
  topic(
    'downforce-vs-drag',
    'Downforce vs Drag',
    'tactical_concept',
    'intermediate',
    'aerodynamics',
    40,
  ),
  topic(
    'ground-effect',
    'Ground Effect Explained',
    'tactical_concept',
    'advanced',
    'aerodynamics',
    50,
  ),
  topic(
    'venturi-tunnels',
    'Venturi Tunnels Explained',
    'tactical_concept',
    'advanced',
    'aerodynamics',
    60,
  ),
  topic(
    'front-wing-aerodynamics',
    'Front Wing Aerodynamics',
    'tactical_concept',
    'advanced',
    'aerodynamics',
    70,
  ),
  topic(
    'rear-wing-aerodynamics',
    'Rear Wing Aerodynamics',
    'tactical_concept',
    'advanced',
    'aerodynamics',
    80,
  ),
  topic(
    'floor-aerodynamics',
    'Floor Aerodynamics',
    'tactical_concept',
    'advanced',
    'aerodynamics',
    90,
  ),
  topic('vortices', 'Vortices Explained', 'tactical_concept', 'advanced', 'aerodynamics', 100),
  topic(
    'aerodynamic-balance',
    'Aerodynamic Balance',
    'tactical_concept',
    'advanced',
    'aerodynamics',
    110,
    ['car-setup'],
  ),
  topic(
    'high-downforce-setup',
    'High-Downforce Setup',
    'tactical_concept',
    'intermediate',
    'aerodynamics',
    120,
    ['car-setup'],
  ),
  topic(
    'low-downforce-setup',
    'Low-Downforce Setup',
    'tactical_concept',
    'intermediate',
    'aerodynamics',
    130,
    ['car-setup'],
  ),
  topic(
    'monaco-vs-monza',
    'Why Monaco and Monza Need Different Cars',
    'standard',
    'intermediate',
    'aerodynamics',
    140,
    ['circuits'],
  ),
  topic('porpoising', 'Porpoising Explained', 'tactical_concept', 'advanced', 'aerodynamics', 150),
  topic(
    'ride-height',
    'Ride Height Explained',
    'tactical_concept',
    'advanced',
    'aerodynamics',
    160,
    ['car-setup'],
  ),

  /* ── Power unit ─────────────────────────────────────────────────────────── */
  topic(
    'power-unit-explained',
    'F1 Power Unit Explained',
    'car_component',
    'intermediate',
    'power-unit',
    10,
  ),
  topic(
    'internal-combustion-engine',
    'Internal Combustion Engine',
    'car_component',
    'intermediate',
    'power-unit',
    20,
  ),
  topic(
    'turbocharger',
    'Turbocharger Explained',
    'car_component',
    'intermediate',
    'power-unit',
    30,
  ),
  topic(
    'hybrid-system',
    'Hybrid System Explained',
    'car_component',
    'intermediate',
    'power-unit',
    40,
  ),
  topic(
    'energy-recovery',
    'Energy Recovery Explained',
    'tactical_concept',
    'advanced',
    'power-unit',
    50,
  ),
  topic('ers', 'ERS Explained', 'car_component', 'advanced', 'power-unit', 60),
  topic(
    'energy-deployment',
    'Energy Deployment Explained',
    'tactical_concept',
    'advanced',
    'power-unit',
    70,
  ),
  topic(
    'energy-store',
    'Battery and Energy Store Explained',
    'car_component',
    'advanced',
    'power-unit',
    80,
  ),
  topic(
    'control-electronics',
    'Control Electronics Explained',
    'car_component',
    'advanced',
    'power-unit',
    90,
  ),
  topic(
    'power-unit-components',
    'Power Unit Components',
    'car_component',
    'intermediate',
    'power-unit',
    100,
  ),
  topic(
    'engine-modes',
    'Engine Modes Explained',
    'tactical_concept',
    'advanced',
    'power-unit',
    110,
  ),
  topic(
    'why-drivers-save-energy',
    'Why Drivers Save Energy',
    'tactical_concept',
    'advanced',
    'power-unit',
    120,
  ),
  topic(
    'why-f1-engines-are-efficient',
    'Why F1 Engines Are So Efficient',
    'standard',
    'advanced',
    'power-unit',
    130,
  ),
  topic(
    'power-unit-penalties',
    'Power Unit Penalties Explained',
    'penalty',
    'intermediate',
    'power-unit',
    140,
    ['rules-and-penalties'],
  ),

  /* ── Driving & technique ────────────────────────────────────────────────── */
  topic(
    'how-f1-cars-brake',
    'How F1 Cars Brake',
    'tactical_concept',
    'intermediate',
    'driving',
    10,
  ),
  topic(
    'why-f1-brakes-are-powerful',
    'Why F1 Brakes Are So Powerful',
    'tactical_concept',
    'intermediate',
    'driving',
    20,
  ),
  topic(
    'brake-temperature',
    'Brake Temperature Explained',
    'tactical_concept',
    'advanced',
    'driving',
    30,
  ),
  topic('brake-balance', 'Brake Balance Explained', 'tactical_concept', 'advanced', 'driving', 40, [
    'car-setup',
  ]),
  topic('trail-braking', 'Trail Braking Explained', 'tactical_concept', 'advanced', 'driving', 50),
  topic('lock-up', 'Lock-Up Explained', 'tactical_concept', 'beginner', 'driving', 60),
  topic(
    'corner-entry',
    'Corner Entry Explained',
    'tactical_concept',
    'intermediate',
    'driving',
    70,
  ),
  topic('apex', 'Apex Explained', 'definition', 'beginner', 'driving', 80, ['glossary']),
  topic('corner-exit', 'Corner Exit Explained', 'tactical_concept', 'intermediate', 'driving', 90),
  topic(
    'slow-vs-fast-corners',
    'Slow vs Fast Corners',
    'tactical_concept',
    'intermediate',
    'driving',
    100,
    ['circuits'],
  ),
  topic('understeer', 'Understeer Explained', 'tactical_concept', 'beginner', 'driving', 110),
  topic('oversteer', 'Oversteer Explained', 'tactical_concept', 'beginner', 'driving', 120),
  topic(
    'correcting-slides',
    'Why Drivers Correct Slides',
    'tactical_concept',
    'intermediate',
    'driving',
    130,
  ),
  topic(
    'what-makes-an-elite-driver',
    'What Makes an Elite F1 Driver?',
    'standard',
    'intermediate',
    'driving',
    140,
  ),
  topic('throttle-control', 'Throttle Control', 'tactical_concept', 'intermediate', 'driving', 150),
  topic('racecraft', 'Racecraft Explained', 'tactical_concept', 'intermediate', 'driving', 160),
  topic('qualifying-skill', 'Qualifying Skill', 'standard', 'intermediate', 'driving', 170, [
    'qualifying',
  ]),
  topic(
    'wet-weather-driving',
    'Wet-Weather Driving',
    'tactical_concept',
    'advanced',
    'driving',
    180,
    ['weather'],
  ),
  topic('driver-consistency', 'Consistency', 'standard', 'intermediate', 'driving', 190),
  topic('driver-adaptability', 'Adaptability', 'standard', 'intermediate', 'driving', 200),
  topic('technical-feedback', 'Technical Feedback', 'standard', 'advanced', 'driving', 210, [
    'teams',
  ]),
  topic('reaction-time', 'Reaction Time', 'standard', 'beginner', 'driving', 220),
  topic('driver-fitness', 'Physical Fitness', 'standard', 'beginner', 'driving', 230),
  topic('mental-load', 'Mental Load During a Race', 'standard', 'intermediate', 'driving', 240),

  /* ── Car setup ──────────────────────────────────────────────────────────── */
  topic(
    'car-setup-explained',
    'F1 Car Setup Explained',
    'tactical_concept',
    'intermediate',
    'car-setup',
    10,
  ),
  topic(
    'front-wing-setup',
    'Front Wing Setup',
    'tactical_concept',
    'intermediate',
    'car-setup',
    20,
  ),
  topic('rear-wing-setup', 'Rear Wing Setup', 'tactical_concept', 'intermediate', 'car-setup', 30),
  topic('suspension-setup', 'Suspension Setup', 'tactical_concept', 'advanced', 'car-setup', 40),
  topic('camber', 'Camber Explained', 'tactical_concept', 'advanced', 'car-setup', 50),
  topic('toe', 'Toe Explained', 'tactical_concept', 'advanced', 'car-setup', 60),
  topic('brake-bias', 'Brake Bias', 'tactical_concept', 'advanced', 'car-setup', 70, ['driving']),
  topic(
    'differential-settings',
    'Differential Settings',
    'tactical_concept',
    'advanced',
    'car-setup',
    80,
  ),
  topic('tyre-pressures', 'Tyre Pressures', 'tactical_concept', 'advanced', 'car-setup', 90, [
    'tyres',
  ]),
  topic('wet-setup', 'Wet Setup', 'tactical_concept', 'advanced', 'car-setup', 100, ['weather']),
  topic(
    'why-teams-compromise-setup',
    'Why Teams Compromise Setup',
    'standard',
    'intermediate',
    'car-setup',
    110,
  ),
  topic(
    'qualifying-vs-race-setup',
    'Qualifying Setup vs Race Setup',
    'tactical_concept',
    'advanced',
    'car-setup',
    120,
  ),

  /* ── Telemetry & lap time ───────────────────────────────────────────────── */
  topic(
    'telemetry-explained',
    'F1 Telemetry Explained',
    'statistic',
    'intermediate',
    'telemetry',
    10,
  ),
  topic('speed-trace', 'Speed Traces Explained', 'statistic', 'advanced', 'telemetry', 20),
  topic('throttle-trace', 'Throttle Trace Explained', 'statistic', 'advanced', 'telemetry', 30),
  topic('brake-trace', 'Brake Trace Explained', 'statistic', 'advanced', 'telemetry', 40),
  topic('gear-data', 'Gear Data Explained', 'statistic', 'advanced', 'telemetry', 50),
  topic('steering-input', 'Steering Input Explained', 'statistic', 'advanced', 'telemetry', 60),
  topic('gps-data', 'GPS Data Explained', 'statistic', 'advanced', 'telemetry', 70),
  topic('sector-times', 'Sector Times Explained', 'statistic', 'beginner', 'telemetry', 80),
  topic('mini-sectors', 'Mini-Sectors Explained', 'statistic', 'advanced', 'telemetry', 90),
  topic('delta-time', 'Delta Time Explained', 'statistic', 'intermediate', 'telemetry', 100),
  topic('lap-comparison', 'Lap Comparison Explained', 'statistic', 'advanced', 'telemetry', 110),
  topic('long-run-pace', 'Long-Run Pace Explained', 'statistic', 'advanced', 'telemetry', 120, [
    'analysis',
  ]),
  topic(
    'race-pace-vs-qualifying-pace',
    'Race Pace vs Qualifying Pace',
    'statistic',
    'intermediate',
    'telemetry',
    130,
    ['analysis'],
  ),
  topic('lap-time-explained', 'Lap Time Explained', 'statistic', 'beginner', 'telemetry', 140),
  topic(
    'personal-best-vs-session-best',
    'Personal Best vs Session Best',
    'definition',
    'beginner',
    'telemetry',
    150,
  ),
  topic('purple-sector', 'Purple Sector Explained', 'definition', 'beginner', 'telemetry', 160),
  topic('fuel-correction', 'Fuel Correction Explained', 'statistic', 'advanced', 'telemetry', 170, [
    'analysis',
  ]),
  topic(
    'why-qualifying-laps-are-faster',
    'Why Qualifying Laps Are Faster',
    'standard',
    'beginner',
    'telemetry',
    180,
  ),
  topic(
    'why-race-laps-are-slower',
    'Why Race Laps Are Slower',
    'standard',
    'beginner',
    'telemetry',
    190,
  ),
  topic('perfect-lap', 'What Makes a Perfect Lap?', 'standard', 'intermediate', 'telemetry', 200),
  topic(
    'gaining-tenths',
    'How Drivers Gain Tenths of a Second',
    'standard',
    'advanced',
    'telemetry',
    210,
  ),

  /* ── Circuits ───────────────────────────────────────────────────────────── */
  topic('circuits-explained', 'F1 Circuits Explained', 'circuit', 'beginner', 'circuits', 10),
  topic(
    'street-vs-permanent',
    'Street Circuit vs Permanent Circuit',
    'circuit',
    'beginner',
    'circuits',
    20,
  ),
  topic('track-layout', 'Track Layout Explained', 'circuit', 'beginner', 'circuits', 30),
  topic('sector', 'Sector Explained', 'definition', 'beginner', 'circuits', 40, [
    'telemetry',
    'glossary',
  ]),
  topic('straight', 'Straight Explained', 'definition', 'beginner', 'circuits', 50),
  topic('chicane', 'Chicane Explained', 'definition', 'beginner', 'circuits', 60, ['glossary']),
  topic('hairpin', 'Hairpin Explained', 'definition', 'beginner', 'circuits', 70, ['glossary']),
  topic('esses', 'Esses Explained', 'definition', 'intermediate', 'circuits', 80),
  topic(
    'track-camber',
    'Camber Explained (Circuits)',
    'definition',
    'intermediate',
    'circuits',
    90,
  ),
  topic(
    'elevation-change',
    'Elevation Change Explained',
    'circuit',
    'intermediate',
    'circuits',
    100,
  ),
  topic('track-surface', 'Track Surface Explained', 'circuit', 'intermediate', 'circuits', 110),
  topic('kerbs', 'Kerbs Explained', 'definition', 'beginner', 'circuits', 120, ['glossary']),
  topic('run-off-areas', 'Run-Off Areas Explained', 'circuit', 'beginner', 'circuits', 130),
  topic('gravel-traps', 'Gravel Traps Explained', 'circuit', 'beginner', 'circuits', 140),
  topic(
    'why-circuits-suit-different-cars',
    'Why Different Circuits Suit Different Cars',
    'standard',
    'intermediate',
    'circuits',
    150,
  ),

  /* ── Weather ────────────────────────────────────────────────────────────── */
  topic('how-rain-changes-f1', 'How Rain Changes F1', 'standard', 'beginner', 'weather', 10),
  topic('aquaplaning', 'Aquaplaning Explained', 'tactical_concept', 'intermediate', 'weather', 20),
  topic(
    'visibility-in-the-wet',
    'Why Visibility Becomes Dangerous',
    'standard',
    'beginner',
    'weather',
    30,
  ),
  topic(
    'track-drying',
    'Track Drying Explained',
    'tactical_concept',
    'intermediate',
    'weather',
    40,
  ),
  topic(
    'crossover-point',
    'Crossover Point Explained',
    'strategy_concept',
    'advanced',
    'weather',
    50,
    ['strategy'],
  ),
  topic(
    'slicks-vs-intermediates',
    'Slicks vs Intermediates',
    'strategy_concept',
    'intermediate',
    'weather',
    60,
    ['tyres'],
  ),
  topic(
    'changing-weather-strategy',
    'Changing Weather Strategy',
    'strategy_concept',
    'advanced',
    'weather',
    70,
  ),
  topic('wind-and-f1-cars', 'Wind and F1 Cars', 'tactical_concept', 'advanced', 'weather', 80, [
    'aerodynamics',
  ]),
  topic(
    'track-temperature',
    'Track Temperature Explained',
    'tactical_concept',
    'intermediate',
    'weather',
    90,
    ['tyres'],
  ),
  topic(
    'air-temperature',
    'Air Temperature Explained',
    'tactical_concept',
    'intermediate',
    'weather',
    100,
  ),

  /* ── Rules & penalties ──────────────────────────────────────────────────── */
  topic(
    'penalties-explained',
    'F1 Penalties Explained',
    'penalty',
    'beginner',
    'rules-and-penalties',
    10,
  ),
  topic('time-penalty', 'Time Penalty Explained', 'penalty', 'beginner', 'rules-and-penalties', 20),
  topic(
    'drive-through-penalty',
    'Drive-Through Penalty',
    'penalty',
    'intermediate',
    'rules-and-penalties',
    30,
  ),
  topic('stop-go-penalty', 'Stop-Go Penalty', 'penalty', 'intermediate', 'rules-and-penalties', 40),
  topic('grid-penalty', 'Grid Penalty', 'penalty', 'beginner', 'rules-and-penalties', 50),
  topic('penalty-points', 'Penalty Points', 'penalty', 'intermediate', 'rules-and-penalties', 60),
  topic('reprimand', 'Reprimand Explained', 'penalty', 'intermediate', 'rules-and-penalties', 70),
  topic(
    'disqualification',
    'Disqualification Explained',
    'penalty',
    'intermediate',
    'rules-and-penalties',
    80,
  ),
  topic('pit-lane-speeding', 'Pit Lane Speeding', 'penalty', 'beginner', 'rules-and-penalties', 90),
  topic(
    'track-limits-penalties',
    'Track Limits Penalties',
    'penalty',
    'intermediate',
    'rules-and-penalties',
    100,
  ),
  topic(
    'causing-a-collision',
    'Causing a Collision',
    'penalty',
    'intermediate',
    'rules-and-penalties',
    110,
  ),
  topic(
    'leaving-the-track-and-gaining-an-advantage',
    'Leaving the Track and Gaining an Advantage',
    'rule',
    'intermediate',
    'rules-and-penalties',
    120,
    ['overtaking'],
  ),
  topic('impeding', 'Impeding Explained', 'penalty', 'intermediate', 'rules-and-penalties', 130, [
    'qualifying',
  ]),
  topic(
    'false-start',
    'False Start Explained',
    'penalty',
    'intermediate',
    'rules-and-penalties',
    140,
    ['the-race'],
  ),
  topic(
    'technical-infringements',
    'Technical Infringements',
    'penalty',
    'advanced',
    'rules-and-penalties',
    150,
  ),
  topic(
    'how-stewards-decide',
    'How F1 Stewards Make Decisions',
    'standard',
    'intermediate',
    'rules-and-penalties',
    160,
  ),
  topic('track-limits', 'Track Limits Explained', 'rule', 'beginner', 'rules-and-penalties', 170, [
    'overtaking',
    'circuits',
  ]),
  topic('white-line-rules', 'White Line Rules', 'rule', 'intermediate', 'rules-and-penalties', 180),
  topic(
    'racing-room',
    'Racing Room Explained',
    'rule',
    'intermediate',
    'rules-and-penalties',
    190,
    ['overtaking'],
  ),
  topic(
    'overtaking-off-track',
    'Overtaking Off Track',
    'rule',
    'intermediate',
    'rules-and-penalties',
    200,
    ['overtaking'],
  ),
  topic(
    'defensive-driving-rules',
    'Defensive Driving Rules',
    'rule',
    'intermediate',
    'rules-and-penalties',
    210,
    ['overtaking'],
  ),
  topic(
    'multiple-direction-changes',
    'Multiple Direction Changes',
    'rule',
    'advanced',
    'rules-and-penalties',
    220,
    ['overtaking'],
  ),
  topic(
    'moving-under-braking',
    'Moving Under Braking',
    'rule',
    'advanced',
    'rules-and-penalties',
    230,
    ['overtaking'],
  ),
  topic(
    'forcing-a-driver-off-track',
    'Forcing Another Driver Off Track',
    'rule',
    'intermediate',
    'rules-and-penalties',
    240,
    ['overtaking'],
  ),
  topic(
    'why-track-limits-differ',
    'Why Track Limits Differ by Circuit',
    'standard',
    'intermediate',
    'rules-and-penalties',
    250,
    ['circuits'],
  ),

  /* ── Teams & people ─────────────────────────────────────────────────────── */
  topic('how-a-team-works', 'How an F1 Team Works', 'standard', 'beginner', 'teams', 10),
  topic('team-principal', 'Team Principal Explained', 'position_role', 'beginner', 'teams', 20),
  topic('race-engineer', 'Race Engineer Explained', 'position_role', 'beginner', 'teams', 30),
  topic(
    'performance-engineer',
    'Performance Engineer',
    'position_role',
    'intermediate',
    'teams',
    40,
  ),
  topic('strategist', 'Strategist Explained', 'position_role', 'intermediate', 'teams', 50, [
    'strategy',
  ]),
  topic('mechanics', 'Mechanics Explained', 'position_role', 'beginner', 'teams', 60),
  topic(
    'technical-director',
    'Technical Director Explained',
    'position_role',
    'intermediate',
    'teams',
    70,
  ),
  topic(
    'aerodynamics-department',
    'Aerodynamics Department',
    'position_role',
    'advanced',
    'teams',
    80,
    ['aerodynamics'],
  ),
  topic('simulator-drivers', 'Simulator Drivers', 'position_role', 'intermediate', 'teams', 90),
  topic('reserve-drivers', 'Reserve Drivers Explained', 'position_role', 'beginner', 'teams', 100, [
    'pathway',
  ]),
  topic('team-radio', 'Team Radio Explained', 'standard', 'beginner', 'teams', 110),
  topic(
    'how-teams-decide-in-a-race',
    'How Teams Make Decisions During a Race',
    'standard',
    'advanced',
    'teams',
    120,
    ['strategy'],
  ),
  topic('team-orders', 'Team Orders Explained', 'strategy_concept', 'intermediate', 'teams', 130),
  topic(
    'number-one-driver',
    'Number One Driver Explained',
    'standard',
    'intermediate',
    'teams',
    140,
  ),
  topic(
    'why-teammates-are-compared',
    'Why Teammates Are Compared So Closely',
    'standard',
    'intermediate',
    'teams',
    150,
    ['analysis'],
  ),
  topic(
    'same-car-is-it-equal',
    'Same Car: Is It Really Equal?',
    'standard',
    'advanced',
    'teams',
    160,
  ),
  topic('teammate-rivalries', 'Teammate Rivalries', 'standard', 'beginner', 'teams', 170),
  topic(
    'car-development',
    'F1 Car Development Explained',
    'standard',
    'intermediate',
    'teams',
    180,
  ),
  topic(
    'upgrade-package',
    'What Is an Upgrade Package?',
    'definition',
    'intermediate',
    'teams',
    190,
  ),
  topic('why-upgrades-fail', 'Why Upgrades Sometimes Fail', 'standard', 'advanced', 'teams', 200),
  topic('correlation', 'Correlation Explained', 'tactical_concept', 'advanced', 'teams', 210),
  topic('wind-tunnel-testing', 'Wind Tunnel Testing', 'standard', 'advanced', 'teams', 220, [
    'aerodynamics',
  ]),
  topic('cfd', 'CFD Explained', 'standard', 'advanced', 'teams', 230, ['aerodynamics']),
  topic(
    'why-cars-improve-in-a-season',
    'Why Cars Improve During a Season',
    'standard',
    'intermediate',
    'teams',
    240,
  ),

  /* ── Regulations & business ─────────────────────────────────────────────── */
  topic(
    'regulations-explained',
    'F1 Regulations Explained',
    'rule',
    'intermediate',
    'business',
    10,
  ),
  topic('sporting-regulations', 'Sporting Regulations', 'rule', 'intermediate', 'business', 20),
  topic('technical-regulations', 'Technical Regulations', 'rule', 'intermediate', 'business', 30),
  topic('financial-regulations', 'Financial Regulations', 'rule', 'advanced', 'business', 40),
  topic('why-f1-changes-rules', 'Why F1 Changes Rules', 'standard', 'intermediate', 'business', 50),
  topic('regulation-eras', 'Regulation Eras Explained', 'standard', 'intermediate', 'business', 60),
  topic('cost-cap', 'Cost Cap Explained', 'rule', 'intermediate', 'business', 70),
  topic('power-unit-allocation', 'Power Unit Allocation', 'rule', 'intermediate', 'business', 80, [
    'power-unit',
  ]),
  topic('component-rules', 'Gearbox and Component Rules', 'rule', 'advanced', 'business', 90),
  topic('minimum-weight', 'Minimum Weight Explained', 'rule', 'intermediate', 'business', 100),
  topic('fuel-rules', 'Fuel Rules', 'rule', 'advanced', 'business', 110),
  topic('car-legality-checks', 'Car Legality Checks', 'procedure', 'advanced', 'business', 120),
  topic('scrutineering', 'Scrutineering Explained', 'procedure', 'intermediate', 'business', 130),
  topic(
    'why-f1-introduced-a-cost-cap',
    'Why F1 Introduced a Cost Cap',
    'standard',
    'intermediate',
    'business',
    140,
  ),
  topic(
    'what-counts-toward-the-cost-cap',
    'What Counts Toward the Cost Cap?',
    'rule',
    'advanced',
    'business',
    150,
  ),
  topic('cost-cap-breaches', 'Cost Cap Breaches', 'standard', 'advanced', 'business', 160),
  topic('prize-money', "Constructors' Prize Money", 'standard', 'intermediate', 'business', 170),
  topic('sponsorship', 'Sponsorship in F1', 'standard', 'beginner', 'business', 180),
  topic(
    'how-teams-make-money',
    'How F1 Teams Make Money',
    'standard',
    'intermediate',
    'business',
    190,
  ),
  topic(
    'why-constructors-compete',
    'Why Constructors Compete in F1',
    'standard',
    'beginner',
    'business',
    200,
  ),
  topic(
    'driver-salaries-vs-budgets',
    'Driver Salaries vs Team Budgets',
    'standard',
    'intermediate',
    'business',
    210,
  ),

  /* ── Getting to F1 ──────────────────────────────────────────────────────── */
  topic(
    'driver-contracts',
    'F1 Driver Contracts Explained',
    'standard',
    'intermediate',
    'pathway',
    10,
  ),
  topic('driver-market', 'What Is the Driver Market?', 'standard', 'beginner', 'pathway', 20),
  topic('rookie-drivers', 'Rookie Drivers Explained', 'definition', 'beginner', 'pathway', 30),
  topic('test-drivers', 'Test Drivers Explained', 'position_role', 'beginner', 'pathway', 40),
  topic('driver-academies', 'Driver Academies Explained', 'standard', 'beginner', 'pathway', 50),
  topic('super-licence', 'Super Licence Explained', 'rule', 'intermediate', 'pathway', 60),
  topic(
    'how-drivers-reach-f1',
    'How Drivers Reach Formula 1',
    'standard',
    'beginner',
    'pathway',
    70,
  ),
  topic('f2-to-f1', 'F2 to F1 Pathway', 'standard', 'beginner', 'pathway', 80),
  topic(
    'why-drivers-change-teams',
    'Why Drivers Change Teams',
    'standard',
    'beginner',
    'pathway',
    90,
  ),
  topic(
    'mid-season-driver-changes',
    'Mid-Season Driver Changes',
    'standard',
    'intermediate',
    'pathway',
    100,
  ),
  topic(
    'when-a-driver-is-dropped',
    'What Happens When a Driver Is Dropped?',
    'standard',
    'intermediate',
    'pathway',
    110,
  ),
  topic('formula-2', 'Formula 2 Explained', 'format', 'beginner', 'pathway', 120),
  topic('formula-3', 'Formula 3 Explained', 'format', 'beginner', 'pathway', 130),
  topic('f1-academy', 'F1 Academy Explained', 'format', 'beginner', 'pathway', 140),
  topic('karting-to-f1', 'Karting to Formula 1', 'standard', 'beginner', 'pathway', 150),
  topic('junior-formula', 'Junior Formula Categories', 'format', 'intermediate', 'pathway', 160),
  topic('super-licence-points', 'Super Licence Points', 'rule', 'intermediate', 'pathway', 170),

  /* ── Performance analysis ───────────────────────────────────────────────── */
  topic(
    'qualifying-pace-analysis',
    'Qualifying Pace Analysis',
    'statistic',
    'advanced',
    'analysis',
    10,
  ),
  topic('race-pace-analysis', 'Race Pace Analysis', 'statistic', 'advanced', 'analysis', 20),
  topic('teammate-delta', 'Teammate Delta', 'statistic', 'advanced', 'analysis', 30),
  topic('tyre-corrected-pace', 'Tyre-Corrected Pace', 'statistic', 'advanced', 'analysis', 40),
  topic(
    'fuel-corrected-lap-times',
    'Fuel-Corrected Lap Times',
    'statistic',
    'advanced',
    'analysis',
    50,
  ),
  topic(
    'track-adjusted-performance',
    'Track-Adjusted Performance',
    'statistic',
    'advanced',
    'analysis',
    60,
  ),
  topic('sector-analysis', 'Sector Analysis', 'statistic', 'advanced', 'analysis', 70),
  topic('corner-speed-analysis', 'Corner-Speed Analysis', 'statistic', 'advanced', 'analysis', 80),
  topic(
    'straight-line-speed-analysis',
    'Straight-Line Speed Analysis',
    'statistic',
    'advanced',
    'analysis',
    90,
  ),
  topic('degradation-curves', 'Degradation Curves', 'statistic', 'advanced', 'analysis', 100),
  topic(
    'pit-stop-loss-analysis',
    'Pit Stop Loss Analysis',
    'statistic',
    'advanced',
    'analysis',
    110,
  ),
  topic('strategy-simulation', 'Strategy Simulation', 'statistic', 'advanced', 'analysis', 120),
  topic(
    'expected-race-position',
    'Expected Race Position',
    'statistic',
    'advanced',
    'analysis',
    130,
  ),
  topic('undercut-power', 'Undercut Power', 'statistic', 'advanced', 'analysis', 140),
  topic('overtaking-difficulty', 'Overtaking Difficulty', 'statistic', 'advanced', 'analysis', 150),
  topic(
    'car-vs-driver-performance',
    'Car Performance vs Driver Performance',
    'statistic',
    'advanced',
    'analysis',
    160,
  ),
  topic(
    'reliability-adjusted-performance',
    'Reliability-Adjusted Performance',
    'statistic',
    'advanced',
    'analysis',
    170,
  ),

  /* ── Glossary ───────────────────────────────────────────────────────────── */
  topic('paddock', 'Paddock', 'definition', 'beginner', 'glossary', 10),
  topic('stint', 'Stint', 'definition', 'beginner', 'glossary', 20),
  topic('constructor', 'Constructor', 'definition', 'beginner', 'glossary', 30),
];
