import type { ExplainerCategorySeed, ExplainerSeed } from './explainer-types';

/**
 * The golf taxonomy: the categories, and every concept the library intends to
 * cover.
 *
 * Everything in this file is a draft placeholder. Nothing here reaches the
 * site. The written explainers live in `golf-explainers.ts` and the four
 * supplementary content files, and they override these by slug, which is why
 * the slugs here have to be right first time: a typo produces a second concept
 * rather than a written version of the first.
 *
 * ## On categories
 *
 * The brief names thirty-four groupings. That is a table of contents for the
 * writing, not a navigation for a reader, and shipping thirty-four headings
 * would ask the reader to do the organising themselves. They are consolidated
 * here into sixteen shown on the landing page and six below the fold, with the
 * brief's groupings preserved as the ordering within each: Category 5 (basic
 * shots) and Category 6 (ball flight) are one Shots category because a fade is
 * both, and Categories 8 and 9 are one Short Game category for the same reason
 * a chip and a putt are the same decision from six feet off the green.
 *
 * Nothing is dropped. Every concept the brief lists appears below, and where a
 * concept belongs in two places it is one row with `alsoIn`, never two rows.
 * Slope Rating is a property of a course and an input to a handicap; the
 * unique index on (sport_id, slug) makes one row a guarantee rather than a
 * convention.
 *
 * ## On duplication with the overview
 *
 * The brief's content rule is the reason several obvious titles are absent. The
 * overview answers "what is this"; an explainer answers "how exactly does this
 * work". So there is no `what-is-golf` here, because the overview already
 * carries it, and `how-golf-works` is written as the mechanics of a round
 * rather than as a second introduction.
 */

export const GOLF_EXPLAINER_CATEGORIES: ExplainerCategorySeed[] = [
  {
    slug: 'start-here',
    name: 'Start Here',
    shortName: 'Basics',
    description: 'Golf from zero: how a round is played, scored and won.',
    order: 10,
  },
  {
    slug: 'scoring',
    name: 'Scoring',
    description: 'Par, birdies, bogeys, net scores and reading a leaderboard.',
    order: 20,
  },
  {
    slug: 'the-course',
    name: 'The Golf Course',
    shortName: 'Course',
    description: 'Every part of the ground, from the tee box to the back of the green.',
    order: 30,
  },
  {
    slug: 'clubs-and-equipment',
    name: 'Clubs & Equipment',
    shortName: 'Clubs',
    description: 'The fourteen clubs, the ball, and what loft, lie and bounce actually do.',
    order: 40,
  },
  {
    slug: 'shots',
    name: 'Shots & Ball Flight',
    shortName: 'Shots',
    description: 'Every shot in the bag, and why the ball goes where it goes.',
    order: 50,
  },
  {
    slug: 'the-swing',
    name: 'The Swing',
    shortName: 'Swing',
    description: 'What the club and the body are doing, and the numbers that describe it.',
    order: 60,
  },
  {
    slug: 'putting-and-short-game',
    name: 'Putting & Short Game',
    shortName: 'Short Game',
    description: 'Green reading, chipping, bunker play and getting up and down.',
    order: 70,
  },
  {
    slug: 'handicaps',
    name: 'Handicaps',
    shortName: 'Handicap',
    description: 'How the system that lets anyone play anyone actually works.',
    order: 80,
  },
  {
    slug: 'formats',
    name: 'Formats',
    description: 'Stroke play, match play, four-ball, foursomes and the team events.',
    order: 90,
  },
  {
    slug: 'tournaments',
    name: 'Tournaments',
    description: 'Four rounds, the cut, tee times, playoffs and how a field is filled.',
    order: 100,
  },
  {
    slug: 'majors-and-tours',
    name: 'Majors & Tours',
    shortName: 'Majors',
    description: 'The four majors, the professional tours and how players reach them.',
    order: 110,
  },
  {
    slug: 'rules',
    name: 'Rules',
    description: 'What the Rules of Golf permit, require and forbid.',
    order: 120,
  },
  {
    slug: 'penalties-and-relief',
    name: 'Penalties & Relief',
    shortName: 'Relief',
    description: 'What a rule costs, what relief it gives, and how to take a drop.',
    order: 130,
  },
  {
    slug: 'strategy-and-conditions',
    name: 'Strategy & Conditions',
    shortName: 'Strategy',
    description: 'Course management, wind, weather and playing the ground in front of you.',
    order: 140,
  },
  {
    slug: 'statistics',
    name: 'Golf Statistics',
    shortName: 'Stats',
    description: 'Reading the tour stat sheet, and what the traditional numbers hide.',
    order: 150,
  },
  {
    slug: 'strokes-gained',
    name: 'Strokes Gained',
    description: 'The baseline model that replaced the traditional statistics, worked through.',
    order: 160,
  },
  /*
   * Below the fold.
   *
   * Real categories with real URLs, reachable from a concept's breadcrumb and
   * from search, but not among the sixteen the landing page leads with. This is
   * how the taxonomy grows past what a landing page can show without either
   * hiding concepts or turning the page into a directory.
   */
  {
    slug: 'course-design',
    name: 'Course Design',
    shortName: 'Design',
    description: 'Why architects put a bunker there, and what links and parkland ask of you.',
    order: 170,
  },
  {
    slug: 'world-rankings',
    name: 'World Rankings',
    shortName: 'Rankings',
    description: 'How ranking points are earned, and what they decide.',
    order: 180,
  },
  {
    slug: 'caddies-and-yardage',
    name: 'Caddies & Yardage',
    shortName: 'Caddies',
    description: 'What a caddie does, and how a number on a yardage book becomes a club.',
    order: 190,
  },
  {
    slug: 'etiquette',
    name: 'Etiquette & Safety',
    shortName: 'Etiquette',
    description: 'Pace of play, repairing the course, and not hitting anybody.',
    order: 200,
  },
  {
    slug: 'advanced-analysis',
    name: 'Advanced Analysis',
    shortName: 'Advanced',
    description: 'Derived models: course fit, field strength and expected performance.',
    order: 210,
  },
  {
    slug: 'glossary',
    name: 'Glossary',
    description: 'The A-Z: ace, dogleg, links, lie, loft and the rest.',
    order: 220,
  },
];

/**
 * Every concept, as a draft.
 *
 * `type` and `difficulty` are set here rather than left to default, because
 * they drive the page template and the beginner filter, and a taxonomy that
 * calls everything a beginner `standard` explainer is not carrying information.
 */
export const GOLF_EXPLAINER_TOPICS: ExplainerSeed[] = [
  // ── Start Here ─────────────────────────────────────────────────────────────
  {
    slug: 'golf-in-5-minutes',
    title: 'Golf in 5 Minutes',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-golf-works',
    title: 'How Golf Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-you-win-in-golf',
    title: 'How Do You Win in Golf?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['scoring'],
  },
  {
    slug: 'how-a-golf-course-works',
    title: 'How a Golf Course Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['the-course'],
  },
  {
    slug: 'what-are-18-holes',
    title: 'What Are 18 Holes?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['the-course'],
  },
  {
    slug: 'professional-golf-explained',
    title: 'Professional Golf Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['majors-and-tours'],
  },
  {
    slug: 'how-a-golf-tournament-works',
    title: 'How a Golf Tournament Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
    alsoIn: ['tournaments'],
  },
  {
    slug: 'what-a-round-of-golf-looks-like',
    title: 'What a Round of Golf Looks Like',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },

  // ── Scoring ────────────────────────────────────────────────────────────────
  {
    slug: 'golf-scoring-explained',
    title: 'How Golf Scoring Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['start-here'],
  },
  {
    slug: 'par',
    title: 'What Is Par?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['start-here'],
  },
  {
    slug: 'birdie',
    title: 'What Is a Birdie?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'eagle',
    title: 'What Is an Eagle?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'albatross',
    title: 'What Is an Albatross?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'condor',
    title: 'What Is a Condor?',
    type: 'scoring_term',
    difficulty: 'intermediate',
    category: 'scoring',
  },
  {
    slug: 'bogey',
    title: 'What Is a Bogey?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'double-bogey',
    title: 'What Is a Double Bogey?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'hole-in-one',
    title: 'What Is a Hole-in-One?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['glossary'],
  },
  {
    slug: 'even-par',
    title: 'What Does Even Par Mean?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'under-par-scores',
    title: 'What Does -5 Mean in Golf?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'over-par-scores',
    title: 'What Does +5 Mean in Golf?',
    type: 'scoring_term',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'gross-vs-net-score',
    title: 'Gross Score vs Net Score',
    type: 'handicap_concept',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['handicaps'],
  },
  {
    slug: 'reading-a-scorecard',
    title: 'How to Read a Scorecard',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'reading-a-leaderboard',
    title: 'How to Read a Golf Leaderboard',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
    alsoIn: ['tournaments'],
  },
  {
    slug: 'stableford',
    title: 'Stableford Scoring Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'scoring',
    alsoIn: ['formats'],
  },

  // ── The Golf Course ────────────────────────────────────────────────────────
  {
    slug: 'golf-course-explained',
    title: 'Golf Course Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['start-here'],
  },
  {
    slug: 'tee-box',
    title: 'Tee Box Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'fairway',
    title: 'Fairway Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'rough',
    title: 'Rough Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'green',
    title: 'Green Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'fringe',
    title: 'Fringe Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'bunker',
    title: 'Bunker Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['penalties-and-relief'],
  },
  {
    slug: 'penalty-area',
    title: 'Penalty Area Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['penalties-and-relief'],
  },
  {
    slug: 'out-of-bounds',
    title: 'Out of Bounds Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['penalties-and-relief'],
  },
  {
    slug: 'dogleg',
    title: 'What Is a Dogleg?',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['course-design'],
  },
  {
    slug: 'par-3-hole',
    title: 'Par 3 Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'par-4-hole',
    title: 'Par 4 Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'par-5-hole',
    title: 'Par 5 Explained',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'front-nine-back-nine',
    title: 'Front Nine vs Back Nine',
    type: 'standard',
    difficulty: 'beginner',
    category: 'the-course',
  },
  {
    slug: 'signature-hole',
    title: 'What Is a Signature Hole?',
    type: 'hole',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['course-design'],
  },
  {
    slug: 'course-rating',
    title: 'Course Rating Explained',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'the-course',
    alsoIn: ['handicaps'],
  },
  {
    slug: 'slope-rating',
    title: 'Slope Rating Explained',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'the-course',
    alsoIn: ['handicaps'],
  },
  {
    slug: 'green-complex',
    title: 'Green Complexes Explained',
    type: 'hole',
    difficulty: 'intermediate',
    category: 'the-course',
    alsoIn: ['course-design'],
  },
  {
    slug: 'teeing-ground-choices',
    title: 'Which Tees Should You Play From?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'the-course',
    alsoIn: ['handicaps'],
  },

  // ── Clubs & Equipment ──────────────────────────────────────────────────────
  {
    slug: 'golf-clubs-explained',
    title: 'Golf Clubs Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
    alsoIn: ['start-here'],
  },
  {
    slug: 'driver',
    title: 'Driver Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'fairway-woods',
    title: 'Fairway Woods Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'hybrids',
    title: 'Hybrids Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'irons',
    title: 'Irons Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'wedges',
    title: 'Wedges Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'putter',
    title: 'Putter Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'driver-vs-wood',
    title: 'Driver vs Fairway Wood',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'hybrid-vs-iron',
    title: 'Hybrid vs Iron',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'iron-numbers',
    title: 'Iron Numbers Explained',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'club-loft',
    title: 'What Does Club Loft Mean?',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'club-length',
    title: 'Club Length Explained',
    type: 'club',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'shaft-flex',
    title: 'Shaft Flex Explained',
    type: 'club',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'lie-angle',
    title: 'Lie Angle Explained',
    type: 'club',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'club-bounce',
    title: 'Club Bounce Explained',
    type: 'club',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'grooves',
    title: 'Golf Club Grooves Explained',
    type: 'club',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'why-multiple-clubs',
    title: 'Why Golfers Carry Multiple Clubs',
    type: 'club',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'fourteen-club-rule',
    title: 'How Many Clubs Can You Carry?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
    alsoIn: ['rules'],
  },
  {
    slug: 'club-gapping',
    title: 'Club Gapping Explained',
    type: 'club',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
    alsoIn: ['caddies-and-yardage'],
  },
  {
    slug: 'golf-ball',
    title: 'Golf Ball Explained',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'ball-compression',
    title: 'Golf Ball Compression',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'ball-dimples',
    title: 'Why Golf Balls Have Dimples',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'ball-construction',
    title: 'Golf Ball Construction Explained',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'driver-technology',
    title: 'Driver Technology Explained',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'iron-technology',
    title: 'Iron Technology Explained',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'putter-types',
    title: 'Putter Types Explained',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'blade-vs-mallet',
    title: 'Blade vs Mallet Putter',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'clubs-and-equipment',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'shaft-materials',
    title: 'Steel vs Graphite Shafts',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },
  {
    slug: 'club-fitting',
    title: 'Club Fitting Explained',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'clubs-and-equipment',
  },

  // ── Shots & Ball Flight ────────────────────────────────────────────────────
  {
    slug: 'tee-shot',
    title: 'Tee Shot Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'approach-shot',
    title: 'Approach Shot Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'iron-shot',
    title: 'Iron Shot Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'pitch-shot',
    title: 'Pitch Shot Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'chip-shot',
    title: 'Chip Shot Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'putt',
    title: 'Putt Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'bunker-shot',
    title: 'Bunker Shot Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'flop-shot',
    title: 'Flop Shot Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'punch-shot',
    title: 'Punch Shot Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
    alsoIn: ['strategy-and-conditions'],
  },
  {
    slug: 'lay-up',
    title: 'Lay-Up Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
    alsoIn: ['strategy-and-conditions'],
  },
  {
    slug: 'recovery-shot',
    title: 'Recovery Shot Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'ball-flight-explained',
    title: 'Golf Ball Flight Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'draw',
    title: 'Draw Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'fade',
    title: 'Fade Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'hook',
    title: 'Hook Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'slice',
    title: 'Slice Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'push',
    title: 'Push Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'pull',
    title: 'Pull Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'push-fade',
    title: 'Push-Fade Explained',
    type: 'shot',
    difficulty: 'advanced',
    category: 'shots',
  },
  {
    slug: 'pull-hook',
    title: 'Pull-Hook Explained',
    type: 'shot',
    difficulty: 'advanced',
    category: 'shots',
  },
  {
    slug: 'high-vs-low-shots',
    title: 'High Shot vs Low Shot',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
    alsoIn: ['strategy-and-conditions'],
  },
  {
    slug: 'ball-spin',
    title: 'Ball Spin Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'backspin',
    title: 'Backspin Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'spin-axis',
    title: 'Spin Axis Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'shots',
    alsoIn: ['the-swing'],
  },
  {
    slug: 'why-golf-balls-curve',
    title: 'Why Golf Balls Curve',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'launch-angle',
    title: 'Launch Angle Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'shots',
    alsoIn: ['the-swing'],
  },

  // ── The Swing ──────────────────────────────────────────────────────────────
  {
    slug: 'golf-swing-explained',
    title: 'Golf Swing Explained',
    type: 'swing_element',
    difficulty: 'beginner',
    category: 'the-swing',
  },
  {
    slug: 'grip',
    title: 'Grip Explained',
    type: 'swing_element',
    difficulty: 'beginner',
    category: 'the-swing',
  },
  {
    slug: 'stance',
    title: 'Stance Explained',
    type: 'swing_element',
    difficulty: 'beginner',
    category: 'the-swing',
  },
  {
    slug: 'alignment',
    title: 'Alignment Explained',
    type: 'swing_element',
    difficulty: 'beginner',
    category: 'the-swing',
  },
  {
    slug: 'address-position',
    title: 'Address Position Explained',
    type: 'swing_element',
    difficulty: 'beginner',
    category: 'the-swing',
  },
  {
    slug: 'backswing',
    title: 'Backswing Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'downswing',
    title: 'Downswing Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'impact',
    title: 'Impact Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'follow-through',
    title: 'Follow-Through Explained',
    type: 'swing_element',
    difficulty: 'beginner',
    category: 'the-swing',
  },
  {
    slug: 'clubface',
    title: 'Clubface Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'face-angle',
    title: 'Face Angle Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'swing-path',
    title: 'Swing Path Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'club-path',
    title: 'Club Path Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'face-to-path',
    title: 'Face-to-Path Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'angle-of-attack',
    title: 'Angle of Attack Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'dynamic-loft',
    title: 'Dynamic Loft Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'clubhead-speed',
    title: 'Clubhead Speed Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'ball-speed',
    title: 'Ball Speed Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'smash-factor',
    title: 'Smash Factor Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'spin-rate',
    title: 'Spin Rate Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'tempo',
    title: 'Tempo Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'the-swing',
  },
  {
    slug: 'gear-effect',
    title: 'Gear Effect Explained',
    type: 'swing_element',
    difficulty: 'advanced',
    category: 'the-swing',
    alsoIn: ['clubs-and-equipment'],
  },
  {
    slug: 'carry-optimisation',
    title: 'Carry Optimisation Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'the-swing',
  },
  {
    slug: 'launch-monitor-data',
    title: 'Launch Monitor Data Explained',
    type: 'technology',
    difficulty: 'advanced',
    category: 'the-swing',
    alsoIn: ['statistics'],
  },

  // ── Putting & Short Game ───────────────────────────────────────────────────
  {
    slug: 'putting-explained',
    title: 'Putting Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'reading-a-green',
    title: 'How to Read a Green',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'green-speed',
    title: 'Green Speed Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
    alsoIn: ['strategy-and-conditions'],
  },
  {
    slug: 'putting-line',
    title: 'Putting Line Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'break',
    title: 'Break Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'uphill-vs-downhill-putts',
    title: 'Uphill vs Downhill Putts',
    type: 'standard',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'lag-putting',
    title: 'Lag Putting Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'short-putts',
    title: 'Short Putts Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'long-putts',
    title: 'Long Putts Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'putting-stroke',
    title: 'Putting Stroke Explained',
    type: 'swing_element',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'aimpoint-vs-pace',
    title: 'Aim Point vs Pace',
    type: 'standard',
    difficulty: 'advanced',
    category: 'putting-and-short-game',
  },
  {
    slug: 'why-putts-break',
    title: 'Why Putts Break',
    type: 'standard',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'grain',
    title: 'Grain Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'short-game-explained',
    title: 'Short Game Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'chip-vs-pitch',
    title: 'Chip vs Pitch',
    type: 'shot',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
  },
  {
    slug: 'bump-and-run',
    title: 'Bump-and-Run Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'bunker-play',
    title: 'Bunker Play Explained',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'greenside-rough',
    title: 'Greenside Rough Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'tight-lie',
    title: 'Tight Lie Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
  },
  {
    slug: 'lob-wedge',
    title: 'Lob Wedge Explained',
    type: 'club',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
    alsoIn: ['clubs-and-equipment'],
  },
  {
    slug: 'spin-around-the-green',
    title: 'Spin Around the Green',
    type: 'shot',
    difficulty: 'advanced',
    category: 'putting-and-short-game',
  },
  {
    slug: 'using-bounce',
    title: 'Using Bounce Explained',
    type: 'shot',
    difficulty: 'advanced',
    category: 'putting-and-short-game',
  },
  {
    slug: 'up-and-down',
    title: 'Up-and-Down Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'putting-and-short-game',
    alsoIn: ['statistics'],
  },
  {
    slug: 'scrambling',
    title: 'Scrambling Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
    alsoIn: ['statistics'],
  },
  {
    slug: 'short-siding',
    title: 'Short-Siding Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'putting-and-short-game',
    alsoIn: ['strategy-and-conditions'],
  },

  // ── Handicaps ──────────────────────────────────────────────────────────────
  {
    slug: 'golf-handicap-explained',
    title: 'Golf Handicap Explained',
    type: 'handicap_concept',
    difficulty: 'beginner',
    category: 'handicaps',
  },
  {
    slug: 'handicap-index',
    title: 'Handicap Index Explained',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'handicaps',
  },
  {
    slug: 'why-golf-uses-handicaps',
    title: 'Why Golf Uses Handicaps',
    type: 'handicap_concept',
    difficulty: 'beginner',
    category: 'handicaps',
  },
  {
    slug: 'how-a-handicap-is-calculated',
    title: 'How a Handicap Is Calculated',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'handicaps',
  },
  {
    slug: 'course-handicap',
    title: 'Course Handicap Explained',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'handicaps',
  },
  {
    slug: 'playing-handicap',
    title: 'Playing Handicap Explained',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'handicaps',
  },
  {
    slug: 'score-differential',
    title: 'Handicap Differential Explained',
    type: 'handicap_concept',
    difficulty: 'advanced',
    category: 'handicaps',
  },
  {
    slug: 'scratch-golfer',
    title: 'Scratch Golfer Explained',
    type: 'handicap_concept',
    difficulty: 'beginner',
    category: 'handicaps',
  },
  {
    slug: 'bogey-golfer',
    title: 'Bogey Golfer Explained',
    type: 'handicap_concept',
    difficulty: 'beginner',
    category: 'handicaps',
  },
  {
    slug: 'what-a-10-handicap-means',
    title: 'What Does a 10 Handicap Mean?',
    type: 'handicap_concept',
    difficulty: 'beginner',
    category: 'handicaps',
  },
  {
    slug: 'different-handicaps-competing',
    title: 'Can Players With Different Handicaps Compete?',
    type: 'handicap_concept',
    difficulty: 'beginner',
    category: 'handicaps',
  },
  {
    slug: 'world-handicap-system',
    title: 'World Handicap System Explained',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'handicaps',
  },
  {
    slug: 'stroke-index',
    title: 'Stroke Index Explained',
    type: 'handicap_concept',
    difficulty: 'intermediate',
    category: 'handicaps',
    alsoIn: ['scoring'],
  },
  {
    slug: 'net-double-bogey',
    title: 'Net Double Bogey Explained',
    type: 'handicap_concept',
    difficulty: 'advanced',
    category: 'handicaps',
  },
  {
    slug: 'playing-conditions-calculation',
    title: 'Playing Conditions Calculation Explained',
    type: 'handicap_concept',
    difficulty: 'advanced',
    category: 'handicaps',
  },

  // ── Formats ────────────────────────────────────────────────────────────────
  {
    slug: 'stroke-play',
    title: 'Stroke Play Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'how-stroke-play-scoring-works',
    title: 'How Stroke Play Scoring Works',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
    alsoIn: ['scoring'],
  },
  {
    slug: 'gross-stroke-play',
    title: 'Gross Stroke Play',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'net-stroke-play',
    title: 'Net Stroke Play',
    type: 'format',
    difficulty: 'intermediate',
    category: 'formats',
    alsoIn: ['handicaps'],
  },
  {
    slug: 'ties-in-stroke-play',
    title: 'Ties in Stroke Play',
    type: 'format',
    difficulty: 'intermediate',
    category: 'formats',
  },
  {
    slug: 'why-one-bad-hole-matters',
    title: 'Why One Bad Hole Matters So Much',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'match-play',
    title: 'Match Play Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'stroke-play-vs-match-play',
    title: 'Stroke Play vs Match Play',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'one-up',
    title: 'What Does 1 Up Mean?',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'two-and-one',
    title: 'What Does 2 & 1 Mean?',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'halved-hole',
    title: 'Halved Hole Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'dormie',
    title: 'Dormie Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'formats',
    alsoIn: ['glossary'],
  },
  {
    slug: 'conceded-putt',
    title: 'Conceded Putt Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'formats',
    alsoIn: ['rules'],
  },
  {
    slug: 'match-play-strategy',
    title: 'Match Play Strategy',
    type: 'format',
    difficulty: 'intermediate',
    category: 'formats',
    alsoIn: ['strategy-and-conditions'],
  },
  {
    slug: 'why-match-play-changes-risk',
    title: 'Why Match Play Changes Risk-Taking',
    type: 'format',
    difficulty: 'intermediate',
    category: 'formats',
    alsoIn: ['strategy-and-conditions'],
  },
  {
    slug: 'golf-team-formats',
    title: 'Golf Team Formats Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'four-ball',
    title: 'Four-Ball Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'foursomes',
    title: 'Foursomes Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'alternate-shot',
    title: 'Alternate Shot Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'scramble',
    title: 'Scramble Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'texas-scramble',
    title: 'Texas Scramble Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'best-ball',
    title: 'Best Ball Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
  },
  {
    slug: 'four-ball-vs-best-ball',
    title: 'Four-Ball vs Best Ball',
    type: 'format',
    difficulty: 'intermediate',
    category: 'formats',
  },
  {
    slug: 'ryder-cup-format',
    title: 'Ryder Cup Format Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
    alsoIn: ['majors-and-tours'],
  },
  {
    slug: 'presidents-cup-format',
    title: 'Presidents Cup Format Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
    alsoIn: ['majors-and-tours'],
  },
  {
    slug: 'solheim-cup-format',
    title: 'Solheim Cup Format Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'formats',
    alsoIn: ['majors-and-tours'],
  },

  // ── Tournaments ────────────────────────────────────────────────────────────
  {
    slug: 'four-round-tournament',
    title: 'Four-Round Tournament Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'the-cut',
    title: 'What Is the Cut?',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'cut-line',
    title: 'Cut Line Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'playoff',
    title: 'What Is a Playoff?',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'sudden-death-playoff',
    title: 'Sudden-Death Playoff Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'aggregate-playoff',
    title: 'Aggregate Playoff Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'tee-times',
    title: 'Tee Times Explained',
    type: 'procedure',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'pairings',
    title: 'Pairings Explained',
    type: 'procedure',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'groups-and-threesomes',
    title: 'Groups and Threesomes Explained',
    type: 'procedure',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'featured-groups',
    title: 'Featured Groups Explained',
    type: 'procedure',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'shotgun-start',
    title: 'Shotgun Start Explained',
    type: 'procedure',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'multi-course-events',
    title: 'Multi-Course Events Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'pro-am',
    title: 'Pro-Am Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'monday-qualifying',
    title: 'Monday Qualifying Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'tournaments',
    alsoIn: ['majors-and-tours'],
  },
  {
    slug: 'sponsor-exemption',
    title: 'Sponsor Exemption Explained',
    type: 'procedure',
    difficulty: 'intermediate',
    category: 'tournaments',
    alsoIn: ['majors-and-tours'],
  },

  // ── Majors & Tours ─────────────────────────────────────────────────────────
  {
    slug: 'golf-majors-explained',
    title: 'Golf Majors Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'majors-and-tours',
    alsoIn: ['start-here'],
  },
  {
    slug: 'masters-tournament',
    title: 'Masters Tournament Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'pga-championship',
    title: 'PGA Championship Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'us-open-golf',
    title: 'U.S. Open Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'the-open-championship',
    title: 'The Open Championship Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'womens-majors',
    title: "Women's Majors Explained",
    type: 'format',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'why-majors-matter',
    title: 'Why Majors Matter',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'major-vs-regular-event',
    title: 'Major vs Regular Tour Event',
    type: 'format',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'career-grand-slam',
    title: 'Career Grand Slam Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'calendar-grand-slam',
    title: 'Calendar Grand Slam Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'why-all-four-majors-is-hard',
    title: 'Why Winning All Four Majors Is Difficult',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'majors-and-tours',
  },
  {
    slug: 'golf-tours-explained',
    title: 'Golf Tours Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
    alsoIn: ['start-here'],
  },
  {
    slug: 'pga-tour',
    title: 'PGA Tour Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'dp-world-tour',
    title: 'DP World Tour Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'lpga-tour',
    title: 'LPGA Tour Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'ladies-european-tour',
    title: 'Ladies European Tour Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'developmental-tours',
    title: 'Developmental Tours Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'majors-and-tours',
  },
  {
    slug: 'reaching-the-pga-tour',
    title: 'How Players Reach the PGA Tour',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'majors-and-tours',
  },
  {
    slug: 'reaching-the-lpga-tour',
    title: 'How Players Reach the LPGA Tour',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'majors-and-tours',
  },
  {
    slug: 'tour-membership',
    title: 'Tour Membership Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'majors-and-tours',
  },
  {
    slug: 'tour-card',
    title: 'Tour Cards Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },
  {
    slug: 'exempt-status',
    title: 'Exempt Status Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'majors-and-tours',
  },
  {
    slug: 'qualifying-school',
    title: 'Qualifying School Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'majors-and-tours',
  },
  {
    slug: 'sponsor-invitations',
    title: 'Sponsor Invitations Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'majors-and-tours',
  },

  // ── World Rankings ─────────────────────────────────────────────────────────
  {
    slug: 'golf-world-rankings',
    title: 'Golf World Rankings Explained',
    type: 'ranking_concept',
    difficulty: 'beginner',
    category: 'world-rankings',
  },
  {
    slug: 'how-golf-rankings-work',
    title: 'How Golf Rankings Work',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'ranking-points',
    title: 'Ranking Points Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'field-strength',
    title: 'Why Tournament Strength Matters',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'ranking-period',
    title: 'Ranking Period Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'becoming-world-number-one',
    title: 'How Players Become World No. 1',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'rankings-and-major-qualification',
    title: 'How Rankings Affect Major Qualification',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'mens-vs-womens-rankings',
    title: "Men's vs Women's Ranking Systems",
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'ranking-vs-tour-standings',
    title: 'World Ranking vs Tour Standings',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },
  {
    slug: 'fedexcup',
    title: 'Ranking vs FedExCup Season Points',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'world-rankings',
  },

  // ── Rules ──────────────────────────────────────────────────────────────────
  {
    slug: 'rules-of-golf',
    title: 'Rules of Golf Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
  },
  {
    slug: 'ball-in-play',
    title: 'When Is the Ball in Play?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
  },
  {
    slug: 'play-it-as-it-lies',
    title: 'Playing the Ball as It Lies',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
  },
  {
    slug: 'identifying-your-ball',
    title: 'Identifying Your Golf Ball',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
  },
  {
    slug: 'lost-ball',
    title: 'Lost Ball Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
    alsoIn: ['penalties-and-relief'],
  },
  {
    slug: 'provisional-ball',
    title: 'Provisional Ball Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'rules',
  },
  {
    slug: 'unplayable-ball',
    title: 'Unplayable Ball Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'rules',
    alsoIn: ['penalties-and-relief'],
  },
  {
    slug: 'embedded-ball',
    title: 'Embedded Ball Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'rules',
    alsoIn: ['penalties-and-relief'],
  },
  {
    slug: 'ball-movement',
    title: 'Ball Movement Rules',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'rules',
  },
  {
    slug: 'wrong-ball',
    title: 'Wrong Ball Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'rules',
  },
  {
    slug: 'wrong-place',
    title: 'Wrong Place Explained',
    type: 'rule',
    difficulty: 'advanced',
    category: 'rules',
  },
  {
    slug: 'advice-rules',
    title: 'Advice Rules Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'rules',
    alsoIn: ['caddies-and-yardage'],
  },
  {
    slug: 'pace-of-play-rules',
    title: 'Pace of Play Rules',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
    alsoIn: ['etiquette'],
  },
  {
    slug: 'flagstick-rules',
    title: 'Flagstick Rules Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
  },
  {
    slug: 'marking-and-lifting',
    title: 'Marking, Lifting and Replacing Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'rules',
  },

  // ── Penalties & Relief ─────────────────────────────────────────────────────
  {
    slug: 'golf-penalties-explained',
    title: 'Golf Penalties Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
  },
  {
    slug: 'penalty-stroke',
    title: 'Penalty Stroke Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
  },
  {
    slug: 'free-relief',
    title: 'Free Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'penalty-relief',
    title: 'Penalty Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'penalty-area-relief',
    title: 'Penalty Area Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'cart-path-relief',
    title: 'Cart Path Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'temporary-water',
    title: 'Temporary Water Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'ground-under-repair',
    title: 'Ground Under Repair Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'unplayable-ball-relief',
    title: 'Unplayable Ball Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'lost-ball-penalty',
    title: 'Lost Ball Penalty Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
  },
  {
    slug: 'out-of-bounds-penalty',
    title: 'Out of Bounds Penalty Explained',
    type: 'penalty',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
  },
  {
    slug: 'drop-procedure',
    title: 'Drop Procedure Explained',
    type: 'procedure',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
  },
  {
    slug: 'relief-area',
    title: 'Relief Area Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'nearest-point-of-relief',
    title: 'Nearest Point of Complete Relief',
    type: 'rule',
    difficulty: 'advanced',
    category: 'penalties-and-relief',
  },
  {
    slug: 'stroke-and-distance',
    title: 'Stroke-and-Distance Explained',
    type: 'penalty',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'back-on-the-line-relief',
    title: 'Back-on-the-Line Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'bunker-rules',
    title: 'Bunker Rules Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
    alsoIn: ['the-course'],
  },
  {
    slug: 'what-you-can-do-in-a-bunker',
    title: 'What Can You Do in a Bunker?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
  },
  {
    slug: 'grounding-the-club',
    title: 'Grounding the Club Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'penalty-areas-explained',
    title: 'Penalty Areas Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
  },
  {
    slug: 'red-penalty-area',
    title: 'Red Penalty Area Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'yellow-penalty-area',
    title: 'Yellow Penalty Area Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'bunker-relief',
    title: 'Bunker Relief Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },
  {
    slug: 'water-hazard-terminology',
    title: 'Water Hazard Terminology Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'penalties-and-relief',
    alsoIn: ['glossary'],
  },
  {
    slug: 'playing-from-a-penalty-area',
    title: 'Playing From a Penalty Area',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'penalties-and-relief',
  },

  // ── Strategy & Conditions ──────────────────────────────────────────────────
  {
    slug: 'course-management',
    title: 'Golf Course Management Explained',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'risk-vs-reward',
    title: 'Risk vs Reward',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'club-selection-strategy',
    title: 'Club Selection Strategy',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'playing-for-position',
    title: 'Playing for Position',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'lay-up-strategy',
    title: 'Lay-Up Strategy',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'when-to-attack-the-green',
    title: 'When to Attack the Green',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'playing-away-from-trouble',
    title: 'Playing Away From Trouble',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'tee-shot-strategy',
    title: 'Tee Shot Strategy',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'approach-shot-strategy',
    title: 'Approach Shot Strategy',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'miss-patterns',
    title: 'Miss Patterns Explained',
    type: 'strategy_concept',
    difficulty: 'advanced',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'playing-to-your-strengths',
    title: 'Playing to Your Strengths',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'why-pros-dont-aim-at-the-flag',
    title: "Why Pros Don't Always Aim at the Flag",
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'course-conditions',
    title: 'Course Conditions Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'firm-vs-soft-courses',
    title: 'Firm vs Soft Courses',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'fast-vs-slow-greens',
    title: 'Fast vs Slow Greens',
    type: 'standard',
    difficulty: 'beginner',
    category: 'strategy-and-conditions',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'rough-length',
    title: 'Rough Length and Difficulty',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'green-firmness',
    title: 'Green Firmness Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'wind-effects',
    title: 'How Wind Affects Golf',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'headwind',
    title: 'Headwind Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'tailwind',
    title: 'Tailwind Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'crosswind',
    title: 'Crosswind Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'why-wind-changes-ball-flight',
    title: 'Why Wind Changes Ball Flight',
    type: 'standard',
    difficulty: 'advanced',
    category: 'strategy-and-conditions',
    alsoIn: ['shots'],
  },
  {
    slug: 'club-selection-in-wind',
    title: 'Club Selection in Wind',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'playing-low-shots',
    title: 'Playing Low Shots',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
    alsoIn: ['shots'],
  },
  {
    slug: 'wind-and-spin',
    title: 'Wind and Spin',
    type: 'standard',
    difficulty: 'advanced',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'gusting-wind-strategy',
    title: 'Gusting Wind Strategy',
    type: 'strategy_concept',
    difficulty: 'advanced',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'rain-effects',
    title: 'Rain Effects Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'heat-and-cold',
    title: 'Temperature Effects Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'altitude-effects',
    title: 'Altitude Effects Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'elevation-changes',
    title: 'Elevation Changes Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
    alsoIn: ['caddies-and-yardage'],
  },
  {
    slug: 'morning-vs-afternoon',
    title: 'Morning vs Afternoon Conditions',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
    alsoIn: ['tournaments'],
  },
  {
    slug: 'links-golf',
    title: 'Links Golf Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'strategy-and-conditions',
    alsoIn: ['course-design'],
  },
  {
    slug: 'what-makes-a-links-course',
    title: 'What Makes a Links Course?',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
    alsoIn: ['course-design'],
  },
  {
    slug: 'links-vs-parkland',
    title: 'Links vs Parkland',
    type: 'standard',
    difficulty: 'beginner',
    category: 'strategy-and-conditions',
    alsoIn: ['course-design'],
  },
  {
    slug: 'firm-turf',
    title: 'Firm Turf Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'pot-bunkers',
    title: 'Pot Bunkers Explained',
    type: 'hole',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
    alsoIn: ['course-design'],
  },
  {
    slug: 'ground-game',
    title: 'Ground Game Explained',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
  },
  {
    slug: 'why-the-open-plays-differently',
    title: 'Why The Open Plays Differently',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'strategy-and-conditions',
    alsoIn: ['majors-and-tours'],
  },
  {
    slug: 'links-golf-strategy',
    title: 'Links Golf Strategy',
    type: 'strategy_concept',
    difficulty: 'advanced',
    category: 'strategy-and-conditions',
  },

  // ── Course Design ──────────────────────────────────────────────────────────
  {
    slug: 'course-design-explained',
    title: 'Golf Course Design Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'course-design',
  },
  {
    slug: 'strategic-design',
    title: 'Strategic Golf Course Design',
    type: 'standard',
    difficulty: 'advanced',
    category: 'course-design',
  },
  {
    slug: 'penal-design',
    title: 'Penal Design Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'course-design',
  },
  {
    slug: 'heroic-design',
    title: 'Heroic Design Explained',
    type: 'standard',
    difficulty: 'advanced',
    category: 'course-design',
  },
  {
    slug: 'bunker-placement',
    title: 'Bunker Placement Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'course-design',
  },
  {
    slug: 'false-front',
    title: 'False Front Explained',
    type: 'hole',
    difficulty: 'intermediate',
    category: 'course-design',
  },
  {
    slug: 'run-off-area',
    title: 'Run-Off Area Explained',
    type: 'hole',
    difficulty: 'intermediate',
    category: 'course-design',
  },
  {
    slug: 'risk-reward-holes',
    title: 'Risk-Reward Holes Explained',
    type: 'hole',
    difficulty: 'intermediate',
    category: 'course-design',
  },
  {
    slug: 'links-course-design',
    title: 'Links Course Design',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'course-design',
  },
  {
    slug: 'parkland-course-design',
    title: 'Parkland Course Design',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'course-design',
  },
  {
    slug: 'why-architecture-matters',
    title: 'Why Course Architecture Matters',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'course-design',
  },

  // ── Caddies & Yardage ──────────────────────────────────────────────────────
  {
    slug: 'what-a-caddie-does',
    title: 'What Does a Caddie Do?',
    type: 'standard',
    difficulty: 'beginner',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'professional-caddies',
    title: 'Professional Golf Caddies Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'yardage-books',
    title: 'Yardage Books Explained',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'caddie-green-reading',
    title: 'Green Reading by Caddies',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
    alsoIn: ['putting-and-short-game'],
  },
  {
    slug: 'caddie-club-selection',
    title: 'Club Selection Help',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'caddie-communication',
    title: 'Caddie-Player Communication',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'caddie-rules',
    title: 'Caddie Rules Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
    alsoIn: ['rules'],
  },
  {
    slug: 'caddies-at-majors',
    title: 'Why Caddies Matter at Major Championships',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'golf-distance-explained',
    title: 'Golf Distance Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'carry-vs-total-distance',
    title: 'Carry Distance vs Total Distance',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'yardage',
    title: 'Yardage Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'front-middle-back-yardages',
    title: 'Distance to Front, Middle and Back',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'elevation-adjustments',
    title: 'Elevation Adjustments Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'wind-adjustments',
    title: 'Wind Adjustments Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'temperature-and-distance',
    title: 'Temperature and Distance',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'altitude-and-distance',
    title: 'Why Golf Balls Travel Further at Altitude',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },
  {
    slug: 'how-players-choose-a-club',
    title: 'How Players Choose a Club',
    type: 'strategy_concept',
    difficulty: 'intermediate',
    category: 'caddies-and-yardage',
  },

  // ── Golf Statistics ────────────────────────────────────────────────────────
  {
    slug: 'golf-statistics-explained',
    title: 'Golf Statistics Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'driving-distance',
    title: 'Driving Distance Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'driving-accuracy',
    title: 'Driving Accuracy Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'greens-in-regulation',
    title: 'Greens in Regulation Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'scrambling-percentage',
    title: 'Scrambling Percentage Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'sand-save-percentage',
    title: 'Sand Save Percentage Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'putts-per-round',
    title: 'Putts Per Round Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'putting-average',
    title: 'Putting Average Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'birdie-average',
    title: 'Birdie Average Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'scoring-average',
    title: 'Scoring Average Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'fairways-hit',
    title: 'Fairways Hit Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'proximity-to-hole',
    title: 'Proximity to the Hole Explained',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'why-traditional-stats-mislead',
    title: 'Why Traditional Golf Stats Can Be Misleading',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
    alsoIn: ['strokes-gained'],
  },

  // ── Strokes Gained ─────────────────────────────────────────────────────────
  {
    slug: 'strokes-gained',
    title: 'Strokes Gained Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'strokes-gained-off-the-tee',
    title: 'Strokes Gained: Off the Tee',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'strokes-gained-approach',
    title: 'Strokes Gained: Approach',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'strokes-gained-around-the-green',
    title: 'Strokes Gained: Around the Green',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'strokes-gained-putting',
    title: 'Strokes Gained: Putting',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'strokes-gained-tee-to-green',
    title: 'Strokes Gained: Tee to Green',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'strokes-gained-total',
    title: 'Strokes Gained: Total',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'how-strokes-gained-is-calculated',
    title: 'How Strokes Gained Is Calculated',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'why-strokes-gained-is-better',
    title: 'Why Strokes Gained Beats Basic Stats',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'reading-a-strokes-gained-table',
    title: 'How to Read a Strokes Gained Table',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },
  {
    slug: 'baseline-expected-strokes',
    title: 'Expected Strokes Baselines Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'strokes-gained',
  },

  // ── Advanced Analysis ──────────────────────────────────────────────────────
  {
    slug: 'expected-score',
    title: 'Expected Score Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'shot-value',
    title: 'Shot Value Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'strokes-gained-vs-field',
    title: 'Strokes Gained vs Field',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'course-adjusted-performance',
    title: 'Course-Adjusted Performance',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'field-strength-adjustments',
    title: 'Field Strength Adjustments',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'distance-vs-accuracy',
    title: 'Driving Distance vs Accuracy Trade-Off',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'approach-proximity-analysis',
    title: 'Approach Proximity Analysis',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'putting-variance',
    title: 'Putting Performance Variance',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'expected-putting',
    title: 'Expected Putting Performance',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'tournament-form-analysis',
    title: 'Tournament Form Analysis',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'course-fit',
    title: 'Course Fit Explained',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'course-history-vs-form',
    title: 'Course History vs Current Form',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'wind-adjusted-performance',
    title: 'Wind-Adjusted Performance',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'major-championship-performance',
    title: 'Major Championship Performance',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },
  {
    slug: 'player-skill-profiles',
    title: 'Player Skill Profiles',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced-analysis',
  },

  // ── Etiquette & Safety ─────────────────────────────────────────────────────
  {
    slug: 'golf-etiquette',
    title: 'Golf Etiquette Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'pace-of-play',
    title: 'Pace of Play Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'ready-golf',
    title: 'Ready Golf Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'repairing-pitch-marks',
    title: 'Repairing Pitch Marks',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'repairing-divots',
    title: 'Repairing Divots',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'raking-bunkers',
    title: 'Raking Bunkers',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'keeping-quiet',
    title: 'Keeping Quiet During Shots',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'where-to-stand',
    title: 'Where to Stand',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'honours-on-the-tee',
    title: 'Honours on the Tee',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
    alsoIn: ['rules'],
  },
  {
    slug: 'dress-codes',
    title: 'Golf Dress Codes Explained',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'calling-fore',
    title: 'Calling Fore',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },
  {
    slug: 'course-safety',
    title: 'Safety on the Golf Course',
    type: 'standard',
    difficulty: 'beginner',
    category: 'etiquette',
  },

  // ── Glossary ───────────────────────────────────────────────────────────────
  {
    slug: 'ace',
    title: 'Ace',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'address',
    title: 'Address',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'approach',
    title: 'Approach',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'caddie',
    title: 'Caddie',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'carry',
    title: 'Carry',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'chip',
    title: 'Chip',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'cut-term',
    title: 'Cut',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'divot',
    title: 'Divot',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'flagstick',
    title: 'Flagstick',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'fore',
    title: 'Fore',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'handicap-term',
    title: 'Handicap',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'hazard',
    title: 'Hazard',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'lie',
    title: 'Lie',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'loft',
    title: 'Loft',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'stroke',
    title: 'Stroke',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'tee',
    title: 'Tee',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'wedge-term',
    title: 'Wedge',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'mulligan',
    title: 'Mulligan',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'gimme',
    title: 'Gimme',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'snowman',
    title: 'Snowman',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'sandbagger',
    title: 'Sandbagger',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'shank',
    title: 'Shank',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'duff',
    title: 'Duff',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'whiff',
    title: 'Whiff',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'fried-egg',
    title: 'Fried Egg',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'waggle',
    title: 'Waggle',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'texas-wedge',
    title: 'Texas Wedge',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'worm-burner',
    title: 'Worm Burner',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'nineteenth-hole',
    title: 'Nineteenth Hole',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'albatross-term',
    title: 'Double Eagle',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
];
