import type { SourceSeed } from './football-overview';
import type { ExplainerSeed } from './explainer-types';
import { standard, technique } from './mma-explainer-helpers';

/**
 * MMA explainers: Wrestling (Category 6) and Clinch (Category 7).
 *
 * Follows the pattern set by `mma-explainers.ts` (Phase 1): the brief's own
 * template per entry, `standard()` for concepts and overviews, `technique()`
 * for discrete, nameable moves with a recognition/mechanics/risk/counter
 * shape. Written for spectator recognition throughout, not as an
 * instructional manual: nothing here is phrased as "do X to your opponent",
 * only as "this is what it looks like and why a fighter attempts it".
 *
 * Cross-category duplication note: **Underhook** and **Overhook / Whizzer**
 * are the same grip concept whether a fighter is using it to control a
 * wrestling exchange or to fight for position in the clinch, and the
 * taxonomy rule for this library is that a concept is one row regardless of
 * how many categories reference it (see `explainer-types.ts`'s note on
 * `alsoIn`). Both are written once here, under `wrestling`, each carrying
 * `alsoIn: ['clinch']`, rather than being duplicated as a second row under
 * `clinch`. A future editor scanning `clinch`'s own explainer list should
 * expect to find these two only via `alsoIn`, not as slugs owned by that
 * category. The same one-row-many-categories approach is used for Chain
 * Wrestling (owned here, `alsoIn: ['advanced-concepts']`), Mat Return and
 * Wrestling Against the Cage (owned here, `alsoIn: ['cage-wrestling']`), and
 * Cage Clinch and Wall Wrestling (owned under `clinch`, `alsoIn:
 * ['cage-wrestling']`).
 *
 * Potential overlap flagged for reconciliation: "Wall Wrestling" is written
 * here, in full, under `clinch`, because this file's brief listed it there.
 * The brief for a separate Category 12 (Cage Wrestling) pass may also list
 * "Wall Wrestling" as one of its own items; if so, that pass should reference
 * this slug via `alsoIn` rather than write a second `wall-wrestling` row.
 */

export const MMA_WRESTLING_CLINCH_SOURCES: SourceSeed[] = [
  {
    key: 'wp-wrestling',
    provider: 'wikipedia',
    title: 'Wrestling',
    url: 'https://en.wikipedia.org/wiki/Wrestling',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-takedown',
    provider: 'wikipedia',
    title: 'Takedown (grappling)',
    url: 'https://en.wikipedia.org/wiki/Takedown_(grappling)',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-single-leg',
    provider: 'wikipedia',
    title: 'Single-leg takedown',
    url: 'https://en.wikipedia.org/wiki/Single-leg_takedown',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-double-leg',
    provider: 'wikipedia',
    title: 'Double-leg takedown',
    url: 'https://en.wikipedia.org/wiki/Double-leg_takedown',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-throw',
    provider: 'wikipedia',
    title: 'Throw (grappling)',
    url: 'https://en.wikipedia.org/wiki/Throw_(grappling)',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-hip-throw',
    provider: 'wikipedia',
    title: 'Hip throw',
    url: 'https://en.wikipedia.org/wiki/Hip_throw',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-sweep-wrestling',
    provider: 'wikipedia',
    title: 'Sweep (grappling)',
    url: 'https://en.wikipedia.org/wiki/Sweep_(grappling)',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-sprawl',
    provider: 'wikipedia',
    title: 'Sprawl (wrestling)',
    url: 'https://en.wikipedia.org/wiki/Sprawl_(wrestling)',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-clinch-fighting',
    provider: 'wikipedia',
    title: 'Clinch fighting',
    url: 'https://en.wikipedia.org/wiki/Clinch_fighting',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-collar-tie',
    provider: 'wikipedia',
    title: 'Collar tie',
    url: 'https://en.wikipedia.org/wiki/Collar_tie',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-underhook',
    provider: 'wikipedia',
    title: 'Underhook',
    url: 'https://en.wikipedia.org/wiki/Underhook',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-muay-thai-clinch',
    provider: 'wikipedia',
    title: 'Muay Thai',
    url: 'https://en.wikipedia.org/wiki/Muay_Thai#Clinching',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-dirty-boxing',
    provider: 'wikipedia',
    title: 'Dirty boxing',
    url: 'https://en.wikipedia.org/wiki/Dirty_boxing',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-mma-clinch',
    provider: 'wikipedia',
    title: 'Mixed martial arts',
    url: 'https://en.wikipedia.org/wiki/Mixed_martial_arts#Clinch_fighting',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-freestyle-wrestling',
    provider: 'wikipedia',
    title: 'Freestyle wrestling',
    url: 'https://en.wikipedia.org/wiki/Freestyle_wrestling',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wp-folkstyle-wrestling',
    provider: 'wikipedia',
    title: 'Folkstyle wrestling',
    url: 'https://en.wikipedia.org/wiki/Folkstyle_wrestling',
    license: 'CC BY-SA 4.0',
  },
  {
    key: 'wd-clinch-fighting',
    provider: 'wikidata',
    title: 'Clinch fighting',
    url: 'https://www.wikidata.org/wiki/Q1548858',
    license: 'CC0 1.0',
  },
];

// ─── Wrestling ──────────────────────────────────────────────────────────────

export const MMA_WRESTLING_CLINCH_EXPLAINERS: ExplainerSeed[] = [
  standard({
    slug: 'mma-wrestling-explained',
    title: 'MMA Wrestling Explained',
    category: 'wrestling',
    aliases: ['mma wrestling', 'wrestling in mma', 'what is mma wrestling'],
    summary:
      'The art of taking a fight to the ground on your own terms, and keeping it there or off it as you choose.',
    isFeatured: true,
    difficulty: 'beginner',
    readMinutes: 4,
    sourceKeys: [
      { key: 'wp-wrestling' },
      { key: 'wp-freestyle-wrestling' },
      { key: 'wp-folkstyle-wrestling' },
    ],
    explanation: `**Wrestling**, in an MMA context, is the set of skills built around taking an opponent to the ground (or preventing them from being taken down), and around controlling position once there. It draws heavily on amateur wrestling styles, chiefly freestyle and folkstyle, adapted for a sport that also allows striking, submissions and a cage or ring wall to wrestle against.

A fighter with a strong wrestling background is often able to dictate where a fight is fought: taking it to the ground when that suits them, or using the same skills in reverse to keep a fight standing by stopping an opponent's own takedown attempts.`,
    howItWorks: `Wrestling in MMA covers three broad jobs: getting a fight to the ground (takedowns), keeping it there once it arrives (control and mat return), and stopping the same thing from happening to you (takedown defence, including the sprawl). Unlike a pure wrestling match, an MMA wrestling exchange also has to account for strikes landing during the attempt, and for a cage or ring wall a fighter can use to their advantage rather than simply being pushed out of bounds.`,
    example: `A fighter shoots for a double-leg takedown early in round one. The attempt is stuffed, and both fighters scramble briefly before resetting at range. Later in the round, the same fighter changes the timing, closes distance behind a jab, and this time drives through to complete the takedown, landing in the other fighter's guard. The skill on display in both moments, one failed, one successful, is the same wrestling.`,
    whyItMatters: `Wrestling is widely regarded as one of the sport's most valuable base disciplines precisely because it lets a fighter choose where a fight takes place: a strong wrestler with a weaker ground game can still use takedowns purely to disrupt a dangerous striker, while a strong wrestler with a strong ground game can use the same skill to set up a finish.`,
    misunderstandings: `A common one: assuming "wrestling" in MMA means the same thing as the ground game generally, including submissions and ground-and-pound. Wrestling proper is about getting to the ground (or preventing it) and controlling position there; what a fighter does once dominant position is secured, submissions, strikes, is covered separately, in the Ground Positions and Submissions categories.`,
    takeaways: `MMA wrestling is about controlling where a fight happens: taking it down, keeping it down, and stopping the same being done to you. It is a base discipline the rest of a fighter's ground game builds on top of.`,
    related: [
      'striking-vs-grappling',
      'takedown-explained',
      'takedown-defense',
      'mma-positions-explained',
      'wrestling-against-the-cage',
    ],
  }),

  technique({
    slug: 'takedown-explained',
    title: 'Takedown Explained',
    category: 'wrestling',
    aliases: ['takedown', 'what is a takedown in mma', 'takedown definition'],
    summary:
      'Bringing a standing opponent to the ground, under some degree of control, so the fight continues there.',
    isFeatured: true,
    difficulty: 'intermediate',
    readMinutes: 4,
    sourceKeys: [{ key: 'wp-takedown' }],
    recognition: `One fighter drops their level, closes distance, and drives through or lifts the other fighter, who ends up on the mat while the fighter who initiated it typically ends up in a controlling position above or alongside them.`,
    theTechnique: `A **takedown** is any technique that brings a standing opponent to the ground with the attacking fighter maintaining some degree of control over the outcome, as distinct from simply knocking someone down with a strike. Takedowns range from leg-based attacks (a single-leg or double-leg takedown) to upper-body throws (a hip throw or body lock takedown) to simple trips and sweeps that use an opponent's own weight and balance against them.`,
    whenUsed: `A fighter attempts a takedown to move the fight to a phase where they have an advantage, most obviously a wrestler against a striker, but also to neutralise a dangerous standing opponent even without a strong ground game of their own, simply to disrupt their rhythm and control the pace of a round.`,
    risks: `A takedown attempt exposes the attacking fighter to strikes while their level is changed and their head is often lower and closer to the other fighter, a vulnerable moment commonly described as being caught with a knee or an uppercut "on the shot".`,
    counters: `An opponent can defend a takedown with a sprawl (dropping their hips back and away from the attempt), by underhooking the attacking fighter's arms to stop the drive, or simply by having strong enough balance and hip positioning that the attempt fails outright, sending both fighters back to a neutral standing position.`,
    example: `A fighter closes distance behind a feinted jab, drops levels, and secures both of the other fighter's legs for a double-leg takedown. The defending fighter sprawls their hips back on reaction, briefly stopping the drive, but the attacking fighter adjusts, finishes the takedown against the cage, and settles into the other fighter's guard as the fight continues on the ground.`,
    misunderstandings: `A common one: treating every fighter who ends up on the ground as having "lost" that exchange. A takedown moves the fight to a new phase; who actually benefits from being there depends on both fighters' skill on the ground, not merely on who initiated the takedown.`,
    related: [
      'single-leg-takedown',
      'double-leg-takedown',
      'body-lock-takedown',
      'takedown-defense',
      'sprawl',
      'mma-wrestling-explained',
    ],
  }),

  technique({
    slug: 'single-leg-takedown',
    title: 'Single-Leg Takedown',
    category: 'wrestling',
    aliases: ['single leg takedown', 'single leg', 'single-leg'],
    summary: 'A takedown built around controlling one of the opponent’s legs rather than both.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-single-leg' }, { key: 'wp-takedown' }],
    recognition: `A fighter drops level, wraps up one of the opponent's legs at the knee or ankle, and drives forward or lifts, while the opponent typically hops on their remaining leg or grabs for the fence or the other fighter's shoulders to stay upright.`,
    theTechnique: `A **single-leg takedown** attacks and controls only one of the opponent's legs, rather than both, as in a double-leg. Because only one leg is trapped, the defending fighter retains more mobility than in a double-leg attempt, which usually means the takedown is finished through a series of steps, angle changes and off-balancing rather than a single driving motion.`,
    whenUsed: `A single-leg is often used when a double-leg is unavailable, for instance when an opponent has sprawled or when only one leg is within reach as a level change begins, and it is also a common entry from the clinch, where a fighter already has upper-body control and simply reaches down for a leg.`,
    risks: `Because the defending fighter keeps one leg free, a single-leg attempt that stalls can turn into a prolonged standing scramble, during which the attacking fighter's head and posture can be exposed to knees, elbows or a guillotine choke attempt.`,
    counters: `A defending fighter can hop away on the free leg while sprawling their weight onto the attacker, defend with a whizzer (an overhook) on the attacking arm to disrupt their balance, or attempt a guillotine choke on an attacker whose head has dropped low and exposed during the attempt.`,
    example: `A fighter shoots in but only secures one leg after the opponent partially sprawls away. Rather than forcing a stalled position, the attacker circles to change the angle, lifts the trapped leg, and off-balances the opponent to the mat, completing the single-leg takedown a few seconds after the initial attempt looked to have failed.`,
    misunderstandings: `A common one: assuming a single-leg is simply a failed or lesser double-leg. It is a distinct technique with its own entries, finishes and follow-ups, often preferred specifically because it demands less commitment and carries a different risk profile than attacking both legs at once.`,
    related: [
      'double-leg-takedown',
      'takedown-explained',
      'takedown-defense',
      'sprawl',
      'overhook-whizzer',
    ],
  }),

  technique({
    slug: 'double-leg-takedown',
    title: 'Double-Leg Takedown',
    category: 'wrestling',
    aliases: ['double leg takedown', 'double leg', 'double-leg'],
    summary: 'A takedown built around driving through both of the opponent’s legs at once.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-double-leg' }, { key: 'wp-takedown' }],
    recognition: `A fighter drops level sharply, drives forward to wrap up both of the opponent's legs behind the knees, and continues driving through them, taking the opponent straight backward and down to the mat.`,
    theTechnique: `A **double-leg takedown** attacks both of the opponent's legs simultaneously, typically by shooting in low, wrapping both arms behind the knees, and driving forward with the legs and hips to take the opponent's base away entirely. Because both legs are controlled at once, a clean double-leg tends to be more immediately decisive than a single-leg, though it also commits the attacker's head and posture more fully during the shot.`,
    whenUsed: `A double-leg is typically attempted when a fighter can close distance cleanly, often off a feint or behind their own strikes, and wants the most direct route to the mat rather than a more gradual, positional entry.`,
    risks: `The moment of the shot, level changed, head down, both arms committed to the legs, is one of the more exposed positions in striking range, and is the classic setup for a counter knee, uppercut, or guillotine choke if the timing or entry is off.`,
    counters: `The primary counter is the sprawl: the defending fighter drops their hips back and down, out of reach of the driving attempt, while using their weight to flatten the attacker out. A defending fighter can also underhook an arm to break the attacker's grip, or simply create enough distance beforehand that the shot never closes.`,
    example: `A fighter closes distance off a low kick feint, drops level, and drives through for a double-leg. The opponent sprawls immediately, dropping their hips onto the attacker's shoulders and killing the forward momentum, and both fighters end up scrambling on the fence rather than the takedown being cleanly completed.`,
    misunderstandings: `A common one: assuming a stuffed double-leg is simply a wasted attempt. Even an unsuccessful shot can tire an opponent's sprawl, set up a later attempt, or open a striking opportunity once both fighters reset, so a single failed takedown rarely tells the whole story of who is winning the underlying exchange.`,
    related: [
      'single-leg-takedown',
      'sprawl',
      'takedown-defense',
      'takedown-explained',
      'level-change',
    ],
  }),

  technique({
    slug: 'body-lock-takedown',
    title: 'Body Lock Takedown',
    category: 'wrestling',
    aliases: ['body lock takedown', 'body-lock takedown', 'clinch takedown from body lock'],
    summary:
      'A takedown driven from a body lock around the opponent’s torso rather than from their legs.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-takedown' }, { key: 'wp-clinch-fighting' }],
    recognition: `Both fighters are in a tight clinch, arms wrapped around each other's torsos, and one fighter changes the angle of their hips, lifts or off-balances the other, and drives them to the mat without ever reaching down for a leg.`,
    theTechnique: `A **body lock takedown** is completed from a locked grip around the opponent's torso, using hip pressure, off-balancing and leverage rather than attacking the legs directly. It is a common finish from extended clinch exchanges, particularly against a cage or ring wall, where the attacking fighter uses the surface to trap the opponent's base while working the body lock to the ground.`,
    whenUsed: `This is typically used once a fighter has already secured control in the clinch, especially against the fence, rather than as an opening attack from a neutral standing position, since establishing the body lock itself usually requires some prior grip fighting.`,
    risks: `Because it relies on sustained clinch control, an attacker committed to a body lock takedown can be vulnerable to knees and short punches if the opponent frees an arm before the takedown is completed.`,
    counters: `A defending fighter can fight to free an underhook to disrupt the lock, widen their base and drop their hips to resist being off-balanced, or use the cage itself to stay upright by pushing back into it rather than being driven away from it.`,
    example: `A fighter secures a body lock against the cage after a lengthy clinch exchange, adjusts their hips to get underneath the opponent's centre of gravity, and lifts and turns them to the mat, completing the takedown without ever touching a leg.`,
    misunderstandings: `A common one: assuming every clinch takedown is "a wrestling takedown" in the leg-attack sense. A body lock takedown is a distinct family of technique, closer in spirit to a judo throw than to a shot for the legs, and is common precisely because MMA's cage or ropes make sustained clinch control easier to hold than in open-mat wrestling.`,
    related: [
      'body-lock',
      'cage-clinch',
      'clinch-takedowns',
      'hip-throw',
      'wrestling-against-the-cage',
    ],
  }),

  technique({
    slug: 'trip',
    title: 'Trip',
    category: 'wrestling',
    aliases: ['trip takedown', 'leg trip', 'foot trip'],
    summary: 'Using a leg to block or hook the opponent’s leg while off-balancing them to the mat.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-throw' }, { key: 'wp-takedown' }],
    recognition: `A fighter, usually from a clinch or after a strike has been checked, hooks or blocks one of the opponent's legs with their own leg while pushing or turning the opponent's upper body, sending them over or around the blocked leg to the mat.`,
    theTechnique: `A **trip** takes an opponent down by using a leg to obstruct one of theirs while unbalancing them with the arms or upper body, so that the opponent falls over the blocked leg rather than being lifted or driven backward. Trips are common finishes from clinch exchanges and are often set up by an upper-body push or pull that gets the opponent's weight moving in the direction the trip needs.`,
    whenUsed: `A trip is typically used once a fighter already has upper-body control in a clinch and wants a lower-commitment way to finish a takedown than a full body lock throw, since it does not require lifting the opponent's weight.`,
    risks: `A trip attempted without enough control of the opponent's upper body can be stepped over or simply avoided by the opponent lifting the blocked leg clear, and a badly timed trip can leave the attacking fighter's own base compromised.`,
    counters: `A defending fighter can lift the leg being hooked clear of the block, widen their stance to make a clean trip harder to land, or counter-off-balance the attacker by turning into the direction of the trip rather than resisting it directly.`,
    example: `From a clinch against the cage, a fighter hooks a leg behind the opponent's near leg while pulling their upper body forward and across. The opponent's balance is taken over the blocked leg, and they go down, with the attacking fighter following them to the mat in a controlling position.`,
    misunderstandings: `A common one: lumping every "leg takedown" together. A trip and a single-leg or double-leg shot look superficially similar in that a leg is involved, but a trip is fundamentally an off-balancing technique using the opponent's own momentum, not a driving attack on the legs themselves.`,
    related: ['foot-sweep', 'hip-throw', 'body-lock-takedown', 'takedown-explained'],
  }),

  technique({
    slug: 'foot-sweep',
    title: 'Foot Sweep',
    category: 'wrestling',
    aliases: ['foot sweep', 'ashi barai', 'sweep the foot'],
    summary:
      'Sweeping the opponent’s planted foot out from under them at the moment their weight is on it.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-sweep-wrestling' }, { key: 'wp-throw' }],
    recognition: `A fighter's foot, planted and briefly weighted mid-step, is swept sideways by the opponent's own foot, timed precisely to a moment when it cannot simply be lifted away, and the fighter drops to the mat as their base disappears.`,
    theTechnique: `A **foot sweep** removes a planted foot from under an opponent at the exact instant their weight is committed to it, using the attacking fighter's own foot or shin rather than a grabbing motion. Because it depends entirely on timing rather than strength, a foot sweep is generally regarded as one of the more technically demanding takedown entries, borrowed directly from judo.`,
    whenUsed: `A foot sweep is typically attempted during footwork exchanges or as an opponent steps to change angle, rather than from a static clinch, since it needs a moment when the target foot is weighted and briefly unable to be repositioned.`,
    risks: `A mistimed foot sweep, attempted when the target foot is not actually weighted, simply fails without unbalancing the opponent at all, and can leave the attacking fighter momentarily off-balance themselves.`,
    counters: `The main defence is timing-based rather than positional: keeping weight distributed rather than fully committed to one foot during exchanges makes a sweep much harder to land, and a fighter who feels their foot being swept can often simply step through rather than resist.`,
    example: `As an opponent steps forward to close distance, a fighter sweeps the opponent's leading foot sideways just as the weight transfers fully onto it, and the opponent, with no base left underneath them, drops straight to the mat.`,
    misunderstandings: `A common one: confusing a foot sweep with a trip. A trip generally blocks a leg while off-balancing the upper body; a foot sweep removes the base itself at a precisely timed moment, and depends on timing far more than on strength or grip control.`,
    related: ['trip', 'hip-throw', 'level-change', 'takedown-explained'],
  }),

  technique({
    slug: 'hip-throw',
    title: 'Hip Throw',
    category: 'wrestling',
    aliases: ['hip throw', 'o goshi', 'judo hip throw'],
    summary:
      'Loading the opponent onto the hips and throwing them over, borrowed directly from judo.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-hip-throw' }, { key: 'wp-throw' }],
    recognition: `A fighter turns into the opponent, drops their hips lower than the opponent's centre of gravity, and rotates them up and over in an arc, so the opponent's feet leave the ground entirely before they land, unlike a takedown that keeps both fighters' feet on the mat throughout.`,
    theTechnique: `A **hip throw** takes an opponent down by turning into them, dropping the hips below theirs, and using that leverage to rotate them up and over the attacker's hip in an arc, borrowed largely unchanged from judo. Because it briefly takes an opponent fully off the ground, a clean hip throw tends to be one of the more visually dramatic ways a fight moves from standing to the mat.`,
    whenUsed: `A hip throw is typically attempted from a clinch where a fighter already has a strong upper-body grip, and favours a fighter with a background in judo or similar throwing arts over a pure freestyle-wrestling approach.`,
    risks: `Committing to a hip throw means turning partially away from the opponent to load them onto the hip, a moment during which an alert opponent can strike, or resist the rotation and stay on their base rather than being thrown.`,
    counters: `A defending fighter can lower their own hips below the attacker's to deny the leverage the throw needs, resist the turning motion by staying square, or, if lifted, look to land safely and immediately scramble back to their feet or into guard.`,
    example: `From a clinch, a fighter turns in sharply, drops their hips under the opponent's, and rotates them cleanly over the hip and onto their back. The move takes only a second or two but visibly separates the opponent from their feet entirely before the landing.`,
    misunderstandings: `A common one: assuming any throw that ends with an opponent on the ground is "a hip throw". The defining feature is the opponent's feet leaving the ground over the attacker's own hip; a body lock takedown or trip that keeps both fighters grounded throughout is a different technique entirely.`,
    related: ['body-lock-takedown', 'trip', 'takedown-explained', 'mma-wrestling-explained'],
  }),

  standard({
    slug: 'level-change',
    title: 'Level Change',
    category: 'wrestling',
    aliases: ['level change', 'changing levels', 'drop level'],
    summary:
      'Dropping the hips and bending the knees to lower the body’s height before a takedown attempt.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-takedown' }, { key: 'wp-wrestling' }],
    explanation: `A **level change** is the drop in height a fighter makes, bending the knees and lowering the hips while keeping the back relatively straight, immediately before shooting for a takedown. It is a body-mechanics fundamental rather than a technique in its own right: nearly every takedown attempt begins with some version of it.`,
    howItWorks: `Dropping level gets a fighter's head and shoulders below the opponent's centre of gravity, which is generally necessary to drive through their legs or hips effectively; attempting a takedown from an upright stance, without changing level first, tends to be far less effective and easier to defend. A good level change is also often disguised behind a strike, most commonly a jab or a low kick feint, so the opponent cannot read the takedown coming from the level change alone.`,
    example: `A fighter throws a jab, and on the very next step drops their level sharply, bending at the knees rather than the waist, before driving in for a double-leg. To the opponent, the level change is disguised enough by the preceding jab that the takedown attempt arrives with less warning than it would from a stationary crouch.`,
    whyItMatters: `Recognising a level change is often the first visual cue that a takedown is about to be attempted, before the shot itself is even thrown, which is why fighters and coaches watch an opponent's hips and knees as closely as their hands.`,
    misunderstandings: `A common one: treating "level change" as if it only ever precedes a takedown. Fighters also change levels to duck under strikes or to disguise a body-kick or leg-kick entry, so a level change alone is a signal to stay alert, not a guarantee a takedown is coming.`,
    takeaways: `A level change lowers the hips before a takedown attempt, and disguising it behind a strike is a large part of what makes a shot effective rather than easily read.`,
    related: ['takedown-explained', 'double-leg-takedown', 'takedown-entry', 'sprawl'],
  }),

  standard({
    slug: 'takedown-entry',
    title: 'Takedown Entry',
    category: 'wrestling',
    aliases: ['takedown entry', 'setting up a takedown', 'shot entry'],
    summary:
      'The setup, distance and timing a fighter uses to get into range for a takedown attempt.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-takedown' }, { key: 'wp-wrestling' }],
    explanation: `A **takedown entry** is everything a fighter does to get into range and timing for a takedown before the shot itself: closing distance, disguising the intent, and picking the moment the opponent is least able to react. A technically sound entry is often what separates a takedown that lands from one that is stuffed before it starts.`,
    howItWorks: `Entries are commonly built around feints, most often a jab or a kick that draws a reaction, or a change of angle that closes distance without telegraphing the takedown itself. Distance matters as much as timing: a shot from too far away gives the opponent time to sprawl or move away, while a shot from too close can be jammed before the level change is complete.`,
    example: `Rather than shooting from the standard boxing range, a fighter steps forward behind two probing jabs, closing distance gradually so the final step into a double-leg attempt covers only a short gap rather than a long, telegraphed run-in. The shorter distance leaves the opponent far less time to sprawl.`,
    whyItMatters: `A wrestler with excellent takedowns in isolation can still struggle in MMA specifically if their entries are underdeveloped, since striking range and open space make a poorly set-up shot far easier to see coming and defend than a wrestling match on a mat with no striking to account for.`,
    misunderstandings: `A common one: treating takedown ability purely as a question of strength or technique in the takedown itself. Many high-level wrestlers who struggle early in their MMA careers do so specifically because their entries, not their finishing technique, need adapting to a sport where strikes and distance control complicate the approach.`,
    takeaways: `An entry is the setup work, distance and disguise, that gets a fighter into range for a takedown. It is frequently the difference between a shot that lands and one that is easily read and stuffed.`,
    related: ['level-change', 'takedown-explained', 'single-leg-takedown', 'double-leg-takedown'],
  }),

  technique({
    slug: 'sprawl',
    title: 'Sprawl',
    category: 'wrestling',
    alsoIn: ['defense'],
    aliases: ['sprawl', 'sprawling', 'what is a sprawl in mma'],
    summary:
      'Dropping the hips back and flattening out on top of an opponent’s takedown attempt to stop it cold.',
    isFeatured: true,
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-sprawl' }],
    recognition: `As an opponent shoots for a takedown, a fighter kicks their legs back and away from the attempt, dropping their hips down and their weight forward onto the attacker's upper back and shoulders, ending up flattened out on top of them rather than being driven backward.`,
    theTechnique: `A **sprawl** is the primary defensive reaction to a takedown attempt: as the opponent shoots in and drops level, the defending fighter kicks their own legs back out of reach, drops their hips low, and drives their weight down onto the attacker's upper back, using gravity and body weight to stop the forward drive rather than trying to muscle the attacker away directly.`,
    whenUsed: `A sprawl is a reaction, not a planned attack: it is thrown the instant a fighter reads a takedown attempt coming, and its effectiveness depends heavily on speed and timing rather than raw strength.`,
    risks: `A sprawl leaves the defending fighter's own head and hands lower and closer to the mat and to the attacker, which occasionally exposes them to a guillotine choke attempt if they are not careful with their positioning while sprawled.`,
    counters: `An attacker whose shot has been sprawled on can chain into a different technique rather than abandoning the exchange entirely, switching to a single-leg if one leg remains within reach, or working for a foot sweep or trip once both fighters are scrambling for position.`,
    example: `A fighter reads a double-leg attempt early, kicks both legs back sharply and drops their hips and chest down onto the attacker's shoulders. The takedown attempt stalls completely, and both fighters scramble briefly before separating back to a neutral standing position.`,
    misunderstandings: `A common one: assuming a sprawl is purely a strength contest, out-muscling the takedown attempt. Timing matters far more than raw power: a sprawl thrown early, before the attacker's level change is complete, stops a much stronger opponent's takedown far more reliably than a late, powerful sprawl against a shot that has already landed.`,
    related: [
      'takedown-defense',
      'takedown-explained',
      'double-leg-takedown',
      'single-leg-takedown',
    ],
  }),

  standard({
    slug: 'takedown-defense',
    title: 'Takedown Defense',
    category: 'wrestling',
    alsoIn: ['defense'],
    aliases: ['takedown defense', 'takedown defence', 'stopping a takedown', 'sprawl and brawl'],
    summary: 'The overall skill of preventing an opponent’s takedown attempts from succeeding.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-takedown' }, { key: 'wp-wrestling' }],
    explanation: `**Takedown defense** is the general skill area covering everything a fighter does to stop an opponent from bringing the fight to the ground: reading a shot coming, sprawling, underhooking or overhooking to disrupt an attacker's grip, and re-establishing distance after a stuffed attempt. It is a distinct skill from having a strong ground game of one's own; a fighter can be a poor grappler and still have excellent takedown defense, and vice versa.`,
    howItWorks: `Good takedown defense is built from several layers working together: distance management that limits how often an opponent gets clean entries in the first place, quick recognition of a level change or shot as it begins, a technically sound sprawl, and the grip fighting (underhooks in particular) that lets a fighter stay upright even during a prolonged clinch battle against the cage.`,
    example: `A fighter with a striking background faces a decorated wrestler and is taken down repeatedly in an early fight of their career. Years later, having specifically trained takedown defense rather than becoming a wrestler themselves, the same fighter stuffs the majority of a similarly strong wrestler's attempts, not by out-wrestling them but by reading entries earlier and sprawling more efficiently.`,
    whyItMatters: `A fighter's takedown defense statistic is one of the most frequently cited numbers in pre-fight analysis specifically because it predicts whether a striker will actually get to fight the fight they want, regardless of how good their striking itself is.`,
    misunderstandings: `A common one: assuming poor takedown defense against one opponent means a fighter is simply "bad at wrestling" in general. Takedown defense is highly matchup-specific: a fighter can defend well against a particular style of attack (say, single-leg entries) while struggling against another (a strong body lock game off the cage), so a single fight's numbers should not be read as a fixed, universal rating.`,
    takeaways: `Takedown defense is the combined skill of reading, sprawling, and grip fighting that keeps a fight standing when an opponent wants it on the ground. It is a strategic asset on its own, separate from ground grappling ability.`,
    related: [
      'sprawl',
      'takedown-explained',
      'underhook',
      'wrestling-against-the-cage',
      'striking-vs-grappling',
    ],
  }),

  standard({
    slug: 'underhook',
    title: 'Underhook',
    category: 'wrestling',
    alsoIn: ['clinch'],
    aliases: ['underhook', 'underhooks', 'what is an underhook'],
    summary: 'An arm threaded under an opponent’s armpit, one of the clinch’s most valuable grips.',
    difficulty: 'beginner',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-underhook' }, { key: 'wp-clinch-fighting' }],
    explanation: `An **underhook** is a grip in which a fighter's arm is threaded underneath the opponent's armpit and wraps around their upper body from below. It is one of the single most fought-over positions in any clinch exchange, since the fighter with the underhook generally has better control of the other fighter's posture and balance than the fighter without one.`,
    howItWorks: `Having an underhook makes it harder for the opponent to control or off-balance the fighter who holds it, since the underhook fighter can lift, turn, and generally dictate posture in a way the overhook fighter (whose arm is on top, wrapped over rather than under) cannot as easily counter. A fighter with underhooks on both sides is in a particularly strong position to attempt a body lock takedown or to control the clinch outright; a fighter with neither underhook is generally on the defensive.`,
    example: `Early in a clinch exchange against the cage, one fighter fights to insert an underhook on their trapped side, immediately changing the balance of the exchange: where they had been getting controlled and pushed back into the fence, the underhook lets them square back up and begin working their own offence instead.`,
    whyItMatters: `Because so much of clinch and wrestling exchanges is decided by who controls the underhooks, commentary frequently narrates a clinch battle purely in terms of who has fought for and won them, even before any takedown or strike has actually landed.`,
    misunderstandings: `A common one: assuming a single underhook automatically means dominance. A fighter can have an underhook and still be controlled overall if the opponent has other compensating grips or positioning; the underhook is a significant advantage, not an automatic win of the exchange on its own.`,
    takeaways: `The underhook, an arm threaded under the opponent's armpit, is one of the clinch's most valuable and most fought-over grips, relevant equally to wrestling exchanges and to standing clinch fighting more broadly.`,
    related: [
      'overhook-whizzer',
      'pummeling',
      'mma-clinch-explained',
      'body-lock-takedown',
      'takedown-defense',
    ],
  }),

  standard({
    slug: 'overhook-whizzer',
    title: 'Overhook / Whizzer',
    category: 'wrestling',
    alsoIn: ['clinch'],
    aliases: ['overhook', 'whizzer', 'over-hook', 'what is a whizzer'],
    summary:
      'An arm wrapped over an opponent’s arm and shoulder, most often used to fight off a takedown or turn an opponent.',
    difficulty: 'beginner',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-wrestling' }],
    explanation: `An **overhook**, commonly called a **whizzer** in a wrestling context, is a grip in which a fighter wraps their arm over the top of the opponent's arm and shoulder, the mirror image of an underhook. Where an underhook generally favours the fighter holding it, an overhook is a more situational tool, most valuable defensively, particularly against a single-leg takedown attempt.`,
    howItWorks: `An overhook lets a fighter apply downward and rotational pressure on the opponent's shoulder and arm, which is especially useful for turning a takedown attempt off to the side or for creating enough space to free the leg or hip the opponent is attacking. On its own, holding only an overhook while the opponent holds an underhook is generally considered a positionally weaker spot to be fighting from than the reverse.`,
    example: `As an opponent completes a shot and secures a single leg, the defending fighter throws an overhook, a whizzer, over the attacker's near arm and shoulder, using the leverage to twist the attacker's upper body off-line and away from a clean finish, buying time to hop the trapped leg free.`,
    whyItMatters: `The overhook-versus-underhook battle is one of the clinch's most basic tactical questions, and recognising who holds which grip is often enough on its own to predict who is about to gain control of a standing exchange.`,
    misunderstandings: `A common one: treating the overhook as simply a weaker or failed version of the underhook. It has a specific, valuable defensive job, particularly against single-leg attempts, that an underhook does not do as well, so a fighter fighting for an overhook is not necessarily losing the grip battle, only playing a different role in it.`,
    takeaways: `An overhook (or whizzer) wraps over the opponent's arm and shoulder and is most valuable defensively, especially against a single-leg takedown, in contrast to the generally more advantageous underhook.`,
    related: ['underhook', 'single-leg-takedown', 'pummeling', 'takedown-defense'],
  }),

  standard({
    slug: 'pummeling',
    title: 'Pummeling',
    category: 'wrestling',
    aliases: ['pummeling', 'pummelling', 'fighting for underhooks'],
    summary:
      'The continuous grip fight in a clinch, each fighter working to trade an overhook for an underhook.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-wrestling' }],
    explanation: `**Pummeling** is the continuous grip exchange that happens once two fighters are in a clinch, each working to insert an underhook and clear the opponent's, cycling through overhooks and underhooks until one fighter establishes a clearly favourable grip or the clinch is broken. Named from wrestling, where the same exchange is a fundamental, heavily drilled skill.`,
    howItWorks: `A pummeling exchange looks like a rapid, almost rhythmic trading of arm position: as one fighter works an arm underneath for an underhook, the other fights to keep or regain their own, and both fighters' hips and weight shift constantly to support whichever grip they currently hold. It rarely resolves in a single motion; a real pummeling exchange in a fight is often several seconds of continuous adjustment before either fighter's control clearly separates from the other's.`,
    example: `Locked in a clinch against the cage, both fighters trade grips repeatedly, one gaining a single underhook only to have the other fighter circle and clear it a moment later. After several seconds of this, one fighter finally secures a double underhook, ending the pummeling exchange with a clear positional advantage.`,
    whyItMatters: `A fighter who has drilled pummeling extensively, common among fighters with a wrestling background, is generally able to win the underlying grip battle in a clinch even against a physically comparable opponent, which is a large part of why wrestling pedigree translates so directly into clinch control in MMA.`,
    misunderstandings: `A common one: viewing a pummeling exchange as a static, motionless clinch. It is a continuously active contest even when neither fighter is striking or attempting a takedown, and a viewer who reads it as "nothing happening" is missing a live tactical battle over the grips that will decide what happens next.`,
    takeaways: `Pummeling is the ongoing underhook-versus-overhook grip fight inside a clinch, and winning it is usually the precondition for whatever a fighter tries to do next, a takedown, a strike, or simply staying upright.`,
    related: ['underhook', 'overhook-whizzer', 'mma-clinch-explained', 'body-lock'],
  }),

  standard({
    slug: 'chain-wrestling',
    title: 'Chain Wrestling',
    category: 'wrestling',
    alsoIn: ['advanced-concepts'],
    aliases: ['chain wrestling', 'combination takedowns', 'linking takedowns'],
    summary:
      'Smoothly transitioning from one takedown attempt into another rather than resetting after a failed shot.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-wrestling' }, { key: 'wp-takedown' }],
    explanation: `**Chain wrestling** is the ability to move directly from one takedown attempt into another when the first is defended, without stopping to reset, so a sprawled single-leg becomes an attempt at the other leg, or a stuffed double-leg flows into a trip, rather than the exchange simply ending once the first attempt fails.`,
    howItWorks: `Chain wrestling relies on reading how an opponent has defended the first attempt and immediately exploiting the position that defence leaves them in, since a sprawl or a block against one technique frequently opens space for a different one. A fighter skilled at it treats a defended takedown as a transition rather than a failure, keeping constant forward pressure through a sequence of linked attempts until one succeeds or the exchange is genuinely over.`,
    example: `A fighter's double-leg attempt is sprawled on. Rather than disengaging, they immediately switch their grip to a single leg that has come free during the scramble, and when that too is defended, transition again into a trip as the opponent's balance is compromised from defending twice in quick succession. The eventual takedown is credited to the last technique attempted, but the sequence that produced it is chain wrestling.`,
    whyItMatters: `Chain wrestling is one of the clearer markers separating a merely strong amateur-level wrestler from an elite MMA wrestler, since a single well-drilled takedown is far easier for an opponent to specifically prepare for than a fighter capable of fluidly moving between several linked options.`,
    misunderstandings: `A common one: assuming a fighter attempting several takedowns in a row is simply repeating a failed technique out of stubbornness. Genuine chain wrestling is a deliberate sequence exploiting each successive defensive reaction, not the same attempt repeated identically; distinguishing the two is mostly a question of whether the fighter's attack is actually adapting to what the defence gave them.`,
    takeaways: `Chain wrestling links takedown attempts together, using one defended technique to set up the next, and is generally regarded as an advanced skill that separates elite wrestlers from merely competent ones.`,
    related: ['takedown-explained', 'single-leg-takedown', 'double-leg-takedown', 'scramble'],
  }),

  standard({
    slug: 'mat-return',
    title: 'Mat Return',
    category: 'wrestling',
    alsoIn: ['cage-wrestling'],
    aliases: ['mat return', 'returning to the mat', 'putting the fight back down'],
    summary: 'Forcing a fight back to the ground after an opponent has stood back up from it.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-wrestling' }, { key: 'wp-takedown' }],
    explanation: `A **mat return** is a technique used to put a fight back on the ground immediately after an opponent has worked their way back to their feet, typically before they have re-established enough distance or posture to defend themselves properly. It matters specifically in MMA because standing back up does not, on its own, guarantee a fighter has actually escaped an unfavourable position.`,
    howItWorks: `A mat return usually exploits the brief window right after a stand-up, when the standing fighter's base and posture are not yet fully set, using a trip, a single-leg attempt on a leg that hasn't cleared, or simply continued upper-body control from before the stand-up occurred. Because it depends on a narrow timing window, a mat return is usually attempted immediately rather than after any pause.`,
    example: `A fighter fights their way up from the bottom of a dominant position, briefly standing, only for the other fighter, who never released a body lock during the stand-up, to immediately drive them back down to the mat before they can create separation. From the outside it can look like the fight briefly returned to standing and then went straight back down; the mat return is what closed that gap.`,
    whyItMatters: `A fighter who is technically able to "get back up" from bad positions repeatedly, but is then immediately put right back down by a mat return each time, is not actually escaping the exchange in any meaningful sense, which matters both for how a fight is actually going and for how a round should be scored.`,
    misunderstandings: `A common one: crediting a fighter who stands up from a bad position with having "escaped" it, full stop. If the same fighter is returned to the mat within moments by a mat return, the underlying exchange has not really changed, even though the fight briefly looked different to a casual viewer watching only for who is standing.`,
    takeaways: `A mat return closes the gap immediately after a stand-up, before the standing fighter has properly reset, and is a reminder that standing back up and actually escaping an exchange are not always the same thing.`,
    related: ['wrestling-against-the-cage', 'ride-position', 'takedown-explained', 'scramble'],
  }),

  standard({
    slug: 'scramble',
    title: 'Scramble',
    category: 'wrestling',
    aliases: ['scramble', 'scrambling', 'mma scramble'],
    summary:
      'A fast, chaotic exchange in which position is briefly up for grabs and can change hands rapidly.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-wrestling' }, { key: 'wp-takedown' }],
    explanation: `A **scramble** is a fast-moving exchange, usually on or near the ground, in which neither fighter has settled into a controlled position and both are actively fighting for one, often resulting in position changing hands more than once in the space of a few seconds. It contrasts with the more static image of ground fighting most casual viewers picture, where one fighter is clearly on top and the other clearly beneath them.`,
    howItWorks: `A scramble typically begins from a stuffed takedown, a failed submission attempt, or a stand-up gone wrong, any moment when both fighters' weight and balance are briefly unresolved. Both fighters try to be the one who ends the scramble in a superior position, and because everything happens quickly and close together, a scramble is often one of the harder passages of a fight for commentary, and for judges, to score cleanly in the moment.`,
    example: `A takedown attempt is stuffed, and rather than resetting to a neutral standing position, both fighters end up tangled near the cage, briefly trading top position twice in the space of five seconds before one fighter finally settles into a stable position on top. To a viewer, the whole sequence might register only as "some scrambling", even though a great deal of skill and effort decided how it resolved.`,
    whyItMatters: `Scrambling ability is a distinct, valuable skill in its own right, separate from a fighter's takedowns or their guard, and fighters known for surviving or winning scrambles are often able to escape or reverse positions that would otherwise be lost causes against opponents without that specific skill.`,
    misunderstandings: `A common one: treating a scramble as a momentary loss of control by both fighters rather than a genuine, actively contested phase of the fight. A high-level scramble is closely fought and often decided by fine margins in grip, timing and base, not by accident or disorder.`,
    takeaways: `A scramble is a fast, position-undecided exchange where both fighters are actively fighting for control, and scrambling well is its own recognised skill, distinct from takedowns or guard play.`,
    related: ['chain-wrestling', 'mat-return', 'takedown-explained', 'mma-positions-explained'],
  }),

  standard({
    slug: 'ride-position',
    title: 'Ride Position',
    category: 'wrestling',
    aliases: ['ride position', 'riding', 'wrestling ride'],
    summary:
      'Staying attached to an opponent’s back or hips from the top, controlling without necessarily advancing.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-wrestling' }, { key: 'wp-folkstyle-wrestling' }],
    explanation: `**Ride position**, borrowed directly from folkstyle wrestling, describes a fighter staying attached to the top of, or behind, an opponent who is on all fours or turtled up, controlling their hips and preventing them from standing or turning, without necessarily advancing to a more dominant MMA-specific position like full mount.`,
    howItWorks: `Rather than actively working to pass to a further-along position, a fighter in ride position focuses on hip control and weight distribution to prevent the bottom fighter from escaping or standing, effectively neutralising them for a stretch of time. It is a wrestling-derived concept that maps only loosely onto the MMA positional hierarchy of guard, mount and back control, since a fighter can be "riding" an opponent without being in a formally named MMA position at all.`,
    example: `After a takedown, rather than working to pass into mount, a fighter simply rides the opponent's hips from behind while they are turtled up, preventing any attempt to stand or turn back into a more neutral position, and content to control the position for the remainder of the round.`,
    whyItMatters: `Ride position matters for scoring discussions specifically because it can look, to a viewer used to MMA's own positional vocabulary, like a fighter is "doing nothing", when in fact controlling an opponent's hips this way is a real, effortful skill judges are instructed to credit as effective grappling.`,
    misunderstandings: `A common one: assuming a fighter riding an opponent without advancing position or landing strikes is simply stalling. Preventing an opponent's escape is itself a form of control, and whether it should be scored as highly as active advancement or striking is a genuinely debated question within MMA judging, not a settled one.`,
    takeaways: `Ride position is wrestling-style hip control from the top, aimed at preventing an opponent's escape rather than advancing to a more dominant MMA position, and it is a real, if sometimes underappreciated, form of control.`,
    related: ['mat-return', 'scramble', 'mma-positions-explained', 'how-mma-scoring-works'],
  }),

  standard({
    slug: 'wrestling-against-the-cage',
    title: 'Wrestling Against the Cage',
    category: 'wrestling',
    alsoIn: ['cage-wrestling'],
    aliases: ['wrestling against the cage', 'cage wrestling', 'dirty wrestling against the fence'],
    summary:
      'Using the cage itself as a tool to control an opponent’s base, rather than only as a boundary.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-wrestling' }, { key: 'wp-clinch-fighting' }],
    explanation: `**Wrestling against the cage** describes using the cage wall itself as an active tool in a wrestling or clinch exchange, pinning an opponent's back to it to remove their ability to circle away, rather than treating the fence only as a boundary the fight happens to occur inside. It is a distinctly MMA skill, since open-mat and most other grappling sports have no equivalent fixed wall to use this way.`,
    howItWorks: `With an opponent's back against the cage, their usual takedown defence options, particularly circling away or sprawling into open space, are far more limited, since the wall behind them removes one whole direction of movement. A fighter skilled at this uses the cage to control an opponent's hips and posture directly, and can complete takedowns from positions (like a locked body lock) that would be much harder to finish in open space without a wall to press against.`,
    example: `Unable to complete a clean double-leg in open space against a strong sprawl, a fighter instead works to walk the opponent backward until their back meets the cage. Once there, with the opponent's retreat cut off, the same fighter secures a body lock and drives them down far more easily than the earlier open-space attempts had allowed.`,
    whyItMatters: `A fighter's overall takedown numbers in a fight can look very different depending on how much time was spent against the fence versus in open space, which is why "cage control" is tracked and discussed as its own factor separate from raw takedown counts.`,
    misunderstandings: `A common one: treating time spent against the cage as inherently one-sided or dull. A skilled defending fighter can use the cage themselves, to stay upright, to frame off an opponent, or to push back into space, so cage time is a genuinely contested phase of the fight, not an automatic advantage for whoever initiated it.`,
    takeaways: `Wrestling against the cage uses the fence itself to remove an opponent's usual defensive options, and is a core, MMA-specific skill with no direct equivalent in open-mat wrestling.`,
    related: ['body-lock-takedown', 'cage-clinch', 'takedown-defense', 'mma-wrestling-explained'],
  }),

  // ─── Clinch ────────────────────────────────────────────────────────────────

  standard({
    slug: 'mma-clinch-explained',
    title: 'MMA Clinch Explained',
    category: 'clinch',
    aliases: ['mma clinch', 'clinch explained', 'what is the clinch in mma'],
    summary:
      'Close-range standing contact where grips, short strikes and takedown attempts all become live at once.',
    isFeatured: true,
    difficulty: 'beginner',
    readMinutes: 4,
    sourceKeys: [
      { key: 'wp-clinch-fighting' },
      { key: 'wp-mma-clinch' },
      { key: 'wd-clinch-fighting' },
    ],
    explanation: `The **clinch** is the phase of a fight in which both fighters are in close-range standing contact, holding onto each other in some combination of grips, rather than fighting at striking range or on the ground. It sits between striking and wrestling on MMA's spectrum of phases, and can turn into either: strikes can still land at close range, and a clinch is where the majority of standing takedown attempts are actually finished from.`,
    howItWorks: `Inside the clinch, both fighters are simultaneously fighting for grip position (underhooks, overhooks, collar ties), looking for openings to land short strikes (knees, elbows and the close punches sometimes called dirty boxing), and probing for a takedown, all at the same time. Which of those a fighter is doing at any given instant depends heavily on who currently has the advantageous grips, which is why the underlying grip fight matters so much to how a clinch exchange actually unfolds.`,
    example: `Two fighters clinch up against the cage. One works a collar tie and lands a couple of short knees to the body, while the other fights for an underhook to relieve the pressure and eventually uses it to turn the position and attempt a body lock takedown instead. All of this, striking, grip fighting and a takedown attempt, happens within the same clinch exchange without either fighter disengaging.`,
    whyItMatters: `A fighter strong in the clinch can effectively create a fourth "home" phase of the fight beyond pure striking or pure ground grappling, one where their specific combination of skills (Muay Thai clinch knees, say, alongside wrestling) gives them an advantage neither a pure striker nor a pure grappler necessarily has.`,
    misunderstandings: `A common one: viewing the clinch purely as a stalling tactic or a pause in the action. It is a live, fully contested phase of the fight with its own strikes, positions and finishes, closely associated with Muay Thai's clinch game and with wrestling's control game alike.`,
    takeaways: `The clinch is close-range standing contact where grip fighting, short strikes and takedown attempts are all simultaneously live. It is a distinct phase of the fight, not a break from one.`,
    related: [
      'striking-vs-grappling',
      'underhook',
      'collar-tie',
      'body-lock',
      'mma-wrestling-explained',
    ],
  }),

  standard({
    slug: 'collar-tie',
    title: 'Collar Tie',
    category: 'clinch',
    aliases: ['collar tie', 'neck tie', 'clinch collar tie'],
    summary:
      'A hand cupped behind the opponent’s head or neck, used to control posture and set up strikes or a takedown.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-collar-tie' }, { key: 'wp-muay-thai-clinch' }],
    explanation: `A **collar tie** is a grip in which a fighter cups a hand behind the opponent's head or neck, using it to control their posture, most often to pull the head down and forward, off-balancing them and opening up short strikes or a takedown attempt. It is one of the clinch's most fundamental grips, present in wrestling, Muay Thai and boxing's inside game alike, each using it slightly differently.`,
    howItWorks: `By controlling the head, a collar tie effectively controls a large part of the rest of the body, since an opponent whose head is pulled down and off-line struggles to generate power or balance for their own strikes or takedown attempts. A single collar tie is often paired with a strike from the free hand, and a double collar tie (both hands on the neck) is a distinct, more dominant version of the same idea.`,
    example: `A fighter secures a collar tie with their lead hand and uses it to pull the opponent's head down and to one side, off-balancing them just enough to land a clean knee to the body with the other leg, a classic Muay Thai-derived combination that depends entirely on the tie itself doing the controlling work.`,
    whyItMatters: `Recognising a collar tie explains why a fighter's head position in the clinch matters so much: a fighter whose head is being actively controlled is generally on the back foot in that exchange, even if no strike has landed yet.`,
    misunderstandings: `A common one: treating any hand near the opponent's neck as a collar tie. The grip specifically needs to be controlling posture, pulling or pushing the head, to function as one; a hand simply resting near the neck without exerting that control is not doing the same job.`,
    related: ['double-collar-tie-thai-clinch', 'underhook', 'mma-clinch-explained', 'clinch-knees'],
  }),

  standard({
    slug: 'double-collar-tie-thai-clinch',
    title: 'Double Collar Tie / Thai Clinch',
    category: 'clinch',
    aliases: ['double collar tie', 'thai clinch', 'muay thai clinch', 'plum'],
    summary:
      'Both hands locked behind the opponent’s neck, the dominant clinch position most associated with Muay Thai.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-muay-thai-clinch' }, { key: 'wp-collar-tie' }],
    explanation: `A **double collar tie**, often called the **Thai clinch** or "the plum", locks both hands behind the opponent's neck, giving far greater control over their posture than a single collar tie can. It is closely associated with Muay Thai, where it is a central, heavily developed part of the clinch game, and is generally regarded as one of the more dominant grips available in a standing exchange.`,
    howItWorks: `With both hands controlling the neck, a fighter can pull the opponent's head down sharply, off-balancing them almost entirely, while their own hips and knees stay free to strike. It is a particularly effective platform for clinch knees, since the opponent's posture and ability to move away are both compromised while their head remains controlled.`,
    example: `A fighter fighting from a Muay Thai background secures a double collar tie against the cage, pulls the opponent's head down and forward, and lands a series of knees to the body and, once the head is controlled low enough, to the head, all while the opponent struggles to free their neck or create the distance needed to escape.`,
    whyItMatters: `A fighter who allows an opponent to secure a clean double collar tie is generally in real danger, both of absorbing significant damage from knees and of simply being unable to escape the position without giving up an underhook or being taken down instead.`,
    misunderstandings: `A common one: assuming the double collar tie is purely a striking tool. It also compromises an opponent's balance badly enough that it is regularly used to set up takedowns as well as strikes, particularly against a fence.`,
    related: ['collar-tie', 'clinch-knees', 'mma-clinch-explained', 'double-underhooks'],
  }),

  standard({
    slug: 'double-underhooks',
    title: 'Double Underhooks',
    category: 'clinch',
    aliases: ['double underhooks', 'both underhooks', 'locked underhooks'],
    summary:
      'Both arms threaded under the opponent’s armpits, one of the clinch’s clearest advantages.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-underhook' }, { key: 'wp-clinch-fighting' }],
    explanation: `**Double underhooks** means both of a fighter's arms are threaded under the opponent's armpits at once, generally regarded as one of the strongest control positions available in a standing clinch. Where a single underhook already offers a real advantage, having both effectively removes most of the opponent's ability to control posture or balance in return.`,
    howItWorks: `With both underhooks locked, a fighter can typically lift, drive or turn the opponent largely on their own terms, since the opponent has no equivalent counter-grip left to resist with, both of their own arms having been forced up and over rather than under. This is the platform most body lock takedowns are launched from, since the double underhook grip and the body lock grip are closely related.`,
    example: `Deep into a clinch exchange, a fighter finally clears the opponent's remaining underhook attempt and locks both arms underneath, immediately changing the character of the exchange: what had been an even grip fight becomes one fighter driving the other backward toward the cage with little resistance available.`,
    whyItMatters: `Reaching double underhooks is often the clearest visible signal in a clinch exchange that one fighter is about to dictate what happens next, a takedown, sustained cage control, or simply forcing the other fighter into a defensive posture.`,
    misunderstandings: `A common one: assuming double underhooks alone guarantees a takedown. It is a strong control position, but a well-defended opponent can still resist being taken down even from here, particularly by widening their base and using the cage themselves to stay upright.`,
    related: ['underhook', 'body-lock', 'body-lock-takedown', 'pummeling'],
  }),

  standard({
    slug: 'body-lock',
    title: 'Body Lock',
    category: 'clinch',
    aliases: ['body lock', 'bear hug clinch', 'locking the body'],
    summary:
      'Both arms locked around the opponent’s torso, controlling their hips and posture directly.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-takedown' }],
    explanation: `A **body lock** is a grip in which a fighter wraps both arms fully around the opponent's torso and locks their hands together, controlling the hips and core directly rather than working through the arms or neck. It is generally considered a step further than double underhooks, since the hands are actually joined rather than merely positioned underneath.`,
    howItWorks: `Because the body lock controls the hips directly, it removes much of an opponent's ability to create distance or reposition, and is the grip most commonly used to launch a body lock takedown, particularly against the cage where the opponent's retreat is already limited. Breaking a body lock generally requires freeing at least one arm or creating enough separation to slip a hip free, rather than any single dramatic escape.`,
    example: `Having secured double underhooks, a fighter locks their hands together around the opponent's lower back, converting the grip into a full body lock. From there, walking the opponent to the cage becomes far easier, since the opponent's hips, not just their arms, are now under direct control.`,
    whyItMatters: `A body lock is one of the clearest visual cues that a takedown is imminent, since so few defensive options remain once an opponent's hips are fully controlled this way, particularly with a wall behind them.`,
    misunderstandings: `A common one: confusing a body lock with a simple clinch hug. The defining feature is the hands actually locking together around the torso, giving genuine hip control, rather than the arms merely being wrapped loosely around the opponent without a secured grip.`,
    related: ['double-underhooks', 'body-lock-takedown', 'cage-clinch', 'clinch-takedowns'],
  }),

  standard({
    slug: 'wrist-control',
    title: 'Wrist Control',
    category: 'clinch',
    aliases: ['wrist control', 'controlling the wrist', 'wrist ties'],
    summary:
      'Grabbing an opponent’s wrist or forearm to limit their striking or takedown options in close.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-mma-clinch' }],
    explanation: `**Wrist control** is a close-range grip in which a fighter grabs an opponent's wrist or forearm to limit what that arm can do, whether that means preventing a strike, stopping the opponent from fighting for an underhook, or simply buying a moment to reset position. It is a lower-commitment grip than an underhook or collar tie, useful specifically because it is quick to apply and to release.`,
    howItWorks: `By pinning a wrist or forearm, a fighter denies the opponent the use of that hand, whether they intended to throw a strike with it, use it to grip fight, or post it against a takedown attempt. Wrist control is frequently a bridging grip: used briefly to create an opening for a more committed grip (an underhook, a collar tie) or a strike, rather than as an end in itself.`,
    example: `Backed toward the cage, a fighter grabs the attacking fighter's lead wrist just as a strike begins, preventing it from landing cleanly and buying a half-second to circle off the fence rather than absorb the shot or get trapped in a worse position.`,
    whyItMatters: `Wrist control is one of the clinch's more understated tools, easy for a casual viewer to miss entirely, but a meaningful part of why some fighters seem consistently able to avoid or blunt short strikes that would otherwise land cleanly in close.`,
    misunderstandings: `A common one: assuming grabbing an opponent's arm at all is itself a foul or an illegal hold. Wrist and arm control of this kind is a standard, legal part of clinch fighting; the fouls that exist around grips concern specific things like grabbing the fence or an opponent's shorts, not controlling a wrist.`,
    related: ['collar-tie', 'underhook', 'dirty-boxing', 'mma-clinch-explained'],
  }),

  standard({
    slug: 'dirty-boxing',
    title: 'Dirty Boxing',
    category: 'clinch',
    aliases: ['dirty boxing', 'inside boxing', 'clinch boxing'],
    summary:
      'Short, close-range punches thrown while grip fighting, without fully committing to a takedown or a clean release.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-dirty-boxing' }, { key: 'wp-clinch-fighting' }],
    explanation: `**Dirty boxing** describes short, close-range punches, usually hooks and uppercuts, thrown while a fighter maintains a grip on the opponent with their other hand, rather than fully releasing to strike at range or fully committing to a takedown. The name comes from boxing's own inside game, where holding and hitting in close is technically restricted; MMA's rules are more permissive about this, letting it become a developed clinch skill in its own right.`,
    howItWorks: `A fighter using dirty boxing typically controls the opponent's posture with one hand, a collar tie or a grip on the head or shoulder, while landing short punches with the other, using the control to keep the opponent from creating the distance they would need to avoid the strikes cleanly. It tends to favour a fighter with a strong boxing background who has adapted their hands to a range and grip situation pure boxing does not allow.`,
    example: `Against the cage, a fighter controls the opponent's head with a collar tie, denying them the ability to pull back cleanly, and lands a series of short hooks to the body and head with the free hand, strikes that would carry little power at full range but land cleanly in the compressed distance the grip creates.`,
    whyItMatters: `Dirty boxing is a large part of why the clinch can be genuinely dangerous rather than merely a positional battle: a fighter controlled against the cage can absorb significant, accumulating damage even without ever being taken down or finished outright.`,
    misunderstandings: `A common one: assuming the "dirty" in the name implies an illegal or foul technique. It refers only to the informal, non-regulation style of the punches relative to pure boxing's rules, not to anything against MMA's own ruleset, where this kind of clinch striking is entirely legal.`,
    related: ['collar-tie', 'clinch-knees', 'clinch-elbows', 'mma-clinch-explained'],
  }),

  technique({
    slug: 'clinch-knees',
    title: 'Clinch Knees',
    category: 'clinch',
    aliases: ['clinch knees', 'knees in the clinch', 'thai knees'],
    summary:
      'Knee strikes thrown from close range while a fighter maintains clinch control, most associated with Muay Thai.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-muay-thai-clinch' }, { key: 'wp-clinch-fighting' }],
    recognition: `A fighter controlling the clinch, often from a collar tie or double collar tie, drives a knee upward into the opponent's midsection or, if their head is controlled low enough, into their head, repeatedly and in quick succession.`,
    theTechnique: `**Clinch knees** are knee strikes thrown from close range while a fighter maintains some form of clinch control, most commonly a collar tie, which pulls the opponent's posture down and forward directly into the path of the rising knee. The grip and the strike work together: the tie compromises the opponent's ability to create distance, and the knee exploits the resulting closeness.`,
    whenUsed: `Clinch knees are a central weapon for fighters with a strong Muay Thai background specifically because the sport's own clinch game is built heavily around them, and they are frequently used against an opponent trapped against the cage with limited room to retreat.`,
    risks: `Landing effective clinch knees usually requires exposing at least one arm to the grip fight rather than defending fully, and a fighter too focused on knees can be vulnerable to a takedown attempt if their grip and posture slip while attacking.`,
    counters: `A defending fighter can control distance by keeping their hips back even while their upper body is controlled, fight to break the collar tie, or change levels to attempt a takedown that removes the knee-striking range altogether.`,
    example: `Working from a double collar tie against the cage, a fighter lands three body knees in quick succession, then, as the opponent's head drops further trying to avoid them, lands a fourth knee to the head, forcing the referee to step in and check the fighter's condition.`,
    misunderstandings: `A common one: assuming clinch knees are simply desperate, close-range flailing rather than a technical weapon. They are a heavily developed, deliberately trained part of the striking game, especially for fighters from a Muay Thai background, not an improvised substitute for striking at range.`,
    related: [
      'double-collar-tie-thai-clinch',
      'collar-tie',
      'clinch-elbows',
      'mma-clinch-explained',
    ],
  }),

  technique({
    slug: 'clinch-elbows',
    title: 'Clinch Elbows',
    category: 'clinch',
    aliases: ['clinch elbows', 'elbows in the clinch', 'short elbows'],
    summary: 'Short elbow strikes thrown at close range within a clinch, often opening cuts.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-muay-thai-clinch' }],
    recognition: `A fighter controlling an opponent's head or upper body at close range throws a short, compact strike with the point of the elbow rather than a full-range punch or kick, most often aimed at the head, and frequently opens a visible cut even from a shot with relatively little travel distance.`,
    theTechnique: `**Clinch elbows** are elbow strikes thrown at very close range, usually while a fighter maintains some grip control over the opponent's posture, using the short distance the clinch creates rather than the fuller arcing motion an elbow can carry at slightly longer range. Because the elbow is a hard, bony striking surface delivered over a short distance, clinch elbows are particularly associated with cuts, even when they do not produce an immediate knockdown.`,
    whenUsed: `Clinch elbows are typically thrown when a fighter has enough control, often a collar tie or an underhook, to keep the opponent's head in range without them pulling away, and are especially effective against the cage, where the opponent has limited room to create distance.`,
    risks: `Because they are thrown from very close range while a grip is maintained, an elbow that misses or is only partially controlled can leave a fighter's own head momentarily exposed, and overcommitting to elbows can cost a fighter the underlying grip battle if their attention shifts fully to striking.`,
    counters: `A defending fighter can tuck their chin and turn their head away from the strike's path, fight to control the attacking fighter's head or wrist to disrupt the strike before it lands, or work to break the clinch and create range entirely.`,
    example: `Controlling the opponent's head with a collar tie against the cage, a fighter throws two short elbows in succession. The second opens a cut above the opponent's eyebrow, and the ringside doctor is called in between rounds to assess whether the fight can continue, even though neither elbow visibly staggered the opponent.`,
    misunderstandings: `A common one: assuming an elbow that doesn't produce a knockdown was ineffective. Clinch elbows are frequently damaging specifically through cuts rather than through concussive force, and a fight can be stopped by a doctor over accumulated elbow cuts even without a single moment that looked, to a casual viewer, like a fight-changing blow.`,
    related: ['clinch-knees', 'collar-tie', 'doctor-stoppage', 'mma-clinch-explained'],
  }),

  standard({
    slug: 'cage-clinch',
    title: 'Cage Clinch',
    category: 'clinch',
    alsoIn: ['cage-wrestling'],
    aliases: ['cage clinch', 'clinch against the cage', 'fence clinch'],
    summary:
      'A standing clinch fought with one fighter’s back against the cage, changing what both fighters can do.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-mma-clinch' }],
    explanation: `A **cage clinch** is a standing clinch exchange fought with one fighter's back against the cage, a situation with no real equivalent in a ring-based combat sport, where a fighter backed to the ropes generally has room to circle off along them rather than being pinned flat. Against a cage, the fighter with their back to it has one whole direction of escape removed entirely.`,
    howItWorks: `The fighter controlling the clinch typically uses the cage to remove the opponent's retreat, pressing them flat against it rather than allowing them to circle away, which makes takedowns, knees and short strikes all easier to land than in open-space clinch. The fighter with their back to the cage, meanwhile, has to work specifically to create an angle or turn the position, since simply backing up further is not an option.`,
    example: `Pressed against the cage in a collar tie, a fighter with their back to the fence works to turn their hips and create an angle rather than trying to back straight out, since backing straight out is impossible with the cage directly behind them; turning is the only route back to open space.`,
    whyItMatters: `A large amount of MMA's cage-specific tactics, from cage wrestling to certain striking combinations, exist specifically because the cage removes a direction of movement a ring-based sport's ropes do not, which is why the same clinch exchange can look and resolve very differently near the centre of the cage versus flat against it.`,
    misunderstandings: `A common one: treating time against the cage as automatically bad for the fighter whose back is to it. A well-schooled fighter can defend effectively from there, use the cage themselves to stay upright against a takedown, and look for angles to escape, so cage time is a genuinely contested position, not an automatic loss.`,
    related: ['wall-wrestling', 'body-lock', 'wrestling-against-the-cage', 'mma-clinch-explained'],
  }),

  standard({
    slug: 'wall-wrestling',
    title: 'Wall Wrestling',
    category: 'clinch',
    alsoIn: ['cage-wrestling'],
    aliases: ['wall wrestling', 'fence wrestling', 'cage wall control'],
    summary:
      'The specific skill of controlling, escaping or fighting within a clinch pinned against the cage wall.',
    difficulty: 'advanced',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-wrestling' }],
    explanation: `**Wall wrestling** is the specific set of skills built around a clinch fought with a fighter pinned against the cage, distinct enough from open-space clinch or wrestling that it is often trained and discussed as its own subject. It covers both sides of the exchange: using the wall to control an opponent, and defending or escaping a position when it is your own back against it.`,
    howItWorks: `For the fighter doing the controlling, wall wrestling means using the cage to remove an opponent's retreat while working takedowns, strikes or sustained positional control that would be far harder to hold in open space. For the fighter with their back to the cage, it means specific defensive tools: framing off the opponent to create space, turning to find an angle along the cage rather than trying to move straight back, and timing a push-off or a takedown attempt of their own once an opening appears.`,
    example: `A fighter repeatedly walks an opponent down and pins them against the cage over several exchanges, not necessarily finishing a takedown each time, but accumulating control time and short strikes that add up meaningfully across a round, purely through effective wall wrestling rather than any single dramatic technique.`,
    whyItMatters: `Wall wrestling is frequently decisive in rounds that look close on paper, since sustained cage control and the associated strikes are explicitly part of what judges are instructed to weigh, meaning a fighter who wins the wall-wrestling exchanges can win a round even without a takedown or a clean finish to show for it.`,
    misunderstandings: `A common one: treating all cage time as equivalent, regardless of who is controlling it. A fighter pinned against the cage but actively defending well, framing, angling out, threatening their own offence, is in a very different position from one being simply held and struck without answer, even though both situations look similar at a glance.`,
    related: [
      'cage-clinch',
      'wrestling-against-the-cage',
      'body-lock-takedown',
      'how-mma-scoring-works',
    ],
  }),

  standard({
    slug: 'clinch-takedowns',
    title: 'Clinch Takedowns',
    category: 'clinch',
    aliases: ['clinch takedowns', 'takedowns from the clinch', 'takedown from clinch'],
    summary:
      'Takedowns completed from an established clinch grip, rather than from a standing shot at range.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-takedown' }, { key: 'wp-clinch-fighting' }],
    explanation: `**Clinch takedowns** are takedowns completed from an already-established clinch position, using grips like a body lock or double underhooks, rather than shooting in for the legs from a standing, separated position. They are a distinct family from leg-attack takedowns like the single-leg or double-leg, relying instead on upper-body control and off-balancing.`,
    howItWorks: `Once a fighter has secured a dominant clinch grip, particularly a body lock, they can look to complete a takedown through a trip, a hip throw, or simply driving the opponent's compromised base to the mat, without ever needing to change level and attack a leg directly. Because the setup work (winning the grip fight) has usually already happened by the time a clinch takedown is attempted, the finishing motion itself is often quicker and lower-risk than a takedown attempted from range.`,
    example: `After a lengthy pummeling exchange ends with a fighter securing a body lock against the cage, they complete the takedown with a trip rather than a leg attack, using the established grip and the opponent's already-compromised base rather than shooting in fresh.`,
    whyItMatters: `A fighter whose main takedown threat comes from the clinch, rather than from open-space shots, tends to fight very differently, working patiently to establish grips first, and recognising this shifts how a viewer should read a fighter who rarely shoots but frequently ends up completing takedowns anyway.`,
    misunderstandings: `A common one: assuming all takedowns are essentially the same "wrestling" skill. Clinch takedowns and leg-attack takedowns draw on different grip fighting, timing and off-balancing skills, and a fighter can be excellent at one family while being comparatively unpolished at the other.`,
    related: ['body-lock', 'body-lock-takedown', 'trip', 'hip-throw', 'takedown-explained'],
  }),

  standard({
    slug: 'breaking-the-clinch',
    title: 'Breaking the Clinch',
    category: 'clinch',
    aliases: ['breaking the clinch', 'clinch escape', 'separating from the clinch'],
    summary:
      'Creating enough space to return the fight to striking range after being controlled up close.',
    difficulty: 'intermediate',
    readMinutes: 3,
    sourceKeys: [{ key: 'wp-clinch-fighting' }, { key: 'wp-mma-clinch' }],
    explanation: `**Breaking the clinch** describes the deliberate act of creating enough separation to return a fight from close-range clinch contact back to striking range, whether by a fighter escaping unfavourable control or by mutual agreement once neither fighter is accomplishing much at close range. Unlike boxing, where a referee will often actively separate fighters in a stalled clinch, MMA generally leaves the responsibility to break with the fighters themselves, since a clinch remains a live, contestable phase rather than dead time.`,
    howItWorks: `A fighter looking to break the clinch typically needs to first neutralise whatever control is being used against them, freeing a trapped arm, creating a frame with a forearm against the opponent's chest or head, or pushing off the cage, before actually stepping back to a safe striking distance. Breaking carelessly, simply shoving away without controlling the opponent's hands first, can expose a fighter to a clean strike the instant separation happens.`,
    example: `Controlled against the cage for an extended exchange, a fighter finally frees an underhook, uses it to create a small angle, and pushes off cleanly to re-establish striking range, immediately resetting their stance rather than backing away carelessly and risking being caught leaving.`,
    whyItMatters: `How cleanly a fighter can break a clinch on their own terms is part of what determines whether time spent controlled against the cage costs them anything beyond that moment, since a poor break can hand the other fighter a free strike just as the position seems to be improving.`,
    misunderstandings: `A common one: assuming a referee will step in to separate a stalled clinch the way one does in boxing. MMA referees generally only intervene to reset a clinch if genuinely nothing is happening from either fighter for a sustained period; otherwise, breaking is left entirely to the fighters themselves as an active, contestable part of the fight.`,
    related: ['mma-clinch-explained', 'underhook', 'cage-clinch', 'wall-wrestling'],
  }),
];
