import type { ExplainerCategorySeed, ExplainerSeed } from './explainer-types';

/**
 * The tennis taxonomy: the categories, and every concept the library intends to
 * cover.
 *
 * Everything in this file is a draft placeholder. Nothing here reaches the
 * site. The written explainers live in the `tennis-*.ts` content files and
 * override these by slug, which is why the slugs here have to be right first
 * time: a typo produces a second concept rather than a written version of the
 * first.
 *
 * ## On categories
 *
 * The brief names twenty groupings. Twenty headings on a landing page is a
 * directory rather than a structure, so the categories are ordered and the
 * landing page leads with the first eight; the rest are real categories with
 * real URLs, reachable from a breadcrumb and from search. That is the same
 * arrangement basketball uses and for the same reason: the taxonomy should grow
 * without either hiding concepts or turning the front page into a list of
 * lists.
 *
 * Several of the brief's groupings collapse here, because they name the same
 * concepts twice. "Serving Rules" and "The Court & Lines" are one category in
 * the reader's head the moment they see that both are answered by the same
 * diagram, and "Seeding & Draws" is where the tournament category's draw
 * entries already point. Where a concept genuinely belongs to two groupings it
 * is one row with `alsoIn`, never two rows: the unique index on
 * (sport_id, slug) makes that a guarantee rather than a convention.
 *
 * ## On the tours
 *
 * There is no "ATP" category and no "WTA" category. The tours differ on rules,
 * ranking mechanics and tournament tiers, and the temptation is to write
 * `atp-rankings` and `wta-rankings` as separate articles. They would agree on
 * most of it and disagree on the parts that matter, and a reader searching
 * "ranking points" would have to pick a tour before they could read anything.
 * So each concept is one page with the divergence in a `rule_differences`
 * section of it, and where the tours genuinely run different machinery (the
 * 1000/500/250 tiers, the Race) the concept is named for the mechanism rather
 * than for a tour.
 *
 * The corollary matters just as much: where a general description would be
 * wrong for one tour, the section is not optional. An explainer that describes
 * only the men's game and says nothing teaches a reader that the ATP's rules
 * are tennis's rules, which is the failure mode this library exists to avoid.
 */

export const TENNIS_EXPLAINER_CATEGORIES: ExplainerCategorySeed[] = [
  {
    slug: 'start-here',
    name: 'Start Here',
    shortName: 'Start',
    description: 'Tennis from zero: how a match is played, won, structured and watched.',
    order: 10,
  },
  {
    slug: 'scoring',
    name: 'Scoring & Match Rules',
    shortName: 'Scoring',
    description: 'Points, games, sets, tiebreaks, and why the numbers go 15, 30, 40.',
    order: 20,
  },
  {
    slug: 'serving',
    name: 'Serving',
    description: 'The one shot every point starts with, and every rule around it.',
    order: 30,
  },
  {
    slug: 'court',
    name: 'The Court & Lines',
    shortName: 'Court',
    description: 'Every line on the court, what it decides, and when a ball is out.',
    order: 40,
  },
  {
    slug: 'shots',
    name: 'Shots & Technique',
    shortName: 'Shots',
    description: 'Every stroke in the game: what it does, when it is chosen, what it costs.',
    order: 50,
  },
  {
    slug: 'tactics',
    name: 'Tactics',
    description: 'How points are built, where players aim, and why.',
    order: 60,
  },
  {
    slug: 'surfaces',
    name: 'Court Surfaces',
    shortName: 'Surfaces',
    description: 'Hard, clay and grass: how the ground changes the sport played on it.',
    order: 70,
  },
  {
    slug: 'tournaments',
    name: 'Tournaments',
    description: 'Draws, tiers, majors, qualifying, and every way a match can end early.',
    order: 80,
  },
  /*
   * Below the fold.
   *
   * Real categories with real URLs, reachable from a concept's breadcrumb and
   * from search, but not among the eight the landing page leads with. This is
   * how a twenty-category taxonomy stays navigable.
   */
  {
    slug: 'rankings',
    name: 'Rankings',
    description: 'How points are earned, defended and lost, and what No. 1 actually means.',
    order: 90,
  },
  {
    slug: 'seeding-and-draws',
    name: 'Seeding & Draws',
    shortName: 'Seeding',
    description: 'Why the best players are kept apart, and how a bracket is built.',
    order: 100,
  },
  {
    slug: 'statistics',
    name: 'Match Statistics',
    shortName: 'Stats',
    description: 'How to read a stat sheet, and which numbers mislead.',
    order: 110,
  },
  {
    slug: 'grand-slams',
    name: 'Grand Slam Concepts',
    shortName: 'Slams',
    description: 'Career, calendar and golden slams, and why all four majors is so hard.',
    order: 120,
  },
  {
    slug: 'doubles',
    name: 'Doubles',
    description: 'A different sport on the same court: formations, order and net play.',
    order: 130,
  },
  {
    slug: 'officiating',
    name: 'Officiating & Technology',
    shortName: 'Officiating',
    description: 'Who calls what, how line calling works, and the penalty system.',
    order: 140,
  },
  {
    slug: 'equipment',
    name: 'Equipment',
    description: 'Rackets, strings, balls and shoes, and the trade-offs behind each.',
    order: 150,
  },
  {
    slug: 'conditions',
    name: 'Conditions & Physics',
    shortName: 'Conditions',
    description: 'Wind, heat, altitude and spin: why the same shot behaves differently.',
    order: 160,
  },
  {
    slug: 'playing-styles',
    name: 'Playing Styles',
    shortName: 'Styles',
    description: 'Baseliners, counterpunchers, serve-and-volleyers, and what beats each.',
    order: 170,
  },
  {
    slug: 'careers',
    name: 'Player Careers',
    shortName: 'Careers',
    description: 'The pathway from juniors to the tour, and the economics underneath it.',
    order: 180,
  },
  {
    slug: 'advanced',
    name: 'Advanced Concepts',
    shortName: 'Advanced',
    description: 'Elo, hold and break rates, dominance ratio, and where the data comes from.',
    order: 190,
  },
  {
    slug: 'glossary',
    name: 'Glossary',
    description: 'Every term, A to Z, in a sentence or three.',
    order: 200,
  },
];

/**
 * Every concept the tennis library intends to cover.
 *
 * Slugs are the URL forever, so they are written as a reader would search
 * rather than as a heading would read: `tiebreak`, not `what-is-a-tiebreak`.
 * The question form belongs in the title and in the aliases, which is what the
 * search index matches on.
 */
export const TENNIS_EXPLAINER_TOPICS: ExplainerSeed[] = [
  // ── Start here ─────────────────────────────────────────────────────────────
  {
    slug: 'tennis-in-five-minutes',
    title: 'Tennis in 5 Minutes',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-a-tennis-match-works',
    title: 'How a Tennis Match Works',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'singles-vs-doubles',
    title: 'Singles vs Doubles',
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'how-you-win-a-tennis-match',
    title: 'How Do You Win a Tennis Match?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'understanding-the-tennis-court',
    title: 'Understanding the Tennis Court',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'tennis-match-formats',
    title: 'Tennis Match Formats',
    type: 'format',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'mens-vs-womens-tennis',
    title: "Men's vs Women's Professional Tennis",
    type: 'standard',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'atp-wta-itf',
    title: 'ATP vs WTA vs ITF',
    type: 'format',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'the-grand-slams',
    title: 'What Are the Grand Slams?',
    type: 'format',
    difficulty: 'beginner',
    category: 'start-here',
  },
  {
    slug: 'the-tennis-season',
    title: 'How the Tennis Season Works',
    type: 'format',
    difficulty: 'beginner',
    category: 'start-here',
  },

  // ── Scoring & match rules ──────────────────────────────────────────────────
  {
    slug: 'tennis-scoring',
    title: 'Tennis Scoring Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'why-fifteen-thirty-forty',
    title: 'Why Tennis Uses 15, 30 and 40',
    type: 'standard',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'love',
    title: 'What Is Love?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'deuce',
    title: 'What Is Deuce?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'advantage',
    title: 'What Is Advantage?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'games-sets-and-matches',
    title: 'Games, Sets and Matches Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'how-you-win-a-set',
    title: 'How Do You Win a Set?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'tiebreak',
    title: 'What Is a Tiebreak?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'how-a-tiebreak-works',
    title: 'How Does a Tiebreak Work?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'match-tiebreak',
    title: 'What Is a Match Tiebreak?',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'scoring',
  },
  {
    slug: 'best-of-three-vs-best-of-five',
    title: 'Best-of-Three vs Best-of-Five',
    type: 'format',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'hold-serve',
    title: 'What Does "Hold Serve" Mean?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'break-of-serve',
    title: 'What Is a Break of Serve?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'break-point',
    title: 'What Is a Break Point?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'set-point-match-point-championship-point',
    title: 'Set Point vs Match Point vs Championship Point',
    type: 'definition',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'bagel',
    title: 'What Is a Bagel?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'scoring',
  },
  {
    slug: 'breadstick',
    title: 'What Is a Breadstick?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'scoring',
  },

  // ── Serving ────────────────────────────────────────────────────────────────
  {
    slug: 'how-serving-works',
    title: 'How Serving Works',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'first-serve-vs-second-serve',
    title: 'First Serve vs Second Serve',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'ace',
    title: 'What Is an Ace?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'service-winner',
    title: 'What Is a Service Winner?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'fault',
    title: 'What Is a Fault?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'double-fault',
    title: 'What Is a Double Fault?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'let',
    title: 'What Is a Let?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'where-a-serve-must-land',
    title: 'Where Must a Serve Land?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'serving-order',
    title: 'Serving Order Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'changing-ends',
    title: 'Changing Ends Explained',
    type: 'rule',
    difficulty: 'beginner',
    category: 'serving',
  },
  {
    slug: 'foot-fault',
    title: 'Foot Fault Explained',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'serving',
  },
  {
    slug: 'serving-in-a-tiebreak',
    title: 'How Serving Works in a Tiebreak',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'serving',
  },

  // ── The court & lines ──────────────────────────────────────────────────────
  {
    slug: 'tennis-court',
    title: 'Tennis Court Explained',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'singles-court-vs-doubles-court',
    title: 'Singles Court vs Doubles Court',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'baseline',
    title: 'Baseline Explained',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'service-boxes',
    title: 'Service Boxes Explained',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'doubles-alleys',
    title: 'Doubles Alleys Explained',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'ball-on-the-line',
    title: 'What Happens When the Ball Hits the Line?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'ball-hits-the-net',
    title: 'What Happens When the Ball Hits the Net?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'when-is-a-ball-out',
    title: 'When Is a Ball Out?',
    type: 'rule',
    difficulty: 'beginner',
    category: 'court',
  },
  {
    slug: 'net-rules',
    title: 'Net Rules',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'court',
  },
  {
    slug: 'ad-court-and-deuce-court',
    title: 'Deuce Court and Ad Court',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'court',
  },

  // ── Shots & technique ──────────────────────────────────────────────────────
  {
    slug: 'forehand',
    title: 'Forehand Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'backhand',
    title: 'Backhand Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'one-handed-vs-two-handed-backhand',
    title: 'One-Handed vs Two-Handed Backhand',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'the-serve',
    title: 'Serve Explained',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'return-of-serve',
    title: 'Return of Serve',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  { slug: 'volley', title: 'Volley', type: 'shot', difficulty: 'beginner', category: 'shots' },
  {
    slug: 'half-volley',
    title: 'Half Volley',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'overhead-smash',
    title: 'Overhead / Smash',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'drop-shot',
    title: 'Drop Shot',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  { slug: 'lob', title: 'Lob', type: 'shot', difficulty: 'beginner', category: 'shots' },
  { slug: 'slice', title: 'Slice', type: 'shot', difficulty: 'intermediate', category: 'shots' },
  {
    slug: 'topspin',
    title: 'Topspin',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'flat-shot',
    title: 'Flat Shot',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'passing-shot',
    title: 'Passing Shot',
    type: 'shot',
    difficulty: 'beginner',
    category: 'shots',
  },
  {
    slug: 'approach-shot',
    title: 'Approach Shot',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'inside-out-forehand',
    title: 'Inside-Out Forehand',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'inside-in-forehand',
    title: 'Inside-In Forehand',
    type: 'shot',
    difficulty: 'advanced',
    category: 'shots',
  },
  {
    slug: 'kick-serve',
    title: 'Kick Serve',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'slice-serve',
    title: 'Slice Serve',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },
  {
    slug: 'flat-serve',
    title: 'Flat Serve',
    type: 'shot',
    difficulty: 'intermediate',
    category: 'shots',
  },

  // ── Playing styles ─────────────────────────────────────────────────────────
  {
    slug: 'baseline-player',
    title: 'Baseline Player',
    type: 'playing_style',
    difficulty: 'beginner',
    category: 'playing-styles',
  },
  {
    slug: 'aggressive-baseliner',
    title: 'Aggressive Baseliner',
    type: 'playing_style',
    difficulty: 'intermediate',
    category: 'playing-styles',
  },
  {
    slug: 'counterpuncher',
    title: 'Counterpuncher',
    type: 'playing_style',
    difficulty: 'intermediate',
    category: 'playing-styles',
  },
  {
    slug: 'serve-and-volley',
    title: 'Serve-and-Volley Player',
    type: 'playing_style',
    difficulty: 'intermediate',
    category: 'playing-styles',
  },
  {
    slug: 'all-court-player',
    title: 'All-Court Player',
    type: 'playing_style',
    difficulty: 'intermediate',
    category: 'playing-styles',
  },
  {
    slug: 'big-server',
    title: 'Big Server',
    type: 'playing_style',
    difficulty: 'beginner',
    category: 'playing-styles',
  },
  {
    slug: 'defensive-player',
    title: 'Defensive Player',
    type: 'playing_style',
    difficulty: 'beginner',
    category: 'playing-styles',
  },
  {
    slug: 'offensive-player',
    title: 'Offensive Player',
    type: 'playing_style',
    difficulty: 'beginner',
    category: 'playing-styles',
  },
  {
    slug: 'playing-from-the-baseline',
    title: 'What Does "Playing From the Baseline" Mean?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'playing-styles',
  },
  {
    slug: 'coming-to-the-net',
    title: 'What Does "Coming to the Net" Mean?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'playing-styles',
  },

  // ── Tactics ────────────────────────────────────────────────────────────────
  {
    slug: 'targeting-the-backhand',
    title: 'Why Players Target the Backhand',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'crosscourt-vs-down-the-line',
    title: 'Playing Crosscourt vs Down the Line',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'changing-direction',
    title: 'Changing Direction of the Ball',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'tactics',
  },
  {
    slug: 'using-angles',
    title: 'Using Angles',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'court-positioning',
    title: 'Court Positioning',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'taking-the-ball-early',
    title: 'Taking the Ball Early',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'tactics',
  },
  {
    slug: 'playing-behind-an-opponent',
    title: 'Playing Behind an Opponent',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'tactics',
  },
  {
    slug: 'serve-plus-one',
    title: 'Serve + 1 Strategy',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'return-positioning',
    title: 'Return Positioning',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'attacking-second-serves',
    title: 'Attacking Second Serves',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'building-a-point',
    title: 'Building a Point',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'defence-to-offence',
    title: 'Defensive-to-Offensive Transition',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'tactics',
  },
  {
    slug: 'approaching-the-net',
    title: 'Why Players Approach the Net',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'tactics',
  },
  {
    slug: 'creating-break-point-pressure',
    title: 'How Players Create Break-Point Pressure',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'tactics',
  },
  {
    slug: 'patterns-of-play',
    title: 'Pattern of Play Explained',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'tactics',
  },
  {
    slug: 'adapting-during-a-match',
    title: 'How Players Adapt During Matches',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'tactics',
  },

  // ── Surfaces ───────────────────────────────────────────────────────────────
  {
    slug: 'tennis-court-surfaces',
    title: 'Tennis Court Surfaces Explained',
    type: 'surface',
    difficulty: 'beginner',
    category: 'surfaces',
  },
  {
    slug: 'hard-courts',
    title: 'Hard Courts Explained',
    type: 'surface',
    difficulty: 'beginner',
    category: 'surfaces',
  },
  {
    slug: 'clay-courts',
    title: 'Clay Courts Explained',
    type: 'surface',
    difficulty: 'beginner',
    category: 'surfaces',
  },
  {
    slug: 'grass-courts',
    title: 'Grass Courts Explained',
    type: 'surface',
    difficulty: 'beginner',
    category: 'surfaces',
  },
  {
    slug: 'why-clay-is-slower',
    title: 'Why Clay Is Slower',
    type: 'surface',
    difficulty: 'intermediate',
    category: 'surfaces',
  },
  {
    slug: 'why-grass-plays-differently',
    title: 'Why Grass Plays Differently',
    type: 'surface',
    difficulty: 'intermediate',
    category: 'surfaces',
  },
  {
    slug: 'surface-and-bounce',
    title: 'How Surface Changes Ball Bounce',
    type: 'surface',
    difficulty: 'intermediate',
    category: 'surfaces',
  },
  {
    slug: 'surface-and-movement',
    title: 'How Surface Changes Movement',
    type: 'surface',
    difficulty: 'intermediate',
    category: 'surfaces',
  },
  {
    slug: 'surface-and-serve',
    title: 'How Surface Affects the Serve',
    type: 'surface',
    difficulty: 'intermediate',
    category: 'surfaces',
  },
  {
    slug: 'surface-dominance',
    title: 'Why Some Players Dominate Certain Surfaces',
    type: 'surface',
    difficulty: 'intermediate',
    category: 'surfaces',
  },
  {
    slug: 'surface-specialist',
    title: 'What Is a Surface Specialist?',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'surfaces',
  },
  {
    slug: 'indoor-vs-outdoor',
    title: 'Indoor vs Outdoor Tennis',
    type: 'surface',
    difficulty: 'intermediate',
    category: 'surfaces',
  },

  // ── Tournaments ────────────────────────────────────────────────────────────
  {
    slug: 'how-tournaments-work',
    title: 'How Tennis Tournaments Work',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'tournament-draw',
    title: 'What Is a Tournament Draw?',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'knockout-format',
    title: 'Knockout Format Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'grand-slam-vs-tour-event',
    title: 'Grand Slam vs Regular Tour Event',
    type: 'format',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'atp-masters-1000',
    title: 'ATP Masters 1000 Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'atp-500',
    title: 'ATP 500 Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'atp-250',
    title: 'ATP 250 Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'atp-challenger-tour',
    title: 'ATP Challenger Tour Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'itf-world-tennis-tour',
    title: 'ITF World Tennis Tour Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'wta-1000',
    title: 'WTA 1000 Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'wta-500',
    title: 'WTA 500 Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'wta-250',
    title: 'WTA 250 Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'wta-125',
    title: 'WTA 125 Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'atp-finals',
    title: 'ATP Finals Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'wta-finals',
    title: 'WTA Finals Explained',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'how-players-qualify-for-tournaments',
    title: 'How Players Qualify for Tournaments',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'main-draw-vs-qualifying',
    title: 'Main Draw vs Qualifying',
    type: 'format',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'qualifier',
    title: 'What Is a Qualifier?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'wild-card',
    title: 'What Is a Wild Card?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'lucky-loser',
    title: 'What Is a Lucky Loser?',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'tournaments',
  },
  {
    slug: 'alternate',
    title: 'What Is an Alternate?',
    type: 'definition',
    difficulty: 'advanced',
    category: 'tournaments',
  },
  {
    slug: 'bye',
    title: 'What Does "Bye" Mean?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'walkover',
    title: 'What Is a Walkover?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'retirement',
    title: 'What Is a Retirement?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'tournaments',
  },
  {
    slug: 'default',
    title: 'What Is a Default?',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'tournaments',
  },

  // ── Rankings ───────────────────────────────────────────────────────────────
  {
    slug: 'atp-rankings',
    title: 'ATP Rankings Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'wta-rankings',
    title: 'WTA Rankings Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'earning-ranking-points',
    title: 'How Tennis Players Earn Ranking Points',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'losing-ranking-points',
    title: 'Why Players Lose Ranking Points',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'points-vs-prize-money',
    title: 'Ranking Points vs Prize Money',
    type: 'ranking_concept',
    difficulty: 'beginner',
    category: 'rankings',
  },
  {
    slug: 'world-number-one',
    title: 'What Does World No. 1 Mean?',
    type: 'ranking_concept',
    difficulty: 'beginner',
    category: 'rankings',
  },
  {
    slug: 'becoming-world-number-one',
    title: 'How Players Become World No. 1',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'year-end-number-one',
    title: 'What Is a Year-End No. 1?',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'defending-points',
    title: 'What Does "Defending Points" Mean?',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'rankings-and-tournament-entry',
    title: 'How Rankings Affect Tournament Entry',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'protected-ranking',
    title: 'What Is a Protected Ranking?',
    type: 'ranking_concept',
    difficulty: 'advanced',
    category: 'rankings',
  },
  {
    slug: 'career-high-ranking',
    title: 'What Is a Career-High Ranking?',
    type: 'definition',
    difficulty: 'beginner',
    category: 'rankings',
  },
  {
    slug: 'ranking-vs-race',
    title: 'Ranking vs Race Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'atp-race',
    title: 'ATP Race Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'wta-race',
    title: 'WTA Race Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },
  {
    slug: 'qualifying-for-the-finals',
    title: 'How Players Qualify for the ATP and WTA Finals',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'rankings',
  },

  // ── Seeding & draws ────────────────────────────────────────────────────────
  {
    slug: 'seed',
    title: 'What Is a Seed?',
    type: 'format',
    difficulty: 'beginner',
    category: 'seeding-and-draws',
  },
  {
    slug: 'why-tournaments-have-seeds',
    title: 'Why Tournaments Have Seeds',
    type: 'format',
    difficulty: 'beginner',
    category: 'seeding-and-draws',
  },
  {
    slug: 'ranking-vs-seeding',
    title: 'Ranking vs Seeding',
    type: 'format',
    difficulty: 'intermediate',
    category: 'seeding-and-draws',
  },
  {
    slug: 'how-draws-work',
    title: 'How Tournament Draws Work',
    type: 'format',
    difficulty: 'intermediate',
    category: 'seeding-and-draws',
  },
  {
    slug: 'separating-top-seeds',
    title: 'Why Top Seeds Are Separated',
    type: 'format',
    difficulty: 'intermediate',
    category: 'seeding-and-draws',
  },
  {
    slug: 'seeded-vs-unseeded',
    title: 'Seeded vs Unseeded Players',
    type: 'definition',
    difficulty: 'beginner',
    category: 'seeding-and-draws',
  },
  {
    slug: 'draw-ceremony',
    title: 'What Is a Draw Ceremony?',
    type: 'format',
    difficulty: 'beginner',
    category: 'seeding-and-draws',
  },
  {
    slug: 'qualifying-draw',
    title: 'What Is a Qualifying Draw?',
    type: 'format',
    difficulty: 'intermediate',
    category: 'seeding-and-draws',
  },
  {
    slug: 'top-players-meeting-early',
    title: 'Why Can Two Top Players Meet Before the Final?',
    type: 'format',
    difficulty: 'intermediate',
    category: 'seeding-and-draws',
  },

  // ── Match statistics ───────────────────────────────────────────────────────
  {
    slug: 'tennis-statistics',
    title: 'Tennis Statistics Explained',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'first-serve-percentage',
    title: 'First Serve Percentage',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'first-serve-points-won',
    title: 'First Serve Points Won',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'second-serve-points-won',
    title: 'Second Serve Points Won',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'aces-statistic',
    title: 'Aces as a Statistic',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'double-faults-statistic',
    title: 'Double Faults as a Statistic',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'winners',
    title: 'Winners',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'unforced-errors',
    title: 'Unforced Errors',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'break-points-won',
    title: 'Break Points Won',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'break-points-saved',
    title: 'Break Points Saved',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'return-points-won',
    title: 'Return Points Won',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'net-points-won',
    title: 'Net Points Won',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'total-points-won',
    title: 'Total Points Won',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'why-total-points-mislead',
    title: 'Why Total Points Won Can Be Misleading',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'serve-speed',
    title: 'Serve Speed',
    type: 'statistic',
    difficulty: 'beginner',
    category: 'statistics',
  },
  {
    slug: 'rally-length',
    title: 'Rally Length',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'forced-vs-unforced-errors',
    title: 'Forced vs Unforced Errors',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },
  {
    slug: 'reading-a-stat-sheet',
    title: 'How to Read a Tennis Match Stat Sheet',
    type: 'statistic',
    difficulty: 'intermediate',
    category: 'statistics',
  },

  // ── Grand slam concepts ────────────────────────────────────────────────────
  {
    slug: 'why-grand-slams-matter',
    title: 'Why Grand Slams Matter',
    type: 'format',
    difficulty: 'beginner',
    category: 'grand-slams',
  },
  {
    slug: 'career-grand-slam',
    title: 'Career Grand Slam',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'grand-slams',
  },
  {
    slug: 'calendar-grand-slam',
    title: 'Calendar Grand Slam',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'grand-slams',
  },
  {
    slug: 'non-calendar-grand-slam',
    title: 'Non-Calendar Grand Slam',
    type: 'definition',
    difficulty: 'advanced',
    category: 'grand-slams',
  },
  {
    slug: 'golden-slam',
    title: 'Golden Slam',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'grand-slams',
  },
  {
    slug: 'career-golden-slam',
    title: 'Career Golden Slam',
    type: 'definition',
    difficulty: 'intermediate',
    category: 'grand-slams',
  },
  {
    slug: 'surface-slam',
    title: 'Surface Slam',
    type: 'definition',
    difficulty: 'advanced',
    category: 'grand-slams',
  },
  {
    slug: 'channel-slam',
    title: 'Channel Slam',
    type: 'definition',
    difficulty: 'advanced',
    category: 'grand-slams',
  },
  {
    slug: 'slam-title-vs-tour-title',
    title: 'Grand Slam Title vs Tour Title',
    type: 'format',
    difficulty: 'beginner',
    category: 'grand-slams',
  },
  {
    slug: 'why-all-four-majors-is-hard',
    title: 'Why Winning All Four Majors Is So Difficult',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'grand-slams',
  },

  // ── Doubles ────────────────────────────────────────────────────────────────
  {
    slug: 'how-doubles-works',
    title: 'How Doubles Tennis Works',
    type: 'rule',
    difficulty: 'beginner',
    category: 'doubles',
  },
  {
    slug: 'doubles-court',
    title: 'Doubles Court Explained',
    type: 'court_area',
    difficulty: 'beginner',
    category: 'doubles',
  },
  {
    slug: 'doubles-serving-order',
    title: 'Doubles Serving Order',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'doubles',
  },
  {
    slug: 'doubles-return-order',
    title: 'Doubles Return Order',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'doubles',
  },
  {
    slug: 'doubles-positioning',
    title: 'Doubles Positioning',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'doubles',
  },
  {
    slug: 'net-play-in-doubles',
    title: 'Why Net Play Is Important in Doubles',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'doubles',
  },
  {
    slug: 'poaching',
    title: 'What Is Poaching?',
    type: 'tactical_concept',
    difficulty: 'intermediate',
    category: 'doubles',
  },
  {
    slug: 'australian-formation',
    title: 'Australian Formation',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'doubles',
  },
  {
    slug: 'i-formation',
    title: 'I-Formation',
    type: 'tactical_concept',
    difficulty: 'advanced',
    category: 'doubles',
  },
  {
    slug: 'doubles-tiebreak-rules',
    title: 'Doubles Tiebreak Rules',
    type: 'rule',
    difficulty: 'intermediate',
    category: 'doubles',
  },
  {
    slug: 'mixed-doubles',
    title: 'Mixed Doubles Explained',
    type: 'format',
    difficulty: 'beginner',
    category: 'doubles',
  },

  // ── Officiating & technology ───────────────────────────────────────────────
  {
    slug: 'who-officiates-a-match',
    title: 'Who Officiates a Tennis Match?',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'officiating',
  },
  {
    slug: 'chair-umpire',
    title: 'Chair Umpire Explained',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'officiating',
  },
  {
    slug: 'line-judges',
    title: 'Line Judges Explained',
    type: 'officiating',
    difficulty: 'beginner',
    category: 'officiating',
  },
  {
    slug: 'electronic-line-calling',
    title: 'Electronic Line Calling Explained',
    type: 'technology',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'hawk-eye',
    title: 'Hawk-Eye Explained',
    type: 'technology',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'player-challenges',
    title: 'Player Challenges Explained',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'code-violations',
    title: 'Code Violations',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'time-violations',
    title: 'Time Violations',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'coaching-rules',
    title: 'Coaching Rules',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'medical-timeouts',
    title: 'Medical Timeouts',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'bathroom-break-rules',
    title: 'Bathroom Break Rules',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'racket-and-ball-abuse',
    title: 'Ball Abuse and Racket Abuse Penalties',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'point-penalty-system',
    title: 'Point Penalty System',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },
  {
    slug: 'when-a-player-is-defaulted',
    title: 'When Can a Player Be Defaulted?',
    type: 'officiating',
    difficulty: 'intermediate',
    category: 'officiating',
  },

  // ── Equipment ──────────────────────────────────────────────────────────────
  {
    slug: 'tennis-racket',
    title: 'Tennis Racket Explained',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'equipment',
  },
  {
    slug: 'racket-head-size',
    title: 'Racket Head Size',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'equipment',
  },
  {
    slug: 'racket-weight',
    title: 'Racket Weight',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'equipment',
  },
  {
    slug: 'string-tension',
    title: 'String Tension',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'equipment',
  },
  {
    slug: 'tennis-strings',
    title: 'Tennis Strings Explained',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'equipment',
  },
  {
    slug: 'why-string-setups-differ',
    title: 'Why Players Use Different String Setups',
    type: 'equipment',
    difficulty: 'advanced',
    category: 'equipment',
  },
  {
    slug: 'tennis-balls',
    title: 'Tennis Balls Explained',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'equipment',
  },
  {
    slug: 'why-balls-are-changed',
    title: 'Why Tennis Balls Are Changed During Matches',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'equipment',
  },
  {
    slug: 'tennis-shoes-by-surface',
    title: 'Tennis Shoes by Surface',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'equipment',
  },
  {
    slug: 'clay-court-shoes',
    title: 'Why Clay-Court Shoes Are Different',
    type: 'equipment',
    difficulty: 'intermediate',
    category: 'equipment',
  },
  {
    slug: 'overgrips',
    title: 'Overgrips Explained',
    type: 'equipment',
    difficulty: 'beginner',
    category: 'equipment',
  },

  // ── Conditions & physics ───────────────────────────────────────────────────
  {
    slug: 'wind-in-tennis',
    title: 'How Wind Affects Tennis',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'conditions',
  },
  {
    slug: 'heat-in-tennis',
    title: 'How Heat Affects Tennis',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'conditions',
  },
  {
    slug: 'humidity-in-tennis',
    title: 'How Humidity Affects Tennis',
    type: 'standard',
    difficulty: 'advanced',
    category: 'conditions',
  },
  {
    slug: 'altitude-in-tennis',
    title: 'Altitude and Tennis',
    type: 'standard',
    difficulty: 'advanced',
    category: 'conditions',
  },
  {
    slug: 'why-balls-fly-at-altitude',
    title: 'Why Tennis Balls Fly Faster at Altitude',
    type: 'standard',
    difficulty: 'advanced',
    category: 'conditions',
  },
  {
    slug: 'indoor-vs-outdoor-conditions',
    title: 'Indoor vs Outdoor Conditions',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'conditions',
  },
  {
    slug: 'day-vs-night-tennis',
    title: 'Day vs Night Tennis',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'conditions',
  },
  {
    slug: 'temperature-and-ball-speed',
    title: 'How Temperature Changes Ball Speed',
    type: 'standard',
    difficulty: 'advanced',
    category: 'conditions',
  },
  {
    slug: 'why-topspin-dips',
    title: 'Why Topspin Makes the Ball Dip',
    type: 'standard',
    difficulty: 'advanced',
    category: 'conditions',
  },
  {
    slug: 'why-slice-stays-low',
    title: 'Why Slice Stays Low',
    type: 'standard',
    difficulty: 'advanced',
    category: 'conditions',
  },
  {
    slug: 'ball-bounce',
    title: 'Tennis Ball Bounce Explained',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'conditions',
  },

  // ── Player careers ─────────────────────────────────────────────────────────
  {
    slug: 'how-tennis-careers-work',
    title: 'How Professional Tennis Careers Work',
    type: 'standard',
    difficulty: 'beginner',
    category: 'careers',
  },
  {
    slug: 'juniors-to-professional',
    title: 'Junior Tennis to Professional Tennis',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'careers',
  },
  {
    slug: 'the-tour-pathway',
    title: 'ITF to Challenger to ATP and WTA: the Pathway',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'careers',
  },
  {
    slug: 'entering-professional-tournaments',
    title: 'How Players Enter Professional Tournaments',
    type: 'format',
    difficulty: 'intermediate',
    category: 'careers',
  },
  {
    slug: 'ranking-cutoffs',
    title: 'Ranking Cutoffs Explained',
    type: 'ranking_concept',
    difficulty: 'intermediate',
    category: 'careers',
  },
  {
    slug: 'injury-comebacks',
    title: 'Injury Comebacks',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'careers',
  },
  {
    slug: 'dropping-down-the-rankings',
    title: 'What Happens When Players Drop Down the Rankings?',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'careers',
  },
  {
    slug: 'prize-money-vs-earnings',
    title: 'Prize Money vs Player Earnings',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'careers',
  },
  {
    slug: 'lower-ranked-player-finances',
    title: 'Why Lower-Ranked Tennis Players Struggle Financially',
    type: 'standard',
    difficulty: 'intermediate',
    category: 'careers',
  },

  // ── Advanced ───────────────────────────────────────────────────────────────
  {
    slug: 'elo-ratings',
    title: 'Elo Ratings in Tennis',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'ranking-vs-elo',
    title: 'Ranking vs Elo',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'hold-percentage',
    title: 'Hold Percentage',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'break-percentage',
    title: 'Break Percentage',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'service-points-won',
    title: 'Service Points Won',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'dominance-ratio',
    title: 'Dominance Ratio',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'surface-adjusted-performance',
    title: 'Surface-Adjusted Performance',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'strength-of-schedule',
    title: 'Strength of Schedule',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'clutch-performance',
    title: 'Clutch Performance',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'break-point-conversion',
    title: 'Break-Point Conversion',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'break-point-save-rate',
    title: 'Break-Point Save Rate',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'expected-hold-probability',
    title: 'Expected Hold Probability',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'serve-direction-analysis',
    title: 'Serve Direction Analysis',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'rally-length-analysis',
    title: 'Rally-Length Analysis',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'court-position-data',
    title: 'Court Position Data',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },
  {
    slug: 'head-to-head-analysis',
    title: 'Head-to-Head Matchup Analysis',
    type: 'statistic',
    difficulty: 'advanced',
    category: 'advanced',
  },

  // ── Glossary ───────────────────────────────────────────────────────────────
  // Terms that are not concepts elsewhere in the taxonomy. Everything else the
  // brief lists under the glossary (ace, deuce, love, slice, seed and the rest)
  // is already a row above and joins this category through `alsoIn`, because a
  // second row for the same word is exactly the duplication the merge-by-slug
  // seed exists to prevent.
  {
    slug: 'rally',
    title: 'Rally',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'crosscourt',
    title: 'Crosscourt',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'down-the-line',
    title: 'Down the Line',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'game-point',
    title: 'Game Point',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
  {
    slug: 'unseeded',
    title: 'Unseeded',
    type: 'definition',
    difficulty: 'beginner',
    category: 'glossary',
  },
];
